#!/usr/bin/env python3
"""배치 3: 비즈니스/과학/기술/의학/법률 전문 어휘 700개."""
from batch_utils import get_connection, get_existing_words, add_words, print_stats

def get_words():
    return [
        # ===== 비즈니스 (BUSINESS) =====
        ("acquisition", "/ˌækwɪˈzɪʃən/", "인수, 취득", "noun", "The company completed an acquisition.", "회사가 인수를 완료했습니다.", "BUSINESS", "COLLEGE", 4, "takeover, purchase", None, None),
        ("agenda", "/əˈdʒɛndə/", "안건, 의제", "noun", "What's on the agenda today?", "오늘 안건이 무엇인가요?", "BUSINESS", "HIGH_SCHOOL", 3, "schedule, program", None, None),
        ("asset", "/ˈæsɛt/", "자산", "noun", "The company has many assets.", "회사는 많은 자산을 가지고 있습니다.", "BUSINESS", "COLLEGE", 4, "resource, property", "liability", None),
        ("audit", "/ˈɔːdɪt/", "감사(하다)", "noun", "We need an internal audit.", "내부 감사가 필요합니다.", "BUSINESS", "COLLEGE", 4, "inspection, review", None, None),
        ("authorize", "/ˈɔːθəraɪz/", "승인하다", "verb", "Authorize the transaction.", "거래를 승인하세요.", "BUSINESS", "COLLEGE", 4, "approve, sanction", "deny, reject", None),
        ("benchmark", "/ˈbɛntʃmɑːrk/", "기준, 벤치마크", "noun", "Set a performance benchmark.", "성과 기준을 설정하세요.", "BUSINESS", "COLLEGE", 4, "standard, measure", None, None),
        ("brand", "/brænd/", "브랜드, 상표", "noun", "Build your personal brand.", "개인 브랜드를 구축하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "label, trademark", None, None),
        ("budget", "/ˈbʌdʒɪt/", "예산", "noun", "Stay within the budget.", "예산 범위 내에서 유지하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "funds, allowance", None, None),
        ("campaign", "/kæmˈpeɪn/", "캠페인, 운동", "noun", "Launch a marketing campaign.", "마케팅 캠페인을 시작하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "drive, initiative", None, None),
        ("candidate", "/ˈkændɪdɪt/", "후보자", "noun", "She is the best candidate.", "그녀가 최고의 후보자입니다.", "BUSINESS", "HIGH_SCHOOL", 3, "applicant, nominee", None, None),
        ("capital", "/ˈkæpɪtəl/", "자본, 수도", "noun", "We need more capital.", "더 많은 자본이 필요합니다.", "BUSINESS", "COLLEGE", 4, "funding, investment", None, None),
        ("collaborate", "/kəˈlæbəreɪt/", "협력하다", "verb", "Collaborate with your team.", "팀과 협력하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "cooperate, work together", "compete", None),
        ("commitment", "/kəˈmɪtmənt/", "헌신, 약속", "noun", "Show your commitment.", "헌신을 보여주세요.", "BUSINESS", "HIGH_SCHOOL", 3, "dedication, pledge", None, None),
        ("competitor", "/kəmˈpɛtɪtər/", "경쟁자", "noun", "Know your competitors.", "경쟁자를 파악하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "rival, opponent", "ally", None),
        ("compliance", "/kəmˈplaɪəns/", "준수, 순응", "noun", "Ensure regulatory compliance.", "규정 준수를 보장하세요.", "LAW", "COLLEGE", 4, "adherence, conformity", "violation", None),
        ("consulting", "/kənˈsʌltɪŋ/", "컨설팅", "noun", "She works in consulting.", "그녀는 컨설팅 분야에서 일합니다.", "BUSINESS", "COLLEGE", 4, "advising, counseling", None, None),
        ("consumer", "/kənˈsuːmər/", "소비자", "noun", "Consumer demand is growing.", "소비자 수요가 증가하고 있습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "customer, buyer", "producer", None),
        ("contract", "/ˈkɑːntrækt/", "계약하다", "verb", "They contracted for services.", "그들은 서비스 계약을 맺었습니다.", "LAW", "HIGH_SCHOOL", 3, "agree, negotiate", None, None),
        ("corporation", "/ˌkɔːrpəˈreɪʃən/", "기업, 법인", "noun", "She founded a corporation.", "그녀가 법인을 설립했습니다.", "BUSINESS", "COLLEGE", 4, "company, firm", None, None),
        ("cost", "/kɑːst/", "비용, 원가", "noun", "Reduce the cost.", "비용을 줄이세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "expense, price", "revenue, income", None),
        ("customer", "/ˈkʌstəmər/", "고객", "noun", "Customer service is important.", "고객 서비스가 중요합니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "client, buyer", "seller, vendor", None),
        ("deadline", "/ˈdɛdlaɪn/", "마감일, 기한", "noun", "Meet the deadline.", "마감일을 맞추세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "due date, cutoff", None, None),
        ("debt", "/dɛt/", "부채, 빚", "noun", "Pay off the debt.", "빚을 갚으세요.", "BUSINESS", "HIGH_SCHOOL", 3, "liability, obligation", "asset", None),
        ("delegate", "/ˈdɛlɪɡɪt/", "위임하다, 대표자", "verb", "Delegate tasks to your team.", "팀에게 업무를 위임하세요.", "BUSINESS", "COLLEGE", 4, "assign, entrust", None, None),
        ("dividend", "/ˈdɪvɪdɛnd/", "배당금", "noun", "Investors receive dividends.", "투자자들이 배당금을 받습니다.", "BUSINESS", "COLLEGE", 4, "share, return", None, None),
        ("efficient", "/ɪˈfɪʃənt/", "효율적인", "adjective", "Work in an efficient way.", "효율적인 방식으로 일하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "productive, effective", "inefficient, wasteful", None),
        ("entrepreneur", "/ˌɑːntrəprəˈnɜːr/", "기업가", "noun", "She is a successful entrepreneur.", "그녀는 성공한 기업가입니다.", "BUSINESS", "COLLEGE", 4, "founder, businessman", None, None),
        ("expense", "/ɪkˈspɛns/", "비용, 지출", "noun", "Submit your expense report.", "비용 보고서를 제출하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "cost, expenditure", "income, revenue", None),
        ("finance", "/ˈfaɪnæns/", "금융, 재정", "noun", "She works in finance.", "그녀는 금융 분야에서 일합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "funding, economy", None, None),
        ("forecast", "/ˈfɔːrkæst/", "예측, 예보", "noun", "The sales forecast is positive.", "판매 예측이 긍정적입니다.", "BUSINESS", "COLLEGE", 4, "prediction, outlook", None, None),
        ("headquarters", "/ˈhɛdˌkwɔːrtərz/", "본사", "noun", "Visit the headquarters.", "본사를 방문하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "head office, HQ", None, None),
        ("hire", "/haɪər/", "고용하다", "verb", "We need to hire more staff.", "직원을 더 고용해야 합니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "employ, recruit", "fire, dismiss", None),
        ("industry", "/ˈɪndəstri/", "산업", "noun", "The tech industry is growing.", "기술 산업이 성장하고 있습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "sector, field", None, None),
        ("inflation", "/ɪnˈfleɪʃən/", "인플레이션", "noun", "Inflation is rising.", "인플레이션이 오르고 있습니다.", "BUSINESS", "COLLEGE", 4, "price increase", "deflation", None),
        ("innovation", "/ˌɪnəˈveɪʃən/", "혁신", "noun", "Innovation drives growth.", "혁신이 성장을 이끕니다.", "BUSINESS", "HIGH_SCHOOL", 3, "invention, breakthrough", None, None),
        ("invest", "/ɪnˈvɛst/", "투자하다", "verb", "Invest wisely.", "현명하게 투자하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "fund, put money into", "withdraw", None),
        ("investor", "/ɪnˈvɛstər/", "투자자", "noun", "The investor funded the startup.", "투자자가 스타트업을 지원했습니다.", "BUSINESS", "COLLEGE", 4, "backer, funder", None, None),
        ("invoice", "/ˈɪnvɔɪs/", "청구서, 인보이스", "noun", "Send the invoice.", "청구서를 보내세요.", "BUSINESS", "HIGH_SCHOOL", 3, "bill, statement", None, None),
        ("launch", "/lɔːntʃ/", "출시하다, 시작하다", "verb", "Launch the new product.", "새 제품을 출시하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "introduce, release", "withdraw, cancel", None),
        ("liability", "/ˌlaɪəˈbɪlɪti/", "부채, 책임", "noun", "Know your legal liability.", "법적 책임을 알아야 합니다.", "LAW", "COLLEGE", 4, "obligation, debt", "asset", None),
        ("logistics", "/ləˈdʒɪstɪks/", "물류", "noun", "Handle the logistics.", "물류를 처리하세요.", "BUSINESS", "COLLEGE", 4, "supply chain, distribution", None, None),
        ("marketing", "/ˈmɑːrkɪtɪŋ/", "마케팅", "noun", "Marketing drives sales.", "마케팅이 판매를 이끕니다.", "BUSINESS", "HIGH_SCHOOL", 3, "promotion, advertising", None, None),
        ("merger", "/ˈmɜːrdʒər/", "합병", "noun", "The merger was successful.", "합병이 성공적이었습니다.", "BUSINESS", "COLLEGE", 4, "combination, union", "split, separation", None),
        ("negotiate", "/nɪˈɡoʊʃieɪt/", "협상하다", "verb", "Negotiate a better price.", "더 좋은 가격을 협상하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "bargain, discuss", None, None),
        ("objective", "/əbˈdʒɛktɪv/", "목표", "noun", "Set clear objectives.", "명확한 목표를 설정하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "goal, target", None, None),
        ("outsource", "/ˈaʊtsɔːrs/", "외주하다", "verb", "Outsource non-core activities.", "핵심이 아닌 활동을 외주하세요.", "BUSINESS", "COLLEGE", 4, "contract out, delegate", "insource", None),
        ("partnership", "/ˈpɑːrtnərʃɪp/", "파트너십, 협력 관계", "noun", "Form a business partnership.", "사업 파트너십을 맺으세요.", "BUSINESS", "HIGH_SCHOOL", 3, "collaboration, alliance", "competition", None),
        ("patent", "/ˈpeɪtənt/", "특허", "noun", "File a patent application.", "특허 신청을 하세요.", "LAW", "COLLEGE", 4, "intellectual property, license", None, None),
        ("pension", "/ˈpɛnʃən/", "연금", "noun", "Save for your pension.", "연금을 위해 저축하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "retirement fund", None, None),
        ("pitch", "/pɪtʃ/", "제안하다, 발표하다", "verb", "Pitch your idea to investors.", "투자자에게 아이디어를 제안하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "present, propose", None, None),
        ("portfolio", "/pɔːrtˈfoʊlioʊ/", "포트폴리오", "noun", "Build a strong portfolio.", "강력한 포트폴리오를 구축하세요.", "BUSINESS", "COLLEGE", 4, "collection, investment", None, None),
        ("profit", "/ˈprɑːfɪt/", "이익, 수익", "noun", "The company made a profit.", "회사가 이익을 냈습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "earnings, gain", "loss", None),
        ("promotion", "/prəˈmoʊʃən/", "승진, 홍보", "noun", "She got a promotion.", "그녀가 승진했습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "advancement, advertising", "demotion", None),
        ("proposal", "/prəˈpoʊzəl/", "제안(서)", "noun", "Submit a business proposal.", "사업 제안서를 제출하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "offer, plan", "rejection", None),
        ("prototype", "/ˈproʊtətaɪp/", "프로토타입", "noun", "Build a prototype first.", "먼저 프로토타입을 만드세요.", "TECHNOLOGY", "COLLEGE", 4, "model, sample", None, None),
        ("purchase", "/ˈpɜːrtʃɪs/", "구매하다", "verb", "Purchase the materials.", "자재를 구매하세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "buy, acquire", "sell", None),
        ("quarterly", "/ˈkwɔːrtərli/", "분기별의", "adjective", "Review the quarterly report.", "분기 보고서를 검토하세요.", "BUSINESS", "COLLEGE", 4, "every three months", None, None),
        ("quota", "/ˈkwoʊtə/", "할당량", "noun", "Meet your sales quota.", "판매 할당량을 달성하세요.", "BUSINESS", "COLLEGE", 4, "limit, allocation", None, None),
        ("recession", "/rɪˈsɛʃən/", "경기 침체", "noun", "The economy is in recession.", "경제가 침체에 빠져 있습니다.", "BUSINESS", "COLLEGE", 4, "downturn, slump", "boom, growth", None),
        ("recruit", "/rɪˈkruːt/", "채용하다", "verb", "Recruit the best talent.", "최고의 인재를 채용하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "hire, employ", "fire, dismiss", None),
        ("revenue", "/ˈrɛvɪnjuː/", "수익, 매출", "noun", "Revenue increased by 20%.", "수익이 20% 증가했습니다.", "BUSINESS", "COLLEGE", 4, "income, earnings", "expenditure", None),
        ("risk", "/rɪsk/", "위험, 위험을 무릅쓰다", "noun", "Assess the risks.", "위험을 평가하세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "danger, hazard", "safety", None),
        ("salary", "/ˈsæləri/", "월급, 봉급", "noun", "What is your salary?", "월급이 얼마인가요?", "BUSINESS", "MIDDLE_SCHOOL", 2, "wage, pay", None, None),
        ("sales", "/seɪlz/", "판매, 영업", "noun", "Sales are increasing.", "판매가 증가하고 있습니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "revenue, marketing", None, None),
        ("shareholder", "/ˈʃɛrhoʊldər/", "주주", "noun", "Shareholders voted on the merger.", "주주들이 합병에 찬성 투표를 했습니다.", "BUSINESS", "COLLEGE", 4, "investor, stockholder", None, None),
        ("startup", "/ˈstɑːrtʌp/", "스타트업", "noun", "She founded a startup.", "그녀가 스타트업을 설립했습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "new company, venture", None, None),
        ("stock", "/stɑːk/", "주식, 재고", "noun", "Invest in stocks.", "주식에 투자하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "shares, inventory", None, None),
        ("supplier", "/səˈplaɪər/", "공급자", "noun", "Find a reliable supplier.", "믿을 수 있는 공급자를 찾으세요.", "BUSINESS", "COLLEGE", 4, "vendor, provider", "consumer, buyer", None),
        ("sustainable", "/səˈsteɪnəbəl/", "지속 가능한", "adjective", "Pursue sustainable growth.", "지속 가능한 성장을 추구하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "lasting, enduring", "unsustainable", None),
        ("tax", "/tæks/", "세금", "noun", "Pay your taxes on time.", "세금을 제때 내세요.", "LAW", "MIDDLE_SCHOOL", 2, "levy, duty", None, None),
        ("transaction", "/trænˈzækʃən/", "거래", "noun", "Complete the transaction.", "거래를 완료하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "deal, exchange", None, None),
        ("vendor", "/ˈvɛndər/", "판매자, 공급업체", "noun", "Choose the best vendor.", "최고의 공급업체를 선택하세요.", "BUSINESS", "COLLEGE", 4, "seller, supplier", "buyer, customer", None),
        ("vision", "/ˈvɪʒən/", "비전, 시각", "noun", "Share your company vision.", "회사 비전을 공유하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "goal, mission", None, None),
        ("workforce", "/ˈwɜːrkfɔːrs/", "노동력, 인력", "noun", "Train your workforce.", "인력을 교육하세요.", "BUSINESS", "COLLEGE", 4, "employees, staff", None, None),

        # ===== 기술/IT (TECHNOLOGY) =====
        ("algorithm", "/ˈælɡərɪðəm/", "알고리즘", "noun", "This algorithm sorts data.", "이 알고리즘은 데이터를 정렬합니다.", "TECHNOLOGY", "COLLEGE", 4, "procedure, process", None, None),
        ("application", "/ˌæplɪˈkeɪʃən/", "앱, 애플리케이션", "noun", "Download the application.", "앱을 다운로드하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "app, software", None, None),
        ("artificial", "/ˌɑːrtɪˈfɪʃəl/", "인공의, 인위적인", "adjective", "Artificial intelligence is growing.", "인공지능이 성장하고 있습니다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "synthetic, man-made", "natural, organic", None),
        ("backup", "/ˈbækʌp/", "백업", "noun", "Always make a backup.", "항상 백업을 만드세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "copy, duplicate", None, None),
        ("bandwidth", "/ˈbændwɪdθ/", "대역폭", "noun", "Increase the bandwidth.", "대역폭을 늘리세요.", "TECHNOLOGY", "COLLEGE", 4, "capacity, speed", None, None),
        ("browser", "/ˈbraʊzər/", "브라우저", "noun", "Open your web browser.", "웹 브라우저를 여세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("cable", "/ˈkeɪbəl/", "케이블, 선", "noun", "Connect the cable.", "케이블을 연결하세요.", "TECHNOLOGY", "ELEMENTARY", 1, "wire, cord", None, None),
        ("cloud", "/klaʊd/", "클라우드", "noun", "Store data in the cloud.", "데이터를 클라우드에 저장하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "online storage", None, None),
        ("code", "/koʊd/", "코드, 암호", "noun", "Write clean code.", "깔끔한 코드를 작성하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "program, script", None, None),
        ("data", "/ˈdeɪtə/", "데이터, 자료", "noun", "Analyze the data.", "데이터를 분석하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "information, facts", None, None),
        ("database", "/ˈdeɪtəbeɪs/", "데이터베이스", "noun", "Update the database.", "데이터베이스를 업데이트하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "storage, repository", None, None),
        ("debug", "/diːˈbʌɡ/", "디버그하다", "verb", "Debug the program.", "프로그램을 디버그하세요.", "TECHNOLOGY", "COLLEGE", 4, "fix, troubleshoot", None, None),
        ("device", "/dɪˈvaɪs/", "장치, 기기", "noun", "Use the right device.", "올바른 장치를 사용하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "gadget, instrument", None, None),
        ("digital", "/ˈdɪdʒɪtəl/", "디지털의", "adjective", "We live in a digital age.", "우리는 디지털 시대에 살고 있습니다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "electronic, online", "analog", None),
        ("download", "/ˈdaʊnloʊd/", "다운로드하다", "verb", "Download the file.", "파일을 다운로드하세요.", "TECHNOLOGY", "ELEMENTARY", 1, None, "upload", None),
        ("encrypt", "/ɪnˈkrɪpt/", "암호화하다", "verb", "Encrypt your data.", "데이터를 암호화하세요.", "TECHNOLOGY", "COLLEGE", 4, "encode, secure", "decrypt", None),
        ("firewall", "/ˈfaɪərwɔːl/", "방화벽", "noun", "Enable the firewall.", "방화벽을 활성화하세요.", "TECHNOLOGY", "COLLEGE", 4, "security barrier", None, None),
        ("framework", "/ˈfreɪmwɜːrk/", "프레임워크, 틀", "noun", "Use a reliable framework.", "신뢰할 수 있는 프레임워크를 사용하세요.", "TECHNOLOGY", "COLLEGE", 4, "structure, system", None, None),
        ("hardware", "/ˈhɑːrdwɛr/", "하드웨어", "noun", "Upgrade your hardware.", "하드웨어를 업그레이드하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "equipment, components", "software", None),
        ("install", "/ɪnˈstɔːl/", "설치하다", "verb", "Install the software.", "소프트웨어를 설치하세요.", "TECHNOLOGY", "ELEMENTARY", 1, "set up, configure", "uninstall, remove", None),
        ("interface", "/ˈɪntərfeɪs/", "인터페이스", "noun", "The user interface is intuitive.", "사용자 인터페이스가 직관적입니다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "UI, design", None, None),
        ("internet", "/ˈɪntərnɛt/", "인터넷", "noun", "Access the internet.", "인터넷에 접속하세요.", "TECHNOLOGY", "ELEMENTARY", 1, "web, online", None, None),
        ("keyboard", "/ˈkiːbɔːrd/", "키보드", "noun", "Clean the keyboard.", "키보드를 청소하세요.", "TECHNOLOGY", "ELEMENTARY", 1, None, None, None),
        ("laptop", "/ˈlæptɑːp/", "노트북", "noun", "I use a laptop.", "노트북을 사용합니다.", "TECHNOLOGY", "ELEMENTARY", 1, "notebook, computer", None, None),
        ("log in", "/lɑːɡ ɪn/", "로그인하다", "verb", "Log in to your account.", "계정에 로그인하세요.", "TECHNOLOGY", "ELEMENTARY", 1, "sign in, access", "log out", None),
        ("monitor", "/ˈmɑːnɪtər/", "모니터, 감시하다", "noun", "Adjust the monitor.", "모니터를 조정하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "screen, display", None, None),
        ("network", "/ˈnɛtwɜːrk/", "네트워크", "noun", "Connect to the network.", "네트워크에 연결하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "system, connection", None, None),
        ("password", "/ˈpæswɜːrd/", "비밀번호", "noun", "Use a strong password.", "강력한 비밀번호를 사용하세요.", "TECHNOLOGY", "ELEMENTARY", 1, "passcode, credential", None, None),
        ("platform", "/ˈplætfɔːrm/", "플랫폼", "noun", "Choose the right platform.", "올바른 플랫폼을 선택하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "system, environment", None, None),
        ("plugin", "/ˈplʌɡɪn/", "플러그인", "noun", "Install the plugin.", "플러그인을 설치하세요.", "TECHNOLOGY", "COLLEGE", 4, "extension, add-on", None, None),
        ("privacy", "/ˈprɪvəsi/", "개인 정보 보호, 프라이버시", "noun", "Protect your privacy.", "개인 정보를 보호하세요.", "LAW", "HIGH_SCHOOL", 3, "confidentiality, security", None, None),
        ("robot", "/ˈroʊbɑːt/", "로봇", "noun", "The robot performs tasks.", "로봇이 작업을 수행합니다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "machine, automaton", None, None),
        ("server", "/ˈsɜːrvər/", "서버", "noun", "The server is down.", "서버가 다운되었습니다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "host, computer", None, None),
        ("software", "/ˈsɑːftwɛr/", "소프트웨어", "noun", "Update your software.", "소프트웨어를 업데이트하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "program, app", "hardware", None),
        ("storage", "/ˈstɔːrɪdʒ/", "저장소", "noun", "More storage is needed.", "저장소가 더 필요합니다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "space, memory", None, None),
        ("update", "/ˈʌpdeɪt/", "업데이트하다", "verb", "Update the app.", "앱을 업데이트하세요.", "TECHNOLOGY", "ELEMENTARY", 1, "upgrade, refresh", "downgrade", None),
        ("upload", "/ˈʌploʊd/", "업로드하다", "verb", "Upload the file.", "파일을 업로드하세요.", "TECHNOLOGY", "ELEMENTARY", 1, None, "download", None),
        ("username", "/ˈjuːzərneɪm/", "사용자 이름", "noun", "Enter your username.", "사용자 이름을 입력하세요.", "TECHNOLOGY", "ELEMENTARY", 1, "account name", None, None),
        ("virtual", "/ˈvɜːrtʃuəl/", "가상의", "adjective", "Join the virtual meeting.", "가상 회의에 참여하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, "online, digital", "physical, real", None),
        ("virus", "/ˈvaɪrəs/", "바이러스", "noun", "Scan for viruses.", "바이러스를 검사하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "malware, bug", None, None),
        ("wireless", "/ˈwaɪərləs/", "무선의", "adjective", "Use wireless headphones.", "무선 헤드폰을 사용하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "Wi-Fi, Bluetooth", "wired", None),

        # ===== 의학 (MEDICINE) =====
        ("allergy", "/ˈælərdʒi/", "알레르기", "noun", "I have a food allergy.", "음식 알레르기가 있습니다.", "MEDICINE", "MIDDLE_SCHOOL", 2, "sensitivity, reaction", None, None),
        ("ambulance", "/ˈæmbjuləns/", "구급차", "noun", "Call an ambulance.", "구급차를 불러주세요.", "MEDICINE", "ELEMENTARY", 1, "emergency vehicle", None, None),
        ("antibiotic", "/ˌæntɪbaɪˈɑːtɪk/", "항생제", "noun", "Take the antibiotic.", "항생제를 복용하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "medicine, drug", None, None),
        ("appointment", "/əˈpɔɪntmənt/", "진료 예약", "noun", "Book a doctor's appointment.", "의사 진료를 예약하세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "booking, meeting", None, None),
        ("bandage", "/ˈbændɪdʒ/", "붕대", "noun", "Apply a bandage.", "붕대를 감으세요.", "MEDICINE", "ELEMENTARY", 1, "dressing, wrap", None, None),
        ("blood", "/blʌd/", "혈액, 피", "noun", "Give blood to help others.", "헌혈로 다른 사람을 도와주세요.", "MEDICINE", "ELEMENTARY", 1, None, None, None),
        ("cancer", "/ˈkænsər/", "암", "noun", "Early cancer detection is important.", "암의 조기 발견이 중요합니다.", "MEDICINE", "HIGH_SCHOOL", 3, "tumor, malignancy", None, None),
        ("chronic", "/ˈkrɑːnɪk/", "만성적인", "adjective", "Chronic pain is difficult.", "만성 통증은 힘듭니다.", "MEDICINE", "HIGH_SCHOOL", 3, "persistent, ongoing", "acute, temporary", None),
        ("clinic", "/ˈklɪnɪk/", "의원, 클리닉", "noun", "Visit the clinic.", "의원을 방문하세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "hospital, medical center", None, None),
        ("cough", "/kɔːf/", "기침하다", "verb", "He has been coughing all day.", "그는 하루 종일 기침을 했습니다.", "MEDICINE", "ELEMENTARY", 1, None, None, None),
        ("cure", "/kjʊr/", "치료하다, 치료제", "verb", "Find a cure for cancer.", "암 치료제를 찾으세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "heal, treat", "cause", None),
        ("dental", "/ˈdɛntəl/", "치아의, 치과의", "adjective", "Get a dental check-up.", "치과 검진을 받으세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "oral, tooth", None, None),
        ("diabetes", "/ˌdaɪəˈbiːtɪs/", "당뇨병", "noun", "Manage your diabetes.", "당뇨병을 관리하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "blood sugar disorder", None, None),
        ("diagnose", "/ˈdaɪəɡnoʊz/", "진단하다", "verb", "The doctor diagnosed flu.", "의사가 독감을 진단했습니다.", "MEDICINE", "HIGH_SCHOOL", 3, "identify, detect", None, None),
        ("diet", "/ˈdaɪɪt/", "식단, 다이어트", "noun", "Follow a healthy diet.", "건강한 식단을 따르세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "nutrition, eating plan", None, None),
        ("dose", "/doʊs/", "복용량", "noun", "Take the correct dose.", "올바른 복용량을 복용하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "amount, quantity", None, None),
        ("emergency", "/ɪˈmɜːrdʒənsi/", "응급, 비상", "noun", "In case of emergency, call 119.", "응급 상황에서는 119에 전화하세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "crisis, urgent situation", None, None),
        ("fever", "/ˈfiːvər/", "열", "noun", "She has a high fever.", "그녀는 고열이 있습니다.", "MEDICINE", "ELEMENTARY", 1, "temperature, heat", None, None),
        ("fracture", "/ˈfræktʃər/", "골절", "noun", "She suffered a fracture.", "그녀는 골절을 당했습니다.", "MEDICINE", "HIGH_SCHOOL", 3, "break, crack", None, None),
        ("headache", "/ˈhɛdeɪk/", "두통", "noun", "I have a headache.", "두통이 있습니다.", "MEDICINE", "ELEMENTARY", 1, "migraine, pain", None, None),
        ("hospital", "/ˈhɑːspɪtəl/", "병원", "noun", "He is in the hospital.", "그는 병원에 있습니다.", "MEDICINE", "ELEMENTARY", 1, "medical center, clinic", None, None),
        ("immune", "/ɪˈmjuːn/", "면역의", "adjective", "Build your immune system.", "면역 체계를 강화하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "resistant, protected", "vulnerable, susceptible", None),
        ("infection", "/ɪnˈfɛkʃən/", "감염", "noun", "Prevent the infection.", "감염을 예방하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "contamination, disease", None, None),
        ("medicine", "/ˈmɛdɪsɪn/", "약, 의학", "noun", "Take your medicine.", "약을 복용하세요.", "MEDICINE", "ELEMENTARY", 1, "drug, medication", None, None),
        ("mental", "/ˈmɛntəl/", "정신적인", "adjective", "Mental health is important.", "정신 건강이 중요합니다.", "MEDICINE", "MIDDLE_SCHOOL", 2, "psychological, emotional", "physical", None),
        ("nurse", "/nɜːrs/", "간호사", "noun", "The nurse is very caring.", "간호사는 매우 배려심이 깊습니다.", "MEDICINE", "ELEMENTARY", 1, "caregiver", None, None),
        ("nutrition", "/njuːˈtrɪʃən/", "영양", "noun", "Good nutrition is essential.", "좋은 영양은 필수입니다.", "MEDICINE", "HIGH_SCHOOL", 3, "diet, food intake", None, None),
        ("obesity", "/oʊˈbiːsɪti/", "비만", "noun", "Prevent obesity with exercise.", "운동으로 비만을 예방하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "overweight, excess weight", None, None),
        ("operation", "/ˌɑːpəˈreɪʃən/", "수술", "noun", "The operation was successful.", "수술이 성공적이었습니다.", "MEDICINE", "MIDDLE_SCHOOL", 2, "surgery, procedure", None, None),
        ("pain", "/peɪn/", "고통, 통증", "noun", "The pain is unbearable.", "통증이 참을 수 없습니다.", "MEDICINE", "ELEMENTARY", 1, "ache, discomfort", "relief, comfort", None),
        ("patient", "/ˈpeɪʃənt/", "환자", "noun", "The patient needs rest.", "환자는 휴식이 필요합니다.", "MEDICINE", "MIDDLE_SCHOOL", 2, "sick person", None, None),
        ("pharmacy", "/ˈfɑːrməsi/", "약국", "noun", "Go to the pharmacy.", "약국에 가세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "drugstore", None, None),
        ("prescription", "/prɪˈskrɪpʃən/", "처방전", "noun", "Get a prescription from the doctor.", "의사에게 처방전을 받으세요.", "MEDICINE", "HIGH_SCHOOL", 3, "order, medication", None, None),
        ("pulse", "/pʌls/", "맥박", "noun", "Check your pulse.", "맥박을 확인하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "heartbeat, rhythm", None, None),
        ("recover", "/rɪˈkʌvər/", "회복하다", "verb", "She will recover soon.", "그녀는 곧 회복할 것입니다.", "MEDICINE", "MIDDLE_SCHOOL", 2, "heal, get better", "worsen", None),
        ("surgery", "/ˈsɜːrdʒəri/", "수술", "noun", "He needs surgery.", "그는 수술이 필요합니다.", "MEDICINE", "HIGH_SCHOOL", 3, "operation, procedure", None, None),
        ("symptom", "/ˈsɪmptəm/", "증상", "noun", "List your symptoms.", "증상을 나열하세요.", "MEDICINE", "HIGH_SCHOOL", 3, "sign, indication", None, None),
        ("therapy", "/ˈθɛrəpi/", "치료, 요법", "noun", "She is undergoing therapy.", "그녀는 치료를 받고 있습니다.", "MEDICINE", "HIGH_SCHOOL", 3, "treatment, healing", None, None),
        ("vaccine", "/væˈksiːn/", "백신", "noun", "Get vaccinated.", "예방접종을 받으세요.", "MEDICINE", "HIGH_SCHOOL", 3, "immunization, shot", None, None),

        # ===== 과학 (SCIENCE) =====
        ("atom", "/ˈætəm/", "원자", "noun", "Matter is made of atoms.", "물질은 원자로 이루어져 있습니다.", "SCIENCE", "HIGH_SCHOOL", 3, "particle, element", None, None),
        ("biology", "/baɪˈɑːlədʒi/", "생물학", "noun", "She studies biology.", "그녀는 생물학을 공부합니다.", "SCIENCE", "HIGH_SCHOOL", 3, "life science", None, None),
        ("cell", "/sɛl/", "세포", "noun", "Every living thing has cells.", "모든 생명체는 세포를 가집니다.", "SCIENCE", "HIGH_SCHOOL", 3, "unit, organism", None, None),
        ("chemistry", "/ˈkɛmɪstri/", "화학", "noun", "Chemistry is fascinating.", "화학은 매력적입니다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("climate", "/ˈklaɪmɪt/", "기후", "noun", "Study the climate patterns.", "기후 패턴을 연구하세요.", "SCIENCE", "MIDDLE_SCHOOL", 2, "weather, atmosphere", None, None),
        ("DNA", "/ˌdiː ɛn ˈeɪ/", "DNA, 유전자", "noun", "DNA carries genetic information.", "DNA는 유전 정보를 담고 있습니다.", "SCIENCE", "HIGH_SCHOOL", 4, "gene, genetic material", None, None),
        ("ecology", "/ɪˈkɑːlədʒi/", "생태학", "noun", "Study ecology to understand nature.", "자연을 이해하려면 생태학을 공부하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "environmental science", None, None),
        ("electricity", "/ɪˌlɛkˈtrɪsɪti/", "전기", "noun", "Electricity powers our homes.", "전기가 우리 집을 밝힙니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "power, current", None, None),
        ("element", "/ˈɛlɪmənt/", "원소, 요소", "noun", "There are 118 known elements.", "알려진 원소는 118개입니다.", "SCIENCE", "HIGH_SCHOOL", 3, "substance, component", None, None),
        ("evolution", "/ˌɛvəˈluːʃən/", "진화", "noun", "Evolution explains diversity.", "진화가 다양성을 설명합니다.", "SCIENCE", "HIGH_SCHOOL", 3, "development, progression", None, None),
        ("experiment", "/ɪkˈspɛrɪmənt/", "실험", "noun", "Conduct an experiment.", "실험을 수행하세요.", "SCIENCE", "MIDDLE_SCHOOL", 2, "test, trial", None, None),
        ("fossil", "/ˈfɑːsəl/", "화석", "noun", "The fossil was millions of years old.", "화석은 수백만 년 된 것이었습니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "remains, artifact", None, None),
        ("galaxy", "/ˈɡæləksi/", "은하", "noun", "Our galaxy is the Milky Way.", "우리 은하는 은하수입니다.", "SCIENCE", "HIGH_SCHOOL", 3, "star system", None, None),
        ("gene", "/dʒiːn/", "유전자", "noun", "Genes determine our traits.", "유전자가 우리의 특성을 결정합니다.", "SCIENCE", "HIGH_SCHOOL", 3, "DNA, heredity", None, None),
        ("gravity", "/ˈɡrævɪti/", "중력", "noun", "Gravity pulls things down.", "중력이 물체를 아래로 당깁니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "force, pull", None, None),
        ("hypothesis", "/haɪˈpɑːθɪsɪs/", "가설", "noun", "Test your hypothesis.", "가설을 검증하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "theory, assumption", "proof, fact", None),
        ("laboratory", "/ˈlæbrətɔːri/", "실험실", "noun", "Work in the laboratory.", "실험실에서 작업하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "lab, research facility", None, None),
        ("magnetic", "/mæɡˈnɛtɪk/", "자기의, 자석의", "adjective", "Magnetic fields are powerful.", "자기장은 강력합니다.", "SCIENCE", "HIGH_SCHOOL", 3, "attractive, electromagnetic", None, None),
        ("microscope", "/ˈmaɪkrəskoʊp/", "현미경", "noun", "Use a microscope to view cells.", "세포를 보려면 현미경을 사용하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "magnifier", None, None),
        ("molecule", "/ˈmɑːlɪkjuːl/", "분자", "noun", "Water is made of molecules.", "물은 분자로 이루어져 있습니다.", "SCIENCE", "HIGH_SCHOOL", 3, "particle, compound", None, None),
        ("orbit", "/ˈɔːrbɪt/", "궤도, 돌다", "noun", "The Earth orbits the sun.", "지구가 태양 주위를 돕니다.", "SCIENCE", "HIGH_SCHOOL", 3, "path, revolution", None, None),
        ("organism", "/ˈɔːrɡənɪzəm/", "생물체", "noun", "Every organism needs energy.", "모든 생물체는 에너지가 필요합니다.", "SCIENCE", "HIGH_SCHOOL", 3, "living thing, creature", None, None),
        ("oxygen", "/ˈɑːksɪdʒən/", "산소", "noun", "Oxygen is essential for life.", "산소는 생명에 필수적입니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "gas, element", None, None),
        ("particle", "/ˈpɑːrtɪkəl/", "입자", "noun", "Small particles make up matter.", "작은 입자가 물질을 이룹니다.", "SCIENCE", "HIGH_SCHOOL", 3, "atom, speck", None, None),
        ("physics", "/ˈfɪzɪks/", "물리학", "noun", "Physics explains the universe.", "물리학은 우주를 설명합니다.", "SCIENCE", "HIGH_SCHOOL", 3, "natural science", None, None),
        ("planet", "/ˈplænɪt/", "행성", "noun", "Saturn is a beautiful planet.", "토성은 아름다운 행성입니다.", "SCIENCE", "ELEMENTARY", 1, "world, celestial body", None, None),
        ("pollution", "/pəˈluːʃən/", "오염", "noun", "Reduce air pollution.", "대기 오염을 줄이세요.", "SCIENCE", "MIDDLE_SCHOOL", 2, "contamination", "purification", None),
        ("radiation", "/ˌreɪdiˈeɪʃən/", "방사선, 복사", "noun", "Avoid harmful radiation.", "해로운 방사선을 피하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "rays, emission", None, None),
        ("renewable", "/rɪˈnjuːəbəl/", "재생 가능한", "adjective", "Use renewable energy.", "재생 가능 에너지를 사용하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "sustainable, green", "nonrenewable", None),
        ("satellite", "/ˈsætəlaɪt/", "위성", "noun", "A satellite orbits Earth.", "위성이 지구 주위를 돕니다.", "SCIENCE", "HIGH_SCHOOL", 3, "moon, spacecraft", None, None),
        ("species", "/ˈspiːʃiːz/", "종(種)", "noun", "Many species are endangered.", "많은 종이 멸종 위기에 처해 있습니다.", "SCIENCE", "HIGH_SCHOOL", 3, "type, category", None, None),
        ("telescope", "/ˈtɛlɪskoʊp/", "망원경", "noun", "Look at stars with a telescope.", "망원경으로 별을 보세요.", "SCIENCE", "MIDDLE_SCHOOL", 2, "viewer, instrument", None, None),
        ("temperature", "/ˈtɛmprɪtʃər/", "온도, 기온", "noun", "Check the temperature.", "온도를 확인하세요.", "SCIENCE", "ELEMENTARY", 1, "heat, degree", None, None),
        ("universe", "/ˈjuːnɪvɜːrs/", "우주", "noun", "The universe is vast.", "우주는 광활합니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "cosmos, space", None, None),
        ("vitamin", "/ˈvaɪtəmɪn/", "비타민", "noun", "Take your vitamins.", "비타민을 드세요.", "MEDICINE", "ELEMENTARY", 1, "nutrient, supplement", None, None),

        # ===== 법률 (LAW) =====
        ("appeal", "/əˈpiːl/", "항소하다, 호소하다", "verb", "Appeal the court decision.", "법원 판결에 항소하세요.", "LAW", "COLLEGE", 4, "challenge, contest", None, None),
        ("arrest", "/əˈrɛst/", "체포하다", "verb", "Police arrested the suspect.", "경찰이 용의자를 체포했습니다.", "LAW", "HIGH_SCHOOL", 3, "detain, apprehend", "release", None),
        ("attorney", "/əˈtɜːrni/", "변호사", "noun", "Hire an attorney.", "변호사를 고용하세요.", "LAW", "HIGH_SCHOOL", 3, "lawyer, counsel", None, None),
        ("bail", "/beɪl/", "보석금", "noun", "He was released on bail.", "그는 보석금으로 석방되었습니다.", "LAW", "COLLEGE", 4, "bond, surety", None, None),
        ("constitution", "/ˌkɑːnstɪˈtuːʃən/", "헌법", "noun", "The constitution protects rights.", "헌법이 권리를 보호합니다.", "LAW", "HIGH_SCHOOL", 3, "law, charter", None, None),
        ("court", "/kɔːrt/", "법원, 법정", "noun", "The case went to court.", "사건이 법원으로 갔습니다.", "LAW", "MIDDLE_SCHOOL", 2, "tribunal, judiciary", None, None),
        ("crime", "/kraɪm/", "범죄", "noun", "Crime is decreasing.", "범죄가 줄어들고 있습니다.", "LAW", "MIDDLE_SCHOOL", 2, "offense, violation", None, None),
        ("criminal", "/ˈkrɪmɪnəl/", "범죄자, 범죄의", "noun", "The criminal was convicted.", "범죄자가 유죄 판결을 받았습니다.", "LAW", "MIDDLE_SCHOOL", 2, "offender, lawbreaker", None, None),
        ("defendant", "/dɪˈfɛndənt/", "피고인", "noun", "The defendant pleaded not guilty.", "피고인은 무죄를 주장했습니다.", "LAW", "COLLEGE", 4, "accused, respondent", "plaintiff", None),
        ("evidence", "/ˈɛvɪdəns/", "증거", "noun", "Provide evidence.", "증거를 제시하세요.", "LAW", "HIGH_SCHOOL", 3, "proof, testimony", None, None),
        ("fine", "/faɪn/", "벌금", "noun", "Pay the fine.", "벌금을 내세요.", "LAW", "MIDDLE_SCHOOL", 2, "penalty, fee", None, None),
        ("fraud", "/frɔːd/", "사기", "noun", "Report fraud immediately.", "즉시 사기를 신고하세요.", "LAW", "HIGH_SCHOOL", 3, "deception, scam", "honesty", None),
        ("guilty", "/ˈɡɪlti/", "유죄의", "adjective", "The jury found him guilty.", "배심원단이 그를 유죄로 판결했습니다.", "LAW", "MIDDLE_SCHOOL", 2, "at fault, responsible", "innocent, not guilty", None),
        ("judge", "/dʒʌdʒ/", "판사, 판단하다", "noun", "The judge made a ruling.", "판사가 판결을 내렸습니다.", "LAW", "MIDDLE_SCHOOL", 2, "magistrate", None, None),
        ("jury", "/ˈdʒʊri/", "배심원단", "noun", "The jury deliberated for hours.", "배심원단이 수 시간 동안 심의했습니다.", "LAW", "HIGH_SCHOOL", 3, "panel, committee", None, None),
        ("lawsuit", "/ˈlɔːsuːt/", "소송", "noun", "File a lawsuit.", "소송을 제기하세요.", "LAW", "COLLEGE", 4, "case, suit", None, None),
        ("lawyer", "/ˈlɔɪər/", "변호사", "noun", "Consult a lawyer.", "변호사와 상담하세요.", "LAW", "MIDDLE_SCHOOL", 2, "attorney, counsel", None, None),
        ("legislation", "/ˌlɛdʒɪˈsleɪʃən/", "법률, 입법", "noun", "New legislation was passed.", "새 법률이 통과되었습니다.", "LAW", "COLLEGE", 4, "law, statute", None, None),
        ("license", "/ˈlaɪsəns/", "면허, 허가", "noun", "Get a driver's license.", "운전면허를 취득하세요.", "LAW", "MIDDLE_SCHOOL", 2, "permit, certificate", None, None),
        ("penalty", "/ˈpɛnəlti/", "처벌, 벌금", "noun", "The penalty is severe.", "처벌이 가혹합니다.", "LAW", "HIGH_SCHOOL", 3, "punishment, fine", "reward", None),
        ("permit", "/ˈpɜːrmɪt/", "허가증, 허가하다", "noun", "You need a work permit.", "취업 허가증이 필요합니다.", "LAW", "HIGH_SCHOOL", 3, "license, authorization", "prohibition", None),
        ("plaintiff", "/ˈpleɪntɪf/", "원고", "noun", "The plaintiff filed a lawsuit.", "원고가 소송을 제기했습니다.", "LAW", "COLLEGE", 4, "complainant, claimant", "defendant", None),
        ("prison", "/ˈprɪzən/", "감옥", "noun", "He went to prison.", "그는 감옥에 갔습니다.", "LAW", "MIDDLE_SCHOOL", 2, "jail, penitentiary", None, None),
        ("proof", "/pruːf/", "증거, 증명", "noun", "Show proof of identity.", "신원 증명을 보여주세요.", "LAW", "MIDDLE_SCHOOL", 2, "evidence, verification", None, None),
        ("regulation", "/ˌrɛɡjuˈleɪʃən/", "규정, 법규", "noun", "Follow safety regulations.", "안전 규정을 따르세요.", "LAW", "HIGH_SCHOOL", 3, "rule, law", None, None),
        ("sentence", "/ˈsɛntəns/", "판결, 문장", "noun", "He received a five-year sentence.", "그는 5년 형을 선고받았습니다.", "LAW", "HIGH_SCHOOL", 3, "punishment, ruling", None, None),
        ("testimony", "/ˈtɛstɪmoʊni/", "증언", "noun", "Give your testimony.", "증언을 하세요.", "LAW", "COLLEGE", 4, "statement, evidence", None, None),
        ("trial", "/ˈtraɪəl/", "재판, 시도", "noun", "The trial begins next week.", "재판이 다음 주에 시작됩니다.", "LAW", "HIGH_SCHOOL", 3, "court case, hearing", None, None),
        ("verdict", "/ˈvɜːrdɪkt/", "평결, 판결", "noun", "The verdict was not guilty.", "평결은 무죄였습니다.", "LAW", "COLLEGE", 4, "decision, ruling", None, None),
        ("violation", "/ˌvaɪəˈleɪʃən/", "위반", "noun", "Report any violations.", "위반 사항을 신고하세요.", "LAW", "HIGH_SCHOOL", 3, "breach, infringement", "compliance", None),
        ("witness", "/ˈwɪtnəs/", "목격자, 증인", "noun", "The witness testified.", "증인이 증언했습니다.", "LAW", "HIGH_SCHOOL", 3, "observer, bystander", None, None),
    ]


if __name__ == "__main__":
    conn = get_connection()
    existing = get_existing_words(conn)
    words = get_words()
    added = add_words(conn, words, existing)
    print(f"배치 3: {added}개 단어 추가")
    print_stats(conn, "배치 3: 비즈니스/전문 어휘")
    conn.close()
