#!/usr/bin/env python3
"""배치 8: 일상생활/기술/의학/환경/사회 대량 어휘"""

import sys
import sqlite3
sys.path.insert(0, '.')
from batch_utils import get_connection, get_existing_words, add_words

def main():
    conn = get_connection()
    existing = get_existing_words(conn)

    words_data = [
        # 일상 동사 (DAILY_LIFE)
        ("accomplish", "/əˈkʌmplɪʃ/", "이루다, 달성하다", "verb", "She accomplished her goal after years of effort.", "그녀는 수년간의 노력 끝에 목표를 달성했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("acquire", "/əˈkwaɪər/", "습득하다, 얻다", "verb", "He acquired new skills through online courses.", "그는 온라인 강좌를 통해 새로운 기술을 습득했다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("adjust", "/əˈdʒʌst/", "조정하다, 적응하다", "verb", "It took time to adjust to the new environment.", "새로운 환경에 적응하는 데 시간이 걸렸다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("admire", "/ədˈmaɪər/", "존경하다, 감탄하다", "verb", "Everyone admired her courage and determination.", "모든 사람이 그녀의 용기와 결단력을 존경했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("afford", "/əˈfɔːrd/", "여유가 되다, 제공하다", "verb", "We can't afford to take any risks right now.", "우리는 지금 어떤 위험도 감수할 여유가 없다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("annoy", "/əˈnɔɪ/", "짜증나게 하다", "verb", "The loud music annoyed the neighbors.", "시끄러운 음악이 이웃들을 짜증나게 했다.", "DAILY_LIFE", "ELEMENTARY", 2, None, None, None),
        ("arrange", "/əˈreɪndʒ/", "정리하다, 준비하다", "verb", "Can you arrange a meeting for next Monday?", "다음 월요일 회의를 준비해 줄 수 있나요?", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("assist", "/əˈsɪst/", "돕다, 지원하다", "verb", "The volunteers assisted in cleaning the park.", "자원봉사자들은 공원 청소를 도왔다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("attempt", "/əˈtempt/", "시도하다; 시도", "verb", "She attempted to climb the mountain alone.", "그녀는 혼자 산을 오르려 시도했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("avoid", "/əˈvɔɪd/", "피하다", "verb", "Try to avoid eating too much sugar.", "설탕을 너무 많이 먹는 것을 피하도록 노력하세요.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("borrow", "/ˈbɒroʊ/", "빌리다", "verb", "Can I borrow your pen for a moment?", "잠깐 펜을 빌릴 수 있나요?", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("celebrate", "/ˈselɪbreɪt/", "축하하다, 기념하다", "verb", "The whole city celebrated the team's victory.", "온 도시가 팀의 승리를 축하했다.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("commit", "/kəˈmɪt/", "약속하다, 저지르다", "verb", "He committed himself to helping the community.", "그는 지역사회를 돕겠다고 약속했다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("complain", "/kəmˈpleɪn/", "불평하다, 항의하다", "verb", "Several customers complained about the service.", "여러 고객들이 서비스에 대해 불평했다.", "DAILY_LIFE", "ELEMENTARY", 2, None, None, None),
        ("concentrate", "/ˈkɒnsəntreɪt/", "집중하다", "verb", "It's hard to concentrate with so much noise.", "이렇게 시끄러운 소리에는 집중하기 어렵다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("confuse", "/kənˈfjuːz/", "혼란스럽게 하다", "verb", "The instructions confused everyone.", "지침이 모든 사람을 혼란스럽게 했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("connect", "/kəˈnekt/", "연결하다", "verb", "The bridge connects the two islands.", "다리가 두 섬을 연결한다.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("consume", "/kənˈsjuːm/", "소비하다, 섭취하다", "verb", "Modern society consumes too many resources.", "현대 사회는 너무 많은 자원을 소비한다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("convince", "/kənˈvɪns/", "설득하다, 확신시키다", "verb", "She convinced him to change his mind.", "그녀는 그가 마음을 바꾸도록 설득했다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("delay", "/dɪˈleɪ/", "지연하다; 지연", "verb", "The flight was delayed by two hours.", "비행기가 두 시간 지연되었다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("deny", "/dɪˈnaɪ/", "부인하다, 거부하다", "verb", "He denied any involvement in the crime.", "그는 범죄에 관여하지 않았다고 부인했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("deserve", "/dɪˈzɜːrv/", "~할 자격이 있다, 받을 만하다", "verb", "She deserves a promotion for her hard work.", "그녀는 열심히 일한 것에 대한 승진을 받을 만하다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("disagree", "/ˌdɪsəˈɡriː/", "동의하지 않다", "verb", "I disagree with your assessment.", "나는 당신의 평가에 동의하지 않는다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("disappoint", "/ˌdɪsəˈpɔɪnt/", "실망시키다", "verb", "The movie disappointed many fans.", "그 영화는 많은 팬들을 실망시켰다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("encourage", "/ɪnˈkɜːrɪdʒ/", "격려하다, 장려하다", "verb", "Parents should encourage their children to read.", "부모는 자녀들이 책을 읽도록 장려해야 한다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("entertain", "/ˌentərˈteɪn/", "즐겁게 하다, 접대하다", "verb", "The comedian entertained the audience for hours.", "코미디언은 몇 시간 동안 관객을 즐겁게 했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("establish", "/ɪˈstæblɪʃ/", "설립하다, 확립하다", "verb", "They established a new company last year.", "그들은 작년에 새 회사를 설립했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("evaluate", "/ɪˈvæljueɪt/", "평가하다", "verb", "We need to evaluate the results carefully.", "우리는 결과를 신중하게 평가해야 한다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("examine", "/ɪɡˈzæmɪn/", "검사하다, 조사하다", "verb", "The doctor examined the patient thoroughly.", "의사는 환자를 철저히 검사했다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("exhaust", "/ɪɡˈzɔːst/", "지치게 하다, 고갈시키다", "verb", "The long journey exhausted everyone.", "긴 여정은 모든 사람을 지치게 했다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("expand", "/ɪkˈspænd/", "확장하다, 펼치다", "verb", "The company plans to expand into new markets.", "회사는 새로운 시장으로 확장할 계획이다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("extend", "/ɪkˈstend/", "연장하다, 확대하다", "verb", "They extended the deadline by one week.", "그들은 마감 기한을 일주일 연장했다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("favor", "/ˈfeɪvər/", "호의; 선호하다", "noun", "Can you do me a favor?", "부탁 하나 들어줄 수 있어요?", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("forgive", "/fərˈɡɪv/", "용서하다", "verb", "It's important to forgive and move on.", "용서하고 앞으로 나아가는 것이 중요하다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("fulfill", "/fʊlˈfɪl/", "이행하다, 충족시키다", "verb", "He fulfilled his promise to his parents.", "그는 부모님께 한 약속을 이행했다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("gather", "/ˈɡæðər/", "모이다, 수집하다", "verb", "Friends gathered to celebrate her birthday.", "친구들이 그녀의 생일을 축하하기 위해 모였다.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("handle", "/ˈhændəl/", "다루다, 처리하다", "verb", "She handles complaints professionally.", "그녀는 불만을 전문적으로 처리한다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("hesitate", "/ˈhezɪteɪt/", "망설이다, 주저하다", "verb", "Don't hesitate to ask if you need help.", "도움이 필요하면 주저하지 말고 물어보세요.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("ignore", "/ɪɡˈnɔːr/", "무시하다", "verb", "She ignored his advice and did it her way.", "그녀는 그의 조언을 무시하고 자신의 방식으로 했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("involve", "/ɪnˈvɒlv/", "포함하다, 관련시키다", "verb", "The project involves many different departments.", "그 프로젝트는 여러 다른 부서를 포함한다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("launch", "/lɔːntʃ/", "시작하다, 발사하다; 출시", "verb", "They launched the new product in spring.", "그들은 봄에 새 제품을 출시했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("manage", "/ˈmænɪdʒ/", "관리하다, 해내다", "verb", "How do you manage to stay so calm?", "어떻게 그렇게 침착하게 유지하는 건가요?", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("mention", "/ˈmenʃən/", "언급하다", "verb", "He mentioned her name in his speech.", "그는 연설에서 그녀의 이름을 언급했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("motivate", "/ˈmoʊtɪveɪt/", "동기를 부여하다", "verb", "Good leaders know how to motivate their teams.", "좋은 리더는 팀에게 동기를 부여하는 방법을 안다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("negotiate", "/nɪˈɡoʊʃieɪt/", "협상하다", "verb", "The union negotiated a better contract.", "노조는 더 나은 계약을 협상했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("obtain", "/əbˈteɪn/", "얻다, 획득하다", "verb", "He obtained his medical license after years of study.", "그는 수년간의 공부 끝에 의사 면허를 취득했다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("overcome", "/ˌoʊvərˈkʌm/", "극복하다", "verb", "She overcame many obstacles to achieve her goal.", "그녀는 목표를 달성하기 위해 많은 장애물을 극복했다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("participate", "/pɑːrˈtɪsɪpeɪt/", "참여하다", "verb", "All students are encouraged to participate.", "모든 학생들은 참여하도록 권장된다.", "EDUCATION", "MIDDLE_SCHOOL", 2, None, None, None),
        ("perform", "/pərˈfɔːrm/", "수행하다, 공연하다", "verb", "The surgeon performed the operation successfully.", "외과 의사는 수술을 성공적으로 수행했다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("persuade", "/pərˈsweɪd/", "설득하다", "verb", "She persuaded him to try the new restaurant.", "그녀는 그를 새 식당을 시도해보도록 설득했다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("plan", "/plæn/", "계획하다; 계획", "verb", "We need to plan our vacation in advance.", "우리는 미리 휴가를 계획해야 한다.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("postpone", "/poʊstˈpoʊn/", "연기하다, 미루다", "verb", "The meeting was postponed until Friday.", "회의가 금요일로 연기되었다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("predict", "/prɪˈdɪkt/", "예측하다", "verb", "Scientists can predict earthquakes to some extent.", "과학자들은 어느 정도 지진을 예측할 수 있다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("prefer", "/prɪˈfɜːr/", "선호하다", "verb", "Do you prefer tea or coffee?", "차를 더 좋아하나요, 아니면 커피를 더 좋아하나요?", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("prevent", "/prɪˈvent/", "예방하다, 막다", "verb", "Vaccinations help prevent many diseases.", "예방접종은 많은 질병을 예방하는 데 도움이 된다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("produce", "/prəˈdjuːs/", "생산하다, 만들다", "verb", "The factory produces thousands of cars daily.", "공장은 매일 수천 대의 자동차를 생산한다.", "BUSINESS", "ELEMENTARY", 2, None, None, None),
        ("protect", "/prəˈtekt/", "보호하다", "verb", "We must protect endangered species.", "우리는 멸종 위기종을 보호해야 한다.", "SCIENCE", "ELEMENTARY", 1, None, None, None),
        ("recover", "/rɪˈkʌvər/", "회복하다, 되찾다", "verb", "She recovered quickly from the surgery.", "그녀는 수술에서 빠르게 회복했다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("reduce", "/rɪˈdjuːs/", "줄이다, 감소시키다", "verb", "We need to reduce our carbon footprint.", "우리는 탄소 발자국을 줄여야 한다.", "SCIENCE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("reflect", "/rɪˈflekt/", "반사하다, 반영하다; 숙고하다", "verb", "The prices reflect the current market conditions.", "가격은 현재 시장 상황을 반영한다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("release", "/rɪˈliːs/", "출시하다, 석방하다; 출시", "verb", "The company released its new product last month.", "회사는 지난달 새 제품을 출시했다.", "BUSINESS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("replace", "/rɪˈpleɪs/", "대체하다, 교체하다", "verb", "We need to replace the broken window.", "우리는 깨진 창문을 교체해야 한다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("represent", "/ˌreprɪˈzent/", "대표하다, 나타내다", "verb", "The painting represents freedom and hope.", "그 그림은 자유와 희망을 나타낸다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("request", "/rɪˈkwest/", "요청하다; 요청", "verb", "She requested a refund for the damaged item.", "그녀는 손상된 물건에 대한 환불을 요청했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("resolve", "/rɪˈzɒlv/", "해결하다, 결심하다", "verb", "They resolved their differences through dialogue.", "그들은 대화를 통해 차이를 해결했다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("respond", "/rɪˈspɒnd/", "반응하다, 대응하다", "verb", "Please respond to the email by tomorrow.", "내일까지 이메일에 답해주세요.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("restore", "/rɪˈstɔːr/", "복원하다, 복구하다", "verb", "Workers restored the old painting carefully.", "작업자들은 낡은 그림을 신중하게 복원했다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("reveal", "/rɪˈviːl/", "드러내다, 밝히다", "verb", "The investigation revealed shocking evidence.", "조사는 충격적인 증거를 드러냈다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("satisfy", "/ˈsætɪsfaɪ/", "만족시키다", "verb", "The solution satisfied all the requirements.", "해결책은 모든 요구사항을 만족시켰다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("select", "/sɪˈlekt/", "선택하다, 고르다", "verb", "Carefully select the best candidates.", "최고의 후보들을 신중하게 선택하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("separate", "/ˈsepəreɪt/", "분리하다; 별개의", "verb", "The teacher separated the students into groups.", "선생님은 학생들을 그룹으로 나눴다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("share", "/ʃeər/", "공유하다, 나누다", "verb", "Please share your ideas with the group.", "그룹과 아이디어를 공유해 주세요.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("solve", "/sɒlv/", "해결하다, 풀다", "verb", "Can you solve this math problem?", "이 수학 문제를 풀 수 있나요?", "EDUCATION", "ELEMENTARY", 1, None, None, None),
        ("struggle", "/ˈstrʌɡəl/", "어려움을 겪다, 노력하다; 투쟁", "verb", "Many families struggle to make ends meet.", "많은 가정이 생계를 유지하기 위해 어려움을 겪는다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, None, None, None),
        ("submit", "/səbˈmɪt/", "제출하다, 복종하다", "verb", "Please submit your assignment by Friday.", "금요일까지 과제를 제출해 주세요.", "EDUCATION", "MIDDLE_SCHOOL", 2, None, None, None),
        ("succeed", "/səkˈsiːd/", "성공하다, 계승하다", "verb", "She succeeded in passing the difficult exam.", "그녀는 어려운 시험에 합격하는 데 성공했다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("suggest", "/səˈdʒest/", "제안하다, 암시하다", "verb", "I suggest we take a short break.", "잠깐 휴식을 취하는 것을 제안합니다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("supply", "/səˈplaɪ/", "공급하다; 공급", "verb", "The store supplies all kinds of electronic equipment.", "그 가게는 모든 종류의 전자 장비를 공급한다.", "BUSINESS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("transform", "/trænsˈfɔːrm/", "변환하다, 변형시키다", "verb", "The new park transformed the neighborhood.", "새 공원이 동네를 변화시켰다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("translate", "/trænsˈleɪt/", "번역하다", "verb", "Can you translate this document into Korean?", "이 문서를 한국어로 번역해 줄 수 있나요?", "EDUCATION", "MIDDLE_SCHOOL", 2, None, None, None),
        ("update", "/ʌpˈdeɪt/", "업데이트하다, 갱신하다", "verb", "Please update your contact information.", "연락처 정보를 업데이트해 주세요.", "TECHNOLOGY", "ELEMENTARY", 2, None, None, None),
        ("waste", "/weɪst/", "낭비하다; 낭비", "verb", "Don't waste water during a drought.", "가뭄 때는 물을 낭비하지 마세요.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, None),
        ("worship", "/ˈwɜːrʃɪp/", "숭배하다, 예배하다", "verb", "People worship at the temple every Sunday.", "사람들은 매주 일요일 사원에서 예배드린다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),

        # 기술/IT 어휘
        ("algorithm", "/ˈælɡərɪðəm/", "알고리즘", "noun", "The search engine uses a complex algorithm.", "검색 엔진은 복잡한 알고리즘을 사용한다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("application", "/ˌæplɪˈkeɪʃən/", "응용 프로그램, 애플리케이션; 지원", "noun", "Download the application from the app store.", "앱 스토어에서 애플리케이션을 다운로드하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("artificial", "/ˌɑːrtɪˈfɪʃəl/", "인공의, 인위적인", "adjective", "Artificial intelligence is changing many industries.", "인공지능이 많은 산업을 변화시키고 있다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("automation", "/ˌɔːtəˈmeɪʃən/", "자동화", "noun", "Automation has increased efficiency in manufacturing.", "자동화는 제조업의 효율성을 높였다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("bandwidth", "/ˈbændwɪdθ/", "대역폭", "noun", "Streaming video requires a lot of bandwidth.", "스트리밍 비디오는 많은 대역폭이 필요하다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("binary", "/ˈbaɪnəri/", "이진법의; 이진수", "adjective", "Computers use binary code to process information.", "컴퓨터는 정보를 처리하기 위해 이진 코드를 사용한다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("blockchain", "/ˈblɒktʃeɪn/", "블록체인", "noun", "Blockchain technology ensures secure transactions.", "블록체인 기술은 안전한 거래를 보장한다.", "TECHNOLOGY", "COLLEGE", 4, None, None, None),
        ("cache", "/kæʃ/", "캐시; 캐시에 저장하다", "noun", "Clear your browser cache to improve performance.", "성능을 개선하려면 브라우저 캐시를 지우세요.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("chip", "/tʃɪp/", "칩, 반도체", "noun", "The new chip is twice as fast as the previous one.", "새 칩은 이전 것보다 두 배 빠르다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("circuit", "/ˈsɜːrkɪt/", "회로", "noun", "The short circuit caused the power outage.", "단락이 정전을 야기했다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("cloud", "/klaʊd/", "클라우드; 구름", "noun", "All our data is stored in the cloud.", "우리의 모든 데이터는 클라우드에 저장되어 있다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("compatible", "/kəmˈpætɪbəl/", "호환되는, 양립할 수 있는", "adjective", "Is this software compatible with my computer?", "이 소프트웨어가 내 컴퓨터와 호환되나요?", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("compile", "/kəmˈpaɪl/", "컴파일하다, 편집하다", "verb", "The program compiles code into machine language.", "프로그램은 코드를 기계 언어로 컴파일한다.", "TECHNOLOGY", "COLLEGE", 4, None, None, None),
        ("configuration", "/kənˌfɪɡjʊˈreɪʃən/", "구성, 설정", "noun", "Check your network configuration settings.", "네트워크 구성 설정을 확인하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("connect", "/kəˈnekt/", "연결하다", "verb", "Connect the cable to the USB port.", "케이블을 USB 포트에 연결하세요.", "TECHNOLOGY", "ELEMENTARY", 1, None, None, None),
        ("cyber", "/ˈsaɪbər/", "사이버", "adjective", "Cyber attacks on businesses are increasing.", "기업에 대한 사이버 공격이 증가하고 있다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("database", "/ˈdeɪtəbeɪs/", "데이터베이스", "noun", "The company maintains a large customer database.", "회사는 대규모 고객 데이터베이스를 유지한다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("debug", "/diːˈbʌɡ/", "디버그하다, 오류를 수정하다", "verb", "It took hours to debug the program.", "프로그램을 디버그하는 데 몇 시간이 걸렸다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("deploy", "/dɪˈplɔɪ/", "배포하다, 배치하다", "verb", "The team deployed the new software update.", "팀은 새 소프트웨어 업데이트를 배포했다.", "TECHNOLOGY", "COLLEGE", 4, None, None, None),
        ("device", "/dɪˈvaɪs/", "기기, 장치", "noun", "Smartphones are the most popular mobile devices.", "스마트폰은 가장 인기 있는 모바일 기기이다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("digital", "/ˈdɪdʒɪtəl/", "디지털의", "adjective", "We live in a digital age.", "우리는 디지털 시대에 살고 있다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("domain", "/dəˈmeɪn/", "도메인; 영역", "noun", "The company registered its domain name.", "회사는 도메인 이름을 등록했다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("download", "/ˈdaʊnloʊd/", "다운로드하다", "verb", "Download the app before the meeting.", "회의 전에 앱을 다운로드하세요.", "TECHNOLOGY", "ELEMENTARY", 2, None, None, None),
        ("encrypt", "/ɪnˈkrɪpt/", "암호화하다", "verb", "Personal data should always be encrypted.", "개인 정보는 항상 암호화되어야 한다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("firewall", "/ˈfaɪərwɔːl/", "방화벽", "noun", "A firewall protects the network from hackers.", "방화벽은 해커로부터 네트워크를 보호한다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("firmware", "/ˈfɜːrmweər/", "펌웨어", "noun", "Update your device's firmware regularly.", "기기의 펌웨어를 정기적으로 업데이트하세요.", "TECHNOLOGY", "COLLEGE", 4, None, None, None),
        ("framework", "/ˈfreɪmwɜːrk/", "프레임워크, 틀", "noun", "The developer used a popular JavaScript framework.", "개발자는 인기 있는 JavaScript 프레임워크를 사용했다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("gigabyte", "/ˈɡɪɡəbaɪt/", "기가바이트", "noun", "The file is 5 gigabytes in size.", "파일 크기는 5기가바이트이다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("hacker", "/ˈhækər/", "해커", "noun", "Hackers compromised the company's security system.", "해커가 회사의 보안 시스템을 침해했다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("hardware", "/ˈhɑːrdweər/", "하드웨어", "noun", "The hardware needs to be upgraded.", "하드웨어를 업그레이드해야 한다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("innovation", "/ˌɪnəˈveɪʃən/", "혁신", "noun", "Innovation drives economic growth.", "혁신은 경제 성장을 이끈다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("interface", "/ˈɪntərfeɪs/", "인터페이스", "noun", "The user interface is intuitive and easy to use.", "사용자 인터페이스는 직관적이고 사용하기 쉽다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("internet", "/ˈɪntərnet/", "인터넷", "noun", "The internet has changed the way we communicate.", "인터넷은 우리가 소통하는 방식을 변화시켰다.", "TECHNOLOGY", "ELEMENTARY", 1, None, None, None),
        ("iterate", "/ˈɪtəreɪt/", "반복하다, 되풀이하다", "verb", "The team iterated on the design multiple times.", "팀은 디자인을 여러 번 반복했다.", "TECHNOLOGY", "COLLEGE", 4, None, None, None),
        ("latency", "/ˈleɪtənsi/", "지연 시간", "noun", "High latency causes lag in online games.", "높은 지연 시간은 온라인 게임에서 렉을 야기한다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("malware", "/ˈmælweər/", "악성 소프트웨어", "noun", "Install antivirus software to prevent malware.", "악성 소프트웨어를 방지하기 위해 바이러스 백신 소프트웨어를 설치하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("migrate", "/ˈmaɪɡreɪt/", "이동하다, 마이그레이션하다", "verb", "The company migrated its data to the cloud.", "회사는 데이터를 클라우드로 마이그레이션했다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("mobile", "/ˈmoʊbaɪl/", "모바일의, 이동 가능한", "adjective", "Mobile payments are becoming more popular.", "모바일 결제가 점점 더 인기를 끌고 있다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("network", "/ˈnetwɜːrk/", "네트워크, 망", "noun", "The office network was down for an hour.", "사무실 네트워크가 한 시간 동안 다운되었다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("offline", "/ˈɒflaɪn/", "오프라인의", "adjective", "The app can work offline without internet access.", "그 앱은 인터넷 없이 오프라인으로 작동할 수 있다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("optimize", "/ˈɒptɪmaɪz/", "최적화하다", "verb", "We need to optimize the code for better performance.", "더 나은 성능을 위해 코드를 최적화해야 한다.", "TECHNOLOGY", "HIGH_SCHOOL", 4, None, None, None),
        ("password", "/ˈpɑːswɜːrd/", "비밀번호", "noun", "Use a strong password with numbers and symbols.", "숫자와 기호가 포함된 강력한 비밀번호를 사용하세요.", "TECHNOLOGY", "ELEMENTARY", 2, None, None, None),
        ("pixel", "/ˈpɪksəl/", "픽셀", "noun", "The screen has a high pixel density.", "화면은 높은 픽셀 밀도를 가지고 있다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("platform", "/ˈplætfɔːrm/", "플랫폼", "noun", "The app is available on multiple platforms.", "앱은 여러 플랫폼에서 사용 가능하다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("plugin", "/ˈplʌɡɪn/", "플러그인", "noun", "Install the plugin to add more features.", "더 많은 기능을 추가하려면 플러그인을 설치하세요.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("privacy", "/ˈprɪvəsi/", "프라이버시, 개인 정보 보호", "noun", "Data privacy is a growing concern.", "데이터 프라이버시는 증가하는 우려 사항이다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("processor", "/ˈprɒsesər/", "프로세서", "noun", "The new processor is much faster than the old one.", "새 프로세서는 이전 것보다 훨씬 빠르다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("programming", "/ˈproʊɡræmɪŋ/", "프로그래밍", "noun", "Programming skills are in high demand.", "프로그래밍 기술은 수요가 높다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("reboot", "/ˌriːˈbuːt/", "재부팅하다", "verb", "Reboot the system to apply the changes.", "변경 사항을 적용하려면 시스템을 재부팅하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("resolution", "/ˌrezəˈluːʃən/", "해상도; 해결", "noun", "The screen has a 4K resolution.", "화면은 4K 해상도를 가지고 있다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("robot", "/ˈroʊbɒt/", "로봇", "noun", "Robots are increasingly used in manufacturing.", "로봇은 제조업에서 점점 더 많이 사용된다.", "TECHNOLOGY", "ELEMENTARY", 2, None, None, None),
        ("scalable", "/ˈskeɪləbəl/", "확장 가능한", "adjective", "The architecture needs to be scalable.", "아키텍처는 확장 가능해야 한다.", "TECHNOLOGY", "COLLEGE", 4, None, None, None),
        ("sensor", "/ˈsensər/", "센서", "noun", "Motion sensors detect movement in the room.", "모션 센서는 방의 움직임을 감지한다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("server", "/ˈsɜːrvər/", "서버", "noun", "The website is hosted on multiple servers.", "웹사이트는 여러 서버에서 호스팅된다.", "TECHNOLOGY", "HIGH_SCHOOL", 3, None, None, None),
        ("software", "/ˈsɒftweər/", "소프트웨어", "noun", "The software needs to be updated regularly.", "소프트웨어는 정기적으로 업데이트되어야 한다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("storage", "/ˈstɔːrɪdʒ/", "저장 공간, 보관", "noun", "Cloud storage is more flexible than local storage.", "클라우드 스토리지는 로컬 스토리지보다 유연하다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("streaming", "/ˈstriːmɪŋ/", "스트리밍", "noun", "Video streaming services have replaced traditional TV.", "비디오 스트리밍 서비스가 전통적인 TV를 대체했다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),
        ("wireless", "/ˈwaɪərləs/", "무선의", "adjective", "The office uses a wireless network.", "사무실은 무선 네트워크를 사용한다.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, None, None, None),

        # 의학/건강 어휘
        ("acute", "/əˈkjuːt/", "급성의; 심각한", "adjective", "He was admitted for acute appendicitis.", "그는 급성 충수염으로 입원했다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("allergy", "/ˈælərgi/", "알레르기", "noun", "She has a severe peanut allergy.", "그녀는 심한 땅콩 알레르기가 있다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("anesthesia", "/ˌænɪsˈθiːziə/", "마취", "noun", "The patient was put under general anesthesia.", "환자는 전신 마취를 받았다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("antibiotic", "/ˌæntɪbaɪˈɒtɪk/", "항생제", "noun", "The doctor prescribed antibiotics for the infection.", "의사는 감염에 대한 항생제를 처방했다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("artery", "/ˈɑːrtəri/", "동맥", "noun", "Blocked arteries can lead to heart attacks.", "막힌 동맥은 심장 발작으로 이어질 수 있다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("biopsy", "/ˈbaɪɒpsi/", "생검", "noun", "A biopsy was performed to check for cancer.", "암을 확인하기 위해 생검이 시행되었다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("blood pressure", "/ˌblʌd ˈpreʃər/", "혈압", "noun", "High blood pressure increases the risk of stroke.", "고혈압은 뇌졸중의 위험을 높인다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("cardiac", "/ˈkɑːrdiæk/", "심장의", "adjective", "He underwent cardiac surgery last month.", "그는 지난달 심장 수술을 받았다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("chronic", "/ˈkrɒnɪk/", "만성적인", "adjective", "He suffers from chronic back pain.", "그는 만성 요통을 앓고 있다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("clinical", "/ˈklɪnɪkəl/", "임상적인", "adjective", "Clinical trials are conducted to test new drugs.", "임상 시험은 새로운 약물을 테스트하기 위해 실시된다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("contagious", "/kənˈteɪdʒəs/", "전염성의", "adjective", "The flu is highly contagious.", "독감은 전염성이 높다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("diagnosis", "/ˌdaɪəɡˈnoʊsɪs/", "진단", "noun", "The doctor made a diagnosis based on the symptoms.", "의사는 증상을 바탕으로 진단을 내렸다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("disease", "/dɪˈziːz/", "질병", "noun", "Many diseases can now be prevented by vaccines.", "많은 질병은 이제 백신으로 예방될 수 있다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("dosage", "/ˈdoʊsɪdʒ/", "용량", "noun", "Follow the prescribed dosage carefully.", "처방된 용량을 신중하게 따르세요.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("genetic", "/dʒɪˈnetɪk/", "유전적인", "adjective", "Some diseases have a genetic component.", "일부 질병은 유전적인 요소가 있다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("immune", "/ɪˈmjuːn/", "면역의, 면역이 있는", "adjective", "A healthy immune system fights off infections.", "건강한 면역 체계는 감염을 막아낸다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("inflammation", "/ˌɪnfləˈmeɪʃən/", "염증", "noun", "Inflammation is a natural response to injury.", "염증은 부상에 대한 자연적인 반응이다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("malignant", "/məˈlɪɡnənt/", "악성의", "adjective", "The biopsy revealed a malignant tumor.", "생검에서 악성 종양이 발견되었다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("metabolism", "/məˈtæbəlɪzəm/", "신진대사", "noun", "Exercise boosts your metabolism.", "운동은 신진대사를 촉진한다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("nutrition", "/njuːˈtrɪʃən/", "영양", "noun", "Good nutrition is essential for health.", "좋은 영양은 건강에 필수적이다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("obesity", "/oʊˈbiːsɪti/", "비만", "noun", "Obesity increases the risk of diabetes.", "비만은 당뇨병의 위험을 높인다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("organ", "/ˈɔːrɡən/", "장기; 기관", "noun", "The liver is a vital organ.", "간은 중요한 장기이다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("pathogen", "/ˈpæθədʒən/", "병원균, 병원체", "noun", "The pathogen was identified as a new strain of virus.", "병원체는 바이러스의 새로운 변종으로 확인되었다.", "MEDICINE", "COLLEGE", 4, None, None, None),
        ("pharmaceutical", "/ˌfɑːrməˈsuːtɪkəl/", "제약의", "adjective", "The pharmaceutical industry develops life-saving drugs.", "제약 산업은 생명을 구하는 약물을 개발한다.", "MEDICINE", "COLLEGE", 4, None, None, None),
        ("physiology", "/ˌfɪziˈɒlədʒi/", "생리학", "noun", "She studied physiology at university.", "그녀는 대학에서 생리학을 공부했다.", "MEDICINE", "COLLEGE", 4, None, None, None),
        ("prognosis", "/prɒɡˈnoʊsɪs/", "예후, 예측", "noun", "The prognosis for the patient was encouraging.", "환자의 예후는 희망적이었다.", "MEDICINE", "COLLEGE", 4, None, None, None),
        ("prescription", "/prɪˈskrɪpʃən/", "처방전", "noun", "You need a prescription for that medication.", "그 약물에는 처방전이 필요합니다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("psychiatric", "/ˌsaɪkiˈætrɪk/", "정신과의", "adjective", "She received psychiatric treatment for depression.", "그녀는 우울증으로 정신과 치료를 받았다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("pulse", "/pʌls/", "맥박, 박동", "noun", "The nurse checked the patient's pulse.", "간호사는 환자의 맥박을 확인했다.", "MEDICINE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("rehabilitation", "/ˌriːhəˌbɪlɪˈteɪʃən/", "재활", "noun", "Physical rehabilitation helped him regain mobility.", "물리 재활은 그가 이동성을 되찾는 데 도움이 됐다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("relapse", "/ˈriːlæps/", "재발", "noun", "The patient suffered a relapse of the disease.", "환자는 질병의 재발을 겪었다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("remedy", "/ˈremədi/", "치료제, 해결책", "noun", "There is no simple remedy for this condition.", "이 상태에 대한 간단한 치료제는 없다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("respiratory", "/rɪˈspɪrətɔːri/", "호흡기의", "adjective", "Air pollution causes many respiratory diseases.", "대기 오염은 많은 호흡기 질환을 야기한다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("syndrome", "/ˈsɪndroʊm/", "증후군", "noun", "He was diagnosed with metabolic syndrome.", "그는 대사 증후군으로 진단받았다.", "MEDICINE", "HIGH_SCHOOL", 4, None, None, None),
        ("therapy", "/ˈθerəpi/", "치료", "noun", "She benefited greatly from cognitive therapy.", "그녀는 인지 치료로 큰 도움을 받았다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("tissue", "/ˈtɪʃuː/", "조직; 티슈", "noun", "The damaged tissue was removed during surgery.", "손상된 조직은 수술 중에 제거되었다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("tumor", "/ˈtjuːmər/", "종양", "noun", "Surgery removed the benign tumor.", "수술로 양성 종양을 제거했다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("vaccine", "/ˈvæksiːn/", "백신", "noun", "Scientists developed a new vaccine for the flu.", "과학자들은 독감에 대한 새로운 백신을 개발했다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),
        ("vein", "/veɪn/", "정맥", "noun", "Blood was drawn from a vein in her arm.", "혈액은 그녀의 팔의 정맥에서 채취되었다.", "MEDICINE", "HIGH_SCHOOL", 3, None, None, None),

        # 환경/과학 어휘
        ("atmosphere", "/ˈætməsfɪər/", "대기; 분위기", "noun", "Carbon dioxide accumulates in the atmosphere.", "이산화탄소는 대기에 축적된다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("biodiversity", "/ˌbaɪoʊdaɪˈvɜːrsɪti/", "생물 다양성", "noun", "Protecting biodiversity is crucial for ecosystems.", "생물 다양성 보호는 생태계에 매우 중요하다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("carbon", "/ˈkɑːrbən/", "탄소", "noun", "Reducing carbon emissions is a global priority.", "탄소 배출량 감소는 세계적인 우선 사항이다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("climate", "/ˈklaɪmɪt/", "기후", "noun", "The climate in this region is mild.", "이 지역의 기후는 온화하다.", "SCIENCE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("contamination", "/kənˌtæmɪˈneɪʃən/", "오염", "noun", "Soil contamination is difficult to remediate.", "토양 오염은 복구하기 어렵다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("coral", "/ˈkɒrəl/", "산호", "noun", "Coral reefs are under threat from warming oceans.", "산호초는 온난화하는 바다로 위협받고 있다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("decompose", "/ˌdiːkəmˈpoʊz/", "분해하다", "verb", "Organic matter decomposes over time.", "유기물은 시간이 지남에 따라 분해된다.", "SCIENCE", "HIGH_SCHOOL", 4, None, None, None),
        ("deforestation", "/ˌdiːˌfɒrɪˈsteɪʃən/", "삼림 벌채", "noun", "Deforestation is destroying natural habitats.", "삼림 벌채는 자연 서식지를 파괴하고 있다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("drought", "/draʊt/", "가뭄", "noun", "The drought lasted for three years.", "가뭄은 3년 동안 계속되었다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("ecosystem", "/ˈiːkoʊsɪstəm/", "생태계", "noun", "Pollution damages the delicate ecosystem.", "오염은 섬세한 생태계를 손상시킨다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("emission", "/ɪˈmɪʃən/", "배출, 방출", "noun", "Greenhouse gas emissions must be reduced.", "온실 가스 배출량을 줄여야 한다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("erosion", "/ɪˈroʊʒən/", "침식", "noun", "Soil erosion is a major problem in dry regions.", "토양 침식은 건조한 지역에서 주요한 문제이다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("fossil", "/ˈfɒsəl/", "화석", "noun", "Scientists discovered dinosaur fossils in the desert.", "과학자들은 사막에서 공룡 화석을 발견했다.", "SCIENCE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("geothermal", "/ˌdʒiːoʊˈθɜːrməl/", "지열의", "adjective", "Iceland uses geothermal energy for heating.", "아이슬란드는 난방에 지열 에너지를 사용한다.", "SCIENCE", "HIGH_SCHOOL", 4, None, None, None),
        ("glacier", "/ˈɡleɪsiər/", "빙하", "noun", "Many glaciers are melting due to global warming.", "많은 빙하가 지구 온난화로 녹고 있다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("greenhouse", "/ˈɡriːnhaʊs/", "온실", "noun", "Greenhouse gases trap heat in the atmosphere.", "온실 가스는 대기 중에 열을 가두어 놓는다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("habitat", "/ˈhæbɪtæt/", "서식지", "noun", "Many animals are losing their natural habitats.", "많은 동물들이 자연 서식지를 잃고 있다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("hurricane", "/ˈhʌrɪkeɪn/", "허리케인", "noun", "The hurricane caused widespread destruction.", "허리케인이 광범위한 피해를 야기했다.", "SCIENCE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("hydropower", "/ˈhaɪdrəpaʊər/", "수력 발전", "noun", "Hydropower is a clean source of energy.", "수력 발전은 깨끗한 에너지원이다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("invasive", "/ɪnˈveɪsɪv/", "침습적인; 외래 침입종의", "adjective", "Invasive species can destroy local ecosystems.", "외래 침입종은 지역 생태계를 파괴할 수 있다.", "SCIENCE", "HIGH_SCHOOL", 4, None, None, None),
        ("molecule", "/ˈmɒlɪkjuːl/", "분자", "noun", "Water is made up of two hydrogen and one oxygen molecule.", "물은 두 개의 수소와 한 개의 산소 분자로 구성된다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("organism", "/ˈɔːrɡənɪzəm/", "생물체, 유기체", "noun", "Bacteria are single-celled organisms.", "박테리아는 단세포 생물이다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("ozone", "/ˈoʊzoʊn/", "오존", "noun", "The ozone layer protects Earth from UV rays.", "오존층은 지구를 자외선으로부터 보호한다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("precipitation", "/prɪˌsɪpɪˈteɪʃən/", "강수량; 침전", "noun", "Annual precipitation in this area is about 500mm.", "이 지역의 연간 강수량은 약 500mm이다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("recycle", "/ˌriːˈsaɪkəl/", "재활용하다", "verb", "Please recycle your plastic bottles.", "플라스틱 병을 재활용해 주세요.", "SCIENCE", "ELEMENTARY", 1, None, None, None),
        ("renewable", "/rɪˈnjuːəbəl/", "재생 가능한", "adjective", "Solar and wind are renewable energy sources.", "태양과 바람은 재생 가능한 에너지원이다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("sediment", "/ˈsedɪmənt/", "침전물, 퇴적물", "noun", "Sediment at the bottom of the lake told the history.", "호수 바닥의 퇴적물은 역사를 알려줬다.", "SCIENCE", "HIGH_SCHOOL", 4, None, None, None),
        ("sewage", "/ˈsuːɪdʒ/", "하수, 오수", "noun", "Sewage treatment plants clean waste water.", "하수 처리 시설은 폐수를 정화한다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("solar", "/ˈsoʊlər/", "태양의", "adjective", "Solar energy is becoming more affordable.", "태양 에너지는 더 저렴해지고 있다.", "SCIENCE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("species", "/ˈspiːʃiːz/", "종", "noun", "Over 8 million species live on Earth.", "지구에는 800만 종 이상이 살고 있다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("tsunami", "/tsuːˈnɑːmi/", "쓰나미", "noun", "The tsunami devastated coastal communities.", "쓰나미가 해안 지역사회를 황폐화시켰다.", "SCIENCE", "MIDDLE_SCHOOL", 2, None, None, None),
        ("turbine", "/ˈtɜːrbaɪn/", "터빈", "noun", "Wind turbines convert wind energy to electricity.", "풍력 터빈은 풍력을 전기로 변환한다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),
        ("volcanic", "/vɒlˈkænɪk/", "화산의", "adjective", "The island was formed by volcanic eruptions.", "그 섬은 화산 폭발로 형성되었다.", "SCIENCE", "HIGH_SCHOOL", 3, None, None, None),

        # 사회/교육 어휘
        ("bureaucracy", "/bjʊˈrɒkrəsi/", "관료제, 관료주의", "noun", "Cutting through the bureaucracy takes patience.", "관료주의를 뚫는 데는 인내가 필요하다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("census", "/ˈsensəs/", "인구 조사", "noun", "The census is conducted every ten years.", "인구 조사는 10년마다 실시된다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("citizenship", "/ˈsɪtɪzənʃɪp/", "시민권", "noun", "She applied for citizenship after living here for five years.", "그녀는 5년 거주 후 시민권을 신청했다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("civilization", "/ˌsɪvɪlaɪˈzeɪʃən/", "문명", "noun", "Ancient civilizations built remarkable monuments.", "고대 문명은 놀라운 기념물을 만들었다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("coalition", "/ˌkoʊəˈlɪʃən/", "연합, 연립", "noun", "A coalition of groups opposed the plan.", "단체들의 연합이 계획에 반대했다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("colonialism", "/kəˈloʊniəlɪzəm/", "식민주의", "noun", "Colonialism had lasting effects on many nations.", "식민주의는 많은 국가에 지속적인 영향을 미쳤다.", "GENERAL", "COLLEGE", 4, None, None, None),
        ("commerce", "/ˈkɒmɜːrs/", "상업, 무역", "noun", "International commerce has grown significantly.", "국제 상업이 크게 성장했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("constitution", "/ˌkɒnstɪˈtjuːʃən/", "헌법; 체질", "noun", "The constitution guarantees basic rights.", "헌법은 기본 권리를 보장한다.", "LAW", "HIGH_SCHOOL", 3, None, None, None),
        ("contemplate", "/ˈkɒntəmpleɪt/", "숙고하다, 심사숙고하다", "verb", "She contemplated the decision for a long time.", "그녀는 오랫동안 그 결정을 숙고했다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("corruption", "/kəˈrʌpʃən/", "부패", "noun", "Fighting corruption is key to good governance.", "부패 퇴치는 좋은 거버넌스의 핵심이다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("counseling", "/ˈkaʊnsəlɪŋ/", "상담", "noun", "Students can seek counseling at the school.", "학생들은 학교에서 상담을 구할 수 있다.", "EDUCATION", "HIGH_SCHOOL", 3, None, None, None),
        ("curriculum", "/kəˈrɪkjʊləm/", "교육 과정", "noun", "The curriculum includes science and arts.", "교육 과정에는 과학과 예술이 포함된다.", "EDUCATION", "HIGH_SCHOOL", 3, None, None, None),
        ("debate", "/dɪˈbeɪt/", "토론; 토론하다", "noun", "The debate on immigration is ongoing.", "이민에 관한 토론은 계속되고 있다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("democracy", "/dɪˈmɒkrəsi/", "민주주의", "noun", "Democracy requires active citizen participation.", "민주주의는 적극적인 시민 참여를 필요로 한다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("demographic", "/ˌdemɒˈɡræfɪk/", "인구 통계학적인", "adjective", "Demographic changes affect social services.", "인구 통계학적 변화는 사회 서비스에 영향을 미친다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("diplomacy", "/dɪˈploʊməsi/", "외교", "noun", "Diplomacy is essential for resolving international conflicts.", "외교는 국제 갈등을 해결하는 데 필수적이다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("discrimination", "/dɪˌskrɪmɪˈneɪʃən/", "차별", "noun", "Racial discrimination is illegal in this country.", "이 나라에서는 인종 차별이 불법이다.", "LAW", "HIGH_SCHOOL", 3, None, None, None),
        ("diversity", "/daɪˈvɜːrsɪti/", "다양성", "noun", "Cultural diversity enriches society.", "문화적 다양성은 사회를 풍요롭게 한다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("domestic", "/dəˈmestɪk/", "국내의; 가정의", "adjective", "The company focuses on the domestic market.", "회사는 국내 시장에 집중한다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("emigrate", "/ˈemɪɡreɪt/", "이민 가다", "verb", "They emigrated from Korea to Canada.", "그들은 한국에서 캐나다로 이민했다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("equality", "/ɪˈkwɒlɪti/", "평등", "noun", "The movement fought for gender equality.", "그 운동은 성 평등을 위해 싸웠다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("ethics", "/ˈeθɪks/", "윤리", "noun", "Medical ethics guides doctors' decisions.", "의료 윤리는 의사의 결정을 안내한다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("exploit", "/ˈeksplɔɪt/", "착취하다; 업적", "verb", "It is wrong to exploit vulnerable workers.", "취약한 노동자를 착취하는 것은 잘못된 것이다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("gender", "/ˈdʒendər/", "성별", "noun", "Gender roles vary across cultures.", "성별 역할은 문화에 따라 다르다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("globalization", "/ˌɡloʊbəlaɪˈzeɪʃən/", "세계화", "noun", "Globalization has both benefits and drawbacks.", "세계화에는 장점과 단점이 모두 있다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("heritage", "/ˈherɪtɪdʒ/", "유산, 문화유산", "noun", "The village is proud of its cultural heritage.", "그 마을은 문화 유산을 자랑스럽게 여긴다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("immigrant", "/ˈɪmɪɡrənt/", "이민자", "noun", "Immigrants contributed greatly to the country's growth.", "이민자들은 나라의 성장에 크게 기여했다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("infrastructure", "/ˈɪnfrəstrʌktʃər/", "기반 시설", "noun", "Good infrastructure is essential for economic development.", "좋은 기반 시설은 경제 발전에 필수적이다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("initiative", "/ɪˈnɪʃətɪv/", "주도권, 이니셔티브", "noun", "She took the initiative to start the project.", "그녀는 프로젝트를 시작하기 위해 주도권을 잡았다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("integration", "/ˌɪntɪˈɡreɪʃən/", "통합", "noun", "Social integration helps immigrants adapt.", "사회적 통합은 이민자들이 적응하는 데 도움이 된다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("justice", "/ˈdʒʌstɪs/", "정의, 공정", "noun", "Everyone deserves equal justice under the law.", "모든 사람은 법 아래 동등한 정의를 받을 자격이 있다.", "LAW", "HIGH_SCHOOL", 3, None, None, None),
        ("legislation", "/ˌledʒɪˈsleɪʃən/", "법률, 입법", "noun", "New legislation was passed to protect consumers.", "소비자를 보호하기 위한 새로운 법률이 통과되었다.", "LAW", "HIGH_SCHOOL", 4, None, None, None),
        ("literacy", "/ˈlɪtərəsi/", "문해력", "noun", "Digital literacy is now as important as reading.", "디지털 문해력이 이제 읽기만큼 중요하다.", "EDUCATION", "HIGH_SCHOOL", 3, None, None, None),
        ("media", "/ˈmiːdiə/", "미디어, 매체", "noun", "The media plays a powerful role in shaping opinion.", "미디어는 여론 형성에 강력한 역할을 한다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("minority", "/maɪˈnɒrɪti/", "소수, 소수집단", "noun", "Minority rights must be protected by law.", "소수자의 권리는 법으로 보호되어야 한다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("nationalism", "/ˈnæʃənəlɪzəm/", "민족주의", "noun", "Nationalism can both unite and divide people.", "민족주의는 사람들을 하나로 묶기도 하고 갈라놓기도 한다.", "GENERAL", "COLLEGE", 4, None, None, None),
        ("parliament", "/ˈpɑːrlɪmənt/", "의회", "noun", "The parliament voted on the new budget.", "의회가 새 예산에 투표했다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("pension", "/ˈpenʃən/", "연금", "noun", "She receives a monthly pension from her previous job.", "그녀는 이전 직장에서 월별 연금을 받는다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("philanthropy", "/fɪˈlænθrəpi/", "자선, 박애주의", "noun", "His philanthropy benefited many local charities.", "그의 자선은 많은 지역 자선단체에 혜택을 주었다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("plagiarism", "/ˈpleɪdʒərɪzəm/", "표절", "noun", "Plagiarism is a serious offense in academic work.", "표절은 학문 작업에서 중대한 위반이다.", "EDUCATION", "HIGH_SCHOOL", 3, None, None, None),
        ("prejudice", "/ˈpredʒʊdɪs/", "편견", "noun", "Prejudice prevents people from seeing clearly.", "편견은 사람들이 명확하게 보는 것을 방해한다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("propaganda", "/ˌprɒpəˈɡændə/", "선전", "noun", "Government propaganda controlled public opinion.", "정부 선전이 여론을 통제했다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("protest", "/ˈproʊtest/", "항의; 항의하다", "noun", "Thousands attended the protest against the law.", "수천 명이 그 법에 반대하는 항의에 참가했다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("reformation", "/ˌrefəˈmeɪʃən/", "개혁, 혁신", "noun", "Educational reformation improved student outcomes.", "교육 개혁은 학생 성과를 개선했다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("refugee", "/ˌrefjʊˈdʒiː/", "난민", "noun", "The country accepted thousands of refugees.", "그 나라는 수천 명의 난민을 받아들였다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("regulation", "/ˌreɡjʊˈleɪʃən/", "규제, 규정", "noun", "Stricter regulations on emissions were introduced.", "배출에 관한 더 엄격한 규제가 도입되었다.", "LAW", "HIGH_SCHOOL", 3, None, None, None),
        ("segregation", "/ˌseɡrɪˈɡeɪʃən/", "분리, 격리", "noun", "Racial segregation was abolished in the 1960s.", "인종 분리는 1960년대에 폐지되었다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("slavery", "/ˈsleɪvəri/", "노예제", "noun", "Slavery was a dark chapter in human history.", "노예제는 인류 역사의 어두운 장이었다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("sovereignty", "/ˈsɒvrənti/", "주권", "noun", "Every nation has the right to sovereignty.", "모든 나라는 주권을 가질 권리가 있다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("stereotype", "/ˈsteriətaɪp/", "고정관념", "noun", "It's important to challenge harmful stereotypes.", "해로운 고정관념에 도전하는 것이 중요하다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("subsidy", "/ˈsʌbsɪdi/", "보조금", "noun", "The government provides subsidies to farmers.", "정부는 농부들에게 보조금을 제공한다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("suffrage", "/ˈsʌfrɪdʒ/", "참정권, 투표권", "noun", "Women's suffrage was achieved after decades of struggle.", "여성 참정권은 수십 년간의 투쟁 끝에 쟁취되었다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("taxation", "/tækˈseɪʃən/", "과세", "noun", "Progressive taxation reduces income inequality.", "누진 과세는 소득 불평등을 줄인다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("tolerance", "/ˈtɒlərəns/", "관용, 인내심", "noun", "A tolerant society accepts different lifestyles.", "관용적인 사회는 다양한 생활 방식을 받아들인다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),
        ("tradition", "/trəˈdɪʃən/", "전통", "noun", "Respecting tradition is important in this culture.", "이 문화에서는 전통을 존중하는 것이 중요하다.", "GENERAL", "MIDDLE_SCHOOL", 2, None, None, None),
        ("transparency", "/trænsˈpærənsi/", "투명성", "noun", "Transparency in government builds public trust.", "정부의 투명성은 대중의 신뢰를 쌓는다.", "GENERAL", "HIGH_SCHOOL", 4, None, None, None),
        ("verdict", "/ˈvɜːrdɪkt/", "평결, 판결", "noun", "The jury delivered a not-guilty verdict.", "배심원은 무죄 평결을 내렸다.", "LAW", "HIGH_SCHOOL", 3, None, None, None),
        ("welfare", "/ˈwelfeər/", "복지", "noun", "Child welfare is the government's top priority.", "아동 복지는 정부의 최우선 과제이다.", "GENERAL", "HIGH_SCHOOL", 3, None, None, None),

        # 비즈니스 추가 어휘
        ("asset", "/ˈæset/", "자산", "noun", "Buildings and equipment are company assets.", "건물과 장비는 회사 자산이다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("audit", "/ˈɔːdɪt/", "감사; 감사하다", "noun", "The company hired an external firm for the annual audit.", "회사는 연례 감사를 위해 외부 기관을 고용했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("benchmark", "/ˈbentʃmɑːrk/", "기준, 벤치마크", "noun", "Industry benchmarks help measure performance.", "업계 벤치마크는 성과를 측정하는 데 도움이 된다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("bonus", "/ˈboʊnəs/", "보너스", "noun", "Employees received a year-end bonus.", "직원들은 연말 보너스를 받았다.", "BUSINESS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("brand", "/brænd/", "브랜드", "noun", "Building a strong brand takes years of work.", "강력한 브랜드를 구축하는 데는 수년간의 노력이 필요하다.", "BUSINESS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("cashflow", "/ˈkæʃfloʊ/", "현금 흐름", "noun", "Managing cash flow is critical for small businesses.", "현금 흐름 관리는 중소기업에게 매우 중요하다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("competitive", "/kəmˈpetɪtɪv/", "경쟁적인", "adjective", "The smartphone market is highly competitive.", "스마트폰 시장은 매우 경쟁이 치열하다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("compliance", "/kəmˈplaɪəns/", "준수, 법규 준수", "noun", "All employees must comply with the new compliance rules.", "모든 직원은 새로운 준수 규칙을 따라야 한다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("consultant", "/kənˈsʌltənt/", "컨설턴트", "noun", "They hired a consultant to improve operations.", "그들은 운영을 개선하기 위해 컨설턴트를 고용했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("corporate", "/ˈkɔːrpərət/", "기업의", "adjective", "Corporate governance ensures accountability.", "기업 지배 구조는 책임을 보장한다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("debt", "/det/", "부채, 빚", "noun", "The company carries a significant amount of debt.", "회사는 상당한 부채를 안고 있다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("depreciation", "/dɪˌpriːʃiˈeɪʃən/", "감가상각", "noun", "Depreciation reduces the value of assets over time.", "감가상각은 시간이 지남에 따라 자산 가치를 감소시킨다.", "BUSINESS", "COLLEGE", 5, None, None, None),
        ("dividend", "/ˈdɪvɪdend/", "배당금", "noun", "Shareholders receive annual dividends.", "주주들은 연간 배당금을 받는다.", "BUSINESS", "COLLEGE", 4, None, None, None),
        ("entrepreneur", "/ˌɒntrəprəˈnɜːr/", "기업가", "noun", "Young entrepreneurs are driving economic growth.", "젊은 기업가들이 경제 성장을 이끌고 있다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("equity", "/ˈekwɪti/", "형평; 자기자본", "noun", "The startup raised equity funding from investors.", "스타트업은 투자자로부터 주식 자금을 모았다.", "BUSINESS", "COLLEGE", 4, None, None, None),
        ("feasibility", "/ˌfiːzəˈbɪlɪti/", "실현 가능성", "noun", "A feasibility study was conducted before the project.", "프로젝트 전에 타당성 조사가 실시되었다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("fiscal", "/ˈfɪskəl/", "재정의, 회계의", "adjective", "The fiscal year ends in March.", "회계 연도는 3월에 끝난다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("forecast", "/ˈfɔːrkæst/", "예측, 예보; 예측하다", "noun", "The sales forecast for next quarter is positive.", "다음 분기 매출 예측은 긍정적이다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("gross", "/ɡroʊs/", "총; 총액", "adjective", "Gross revenue exceeded expectations.", "총 수익이 기대를 초과했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("incentivize", "/ɪnˈsentɪvaɪz/", "동기를 부여하다", "verb", "The company incentivized employees with bonuses.", "회사는 보너스로 직원들에게 동기를 부여했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("inventory", "/ˈɪnvəntɔːri/", "재고", "noun", "The store needs to restock its inventory.", "가게는 재고를 다시 채워야 한다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("invoice", "/ˈɪnvɔɪs/", "청구서, 인보이스", "noun", "Please send the invoice by email.", "이메일로 청구서를 보내주세요.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("liability", "/ˌlaɪəˈbɪlɪti/", "책임; 부채", "noun", "The company's liabilities exceeded its assets.", "회사의 부채가 자산을 초과했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("logistics", "/ləˈdʒɪstɪks/", "물류", "noun", "Efficient logistics is key to customer satisfaction.", "효율적인 물류는 고객 만족의 핵심이다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("margin", "/ˈmɑːrdʒɪn/", "마진, 이익; 여백", "noun", "The profit margin was lower than expected.", "이익 마진은 예상보다 낮았다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("merger", "/ˈmɜːrdʒər/", "합병", "noun", "The merger created the largest company in the industry.", "합병으로 업계 최대 기업이 탄생했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("milestone", "/ˈmaɪlstoʊn/", "이정표, 중요한 단계", "noun", "Reaching one million customers was a major milestone.", "백만 명의 고객 달성은 중요한 이정표였다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("momentum", "/moʊˈmentəm/", "추진력, 모멘텀", "noun", "The startup gained momentum after the launch.", "스타트업은 출시 후 추진력을 얻었다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("overhead", "/ˈoʊvərhed/", "간접비, 경비", "noun", "Reducing overhead costs improved profitability.", "간접비 절감은 수익성을 개선했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("portfolio", "/pɔːrtˈfoʊlioʊ/", "포트폴리오", "noun", "She has a diverse investment portfolio.", "그녀는 다양한 투자 포트폴리오를 가지고 있다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("procurement", "/prəˈkjʊərmənt/", "조달", "noun", "The procurement department handles all purchasing.", "조달 부서는 모든 구매를 처리한다.", "BUSINESS", "COLLEGE", 4, None, None, None),
        ("recession", "/rɪˈseʃən/", "경기 침체", "noun", "The country experienced a deep recession.", "그 나라는 심각한 경기 침체를 경험했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("restructure", "/ˌriːˈstrʌktʃər/", "구조 조정하다", "verb", "The company had to restructure to survive.", "회사는 살아남기 위해 구조 조정을 해야 했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("shareholder", "/ˈʃeərhoʊldər/", "주주", "noun", "Shareholders voted to approve the acquisition.", "주주들은 인수 승인에 투표했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("startup", "/ˈstɑːrtʌp/", "스타트업", "noun", "The startup secured funding from venture capitalists.", "스타트업은 벤처 캐피털리스트로부터 자금을 확보했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("surplus", "/ˈsɜːrpləs/", "잉여, 흑자", "noun", "The company had a budget surplus this year.", "회사는 올해 예산 흑자를 기록했다.", "BUSINESS", "HIGH_SCHOOL", 4, None, None, None),
        ("transaction", "/trænˈzækʃən/", "거래", "noun", "All transactions are recorded in the database.", "모든 거래는 데이터베이스에 기록된다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("venture", "/ˈventʃər/", "모험적 사업; 감히 하다", "noun", "He started a new venture in renewable energy.", "그는 재생 에너지 분야에서 새로운 사업을 시작했다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),
        ("workforce", "/ˈwɜːrkfɔːrs/", "인력, 노동력", "noun", "The company plans to expand its workforce.", "회사는 인력을 확장할 계획이다.", "BUSINESS", "HIGH_SCHOOL", 3, None, None, None),

        # 예술/문화 추가 어휘
        ("aesthetic", "/iːsˈθetɪk/", "미적인; 미학", "adjective", "The building has great aesthetic appeal.", "그 건물은 훌륭한 미적 매력을 가지고 있다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
        ("allegory", "/ˈæləɡɔːri/", "우화, 알레고리", "noun", "The novel is an allegory about greed.", "그 소설은 탐욕에 관한 우화이다.", "ARTS", "COLLEGE", 5, None, None, None),
        ("archive", "/ˈɑːrkaɪv/", "기록 보관소; 보관하다", "noun", "The museum has an extensive digital archive.", "박물관은 광범위한 디지털 기록 보관소를 가지고 있다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("choreography", "/ˌkɒriˈɒɡrəfi/", "안무", "noun", "The choreography of the ballet was stunning.", "발레의 안무는 놀라웠다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
        ("composition", "/ˌkɒmpəˈzɪʃən/", "구성; 작곡; 구도", "noun", "The composer's latest composition premiered last night.", "작곡가의 최신 작품이 어젯밤에 초연되었다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("contemporary", "/kənˈtempərəri/", "현대의; 동시대의", "adjective", "Contemporary art challenges traditional notions of beauty.", "현대 예술은 아름다움에 대한 전통적인 개념에 도전한다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("critique", "/krɪˈtiːk/", "비평; 비평하다", "noun", "The film received excellent critiques.", "그 영화는 훌륭한 비평을 받았다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
        ("depict", "/dɪˈpɪkt/", "묘사하다, 그리다", "verb", "The painting depicts a peaceful rural scene.", "그 그림은 평화로운 시골 풍경을 묘사한다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("improvise", "/ˈɪmprəvaɪz/", "즉흥적으로 하다", "verb", "Jazz musicians often improvise during performances.", "재즈 음악가들은 공연 중에 종종 즉흥 연주를 한다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
        ("inspiration", "/ˌɪnspɪˈreɪʃən/", "영감", "noun", "The artist drew inspiration from everyday life.", "그 예술가는 일상생활에서 영감을 받았다.", "ARTS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("interpretation", "/ɪnˌtɜːrprɪˈteɪʃən/", "해석, 연주", "noun", "The director's interpretation of the play was unique.", "감독의 연극 해석은 독특했다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
        ("manuscript", "/ˈmænjʊskrɪpt/", "원고, 필사본", "noun", "The author submitted the manuscript to the publisher.", "작가는 출판사에 원고를 제출했다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("masterpiece", "/ˈmɑːstərpiːs/", "걸작", "noun", "The Mona Lisa is considered a masterpiece.", "모나리자는 걸작으로 여겨진다.", "ARTS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("medium", "/ˈmiːdiəm/", "매체; 중간의", "noun", "Oil paint is a traditional artistic medium.", "유화 물감은 전통적인 예술 매체이다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("melody", "/ˈmelɒdi/", "선율, 멜로디", "noun", "The melody was simple but beautiful.", "선율은 단순하지만 아름다웠다.", "ARTS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("motif", "/moʊˈtiːf/", "모티프, 주제", "noun", "The recurring motif of water runs through the novel.", "물의 반복적인 모티프가 소설 전반에 흐른다.", "ARTS", "COLLEGE", 4, None, None, None),
        ("narrative", "/ˈnærətɪv/", "서술, 이야기", "noun", "The narrative of the film was complex.", "영화의 서술은 복잡했다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
        ("orchestra", "/ˈɔːrkɪstrə/", "오케스트라", "noun", "The symphony orchestra performed Beethoven.", "심포니 오케스트라는 베토벤을 연주했다.", "ARTS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("portrait", "/ˈpɔːrtrɪt/", "초상화; 묘사", "noun", "The museum displays royal portraits from the 18th century.", "박물관은 18세기 왕실 초상화를 전시한다.", "ARTS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("prose", "/proʊz/", "산문", "noun", "Her prose style is clear and elegant.", "그녀의 산문 스타일은 명확하고 우아하다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
        ("rehearsal", "/rɪˈhɜːrsəl/", "리허설, 연습", "noun", "The actors went through several rehearsals before opening night.", "배우들은 개막 전날 밤 전에 여러 번 리허설을 했다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("rhythm", "/ˈrɪðəm/", "리듬, 박자", "noun", "The rhythm of the music made everyone want to dance.", "음악의 리듬은 모든 사람이 춤추고 싶게 만들었다.", "ARTS", "MIDDLE_SCHOOL", 2, None, None, None),
        ("sculpture", "/ˈskʌlptʃər/", "조각품", "noun", "The sculpture was carved from a single block of marble.", "조각품은 대리석 한 덩어리로 조각되었다.", "ARTS", "HIGH_SCHOOL", 3, None, None, None),
        ("theatrical", "/θiˈætrɪkəl/", "연극적인", "adjective", "The theatrical performance received standing ovations.", "연극적인 공연은 기립 박수를 받았다.", "ARTS", "HIGH_SCHOOL", 4, None, None, None),
    ]

    added = add_words(conn, words_data, existing)
    conn.close()

    conn2 = get_connection()
    c = conn2.cursor()
    c.execute("SELECT COUNT(*) FROM words")
    total = c.fetchone()[0]
    conn2.close()

    print()
    print("=" * 50)
    print("배치 8: 일상/기술/의학/환경/사회/비즈니스/예술 완료")
    print("=" * 50)
    print(f"배치 8: {added}개 단어 추가")
    print(f"총 단어 수: {total}")

if __name__ == "__main__":
    main()
