#!/usr/bin/env python3
"""배치 2: 중고등 학술 어휘 (Academic Word List 기반) 700개."""
from batch_utils import get_connection, get_existing_words, add_words, print_stats

def get_words():
    return [
        # ===== AWL (Academic Word List) - 학술 필수 어휘 =====
        ("analyze", "/ˈænəlaɪz/", "분석하다", "verb", "Analyze the data carefully.", "데이터를 신중하게 분석하세요.", "EDUCATION", "HIGH_SCHOOL", 3, "examine, study", None, None),
        ("approach", "/əˈproʊtʃ/", "접근법, 방법", "noun", "Try a different approach.", "다른 접근법을 시도해 보세요.", "GENERAL", "HIGH_SCHOOL", 3, "method, strategy", None, None),
        ("assess", "/əˈsɛs/", "평가하다", "verb", "Assess the situation first.", "먼저 상황을 평가하세요.", "EDUCATION", "HIGH_SCHOOL", 3, "evaluate, judge", None, None),
        ("assume", "/əˈsuːm/", "가정하다", "verb", "Don't assume anything.", "어떤 것도 가정하지 마세요.", "GENERAL", "HIGH_SCHOOL", 3, "suppose, presume", None, None),
        ("benefit", "/ˈbɛnɪfɪt/", "혜택, 이점", "noun", "Exercise has many benefits.", "운동은 많은 이점이 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "advantage, gain", "disadvantage, harm", None),
        ("concept", "/ˈkɑːnsɛpt/", "개념", "noun", "Explain the concept clearly.", "개념을 명확히 설명하세요.", "EDUCATION", "HIGH_SCHOOL", 3, "idea, notion", None, None),
        ("context", "/ˈkɑːntɛkst/", "맥락, 상황", "noun", "Understand the context.", "맥락을 이해하세요.", "GENERAL", "HIGH_SCHOOL", 3, "background, setting", None, None),
        ("contract", "/ˈkɑːntrækt/", "계약(서)", "noun", "Sign the contract.", "계약서에 서명하세요.", "LAW", "HIGH_SCHOOL", 3, "agreement, deal", None, None),
        ("contribute", "/kənˈtrɪbjuːt/", "기여하다, 공헌하다", "verb", "Contribute to the community.", "지역 사회에 기여하세요.", "GENERAL", "HIGH_SCHOOL", 3, "give, donate", "take", None),
        ("define", "/dɪˈfaɪn/", "정의하다", "verb", "Define your goals clearly.", "목표를 명확히 정의하세요.", "GENERAL", "HIGH_SCHOOL", 3, "explain, clarify", None, None),
        ("demonstrate", "/ˈdɛmənstreɪt/", "보여주다, 증명하다", "verb", "Demonstrate how it works.", "작동 방식을 보여주세요.", "GENERAL", "HIGH_SCHOOL", 3, "show, prove", None, None),
        ("distribute", "/dɪˈstrɪbjuːt/", "배포하다, 배급하다", "verb", "Distribute the handouts.", "유인물을 배포하세요.", "GENERAL", "HIGH_SCHOOL", 3, "spread, allocate", "collect", None),
        ("estimate", "/ˈɛstɪmɪt/", "추정하다, 추산", "verb", "Estimate the total cost.", "총 비용을 추산하세요.", "GENERAL", "HIGH_SCHOOL", 3, "calculate, guess", None, None),
        ("evaluate", "/ɪˈvæljueɪt/", "평가하다", "verb", "Evaluate the results.", "결과를 평가하세요.", "EDUCATION", "HIGH_SCHOOL", 3, "assess, judge", None, None),
        ("function", "/ˈfʌŋkʃən/", "기능, 역할", "noun", "What is the function of this button?", "이 버튼의 기능이 무엇인가요?", "GENERAL", "HIGH_SCHOOL", 3, "role, purpose", None, None),
        ("generate", "/ˈdʒɛnəreɪt/", "생성하다, 발생시키다", "verb", "Generate new ideas.", "새로운 아이디어를 생성하세요.", "GENERAL", "HIGH_SCHOOL", 3, "create, produce", "destroy", None),
        ("ignore", "/ɪɡˈnɔːr/", "무시하다", "verb", "Don't ignore the warning.", "경고를 무시하지 마세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "disregard, overlook", "pay attention to", None),
        ("impact", "/ˈɪmpækt/", "영향, 충격", "noun", "The impact was enormous.", "영향이 엄청났습니다.", "GENERAL", "HIGH_SCHOOL", 3, "effect, influence", None, None),
        ("implement", "/ˈɪmplɪmɛnt/", "실행하다, 시행하다", "verb", "Implement the new policy.", "새 정책을 시행하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "carry out, execute", "cancel, abandon", None),
        ("interpret", "/ɪnˈtɜːrprɪt/", "해석하다", "verb", "Interpret the results.", "결과를 해석하세요.", "GENERAL", "HIGH_SCHOOL", 3, "explain, understand", None, None),
        ("invest", "/ɪnˈvɛst/", "투자하다", "verb", "Invest in your education.", "교육에 투자하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "spend, put money into", "withdraw", None),
        ("justify", "/ˈdʒʌstɪfaɪ/", "정당화하다, 옳다고 주장하다", "verb", "Can you justify your decision?", "결정을 정당화할 수 있나요?", "GENERAL", "HIGH_SCHOOL", 3, "defend, support", None, None),
        ("method", "/ˈmɛθəd/", "방법", "noun", "Use the correct method.", "올바른 방법을 사용하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "way, approach", None, None),
        ("objective", "/əbˈdʒɛktɪv/", "목표, 객관적인", "noun", "Our main objective is success.", "우리의 주요 목표는 성공입니다.", "GENERAL", "HIGH_SCHOOL", 3, "goal, aim", "subjective", None),
        ("occur", "/əˈkɜːr/", "일어나다, 발생하다", "verb", "When did it occur?", "언제 발생했나요?", "GENERAL", "MIDDLE_SCHOOL", 2, "happen, take place", None, None),
        ("policy", "/ˈpɑːlɪsi/", "정책", "noun", "The new policy is effective.", "새 정책이 효과적입니다.", "LAW", "HIGH_SCHOOL", 3, "rule, regulation", None, None),
        ("principle", "/ˈprɪnsɪpəl/", "원칙", "noun", "Follow ethical principles.", "윤리적 원칙을 따르세요.", "GENERAL", "HIGH_SCHOOL", 3, "rule, standard", None, None),
        ("promote", "/prəˈmoʊt/", "홍보하다, 촉진하다", "verb", "Promote healthy habits.", "건강한 습관을 장려하세요.", "GENERAL", "HIGH_SCHOOL", 3, "advance, support", "demote, hinder", None),
        ("respond", "/rɪˈspɑːnd/", "반응하다, 대답하다", "verb", "Respond to the question.", "질문에 답하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "answer, reply", "ignore", None),
        ("restrict", "/rɪˈstrɪkt/", "제한하다", "verb", "Restrict access to the file.", "파일 접근을 제한하세요.", "GENERAL", "HIGH_SCHOOL", 3, "limit, constrain", "allow, permit", None),
        ("significant", "/sɪɡˈnɪfɪkənt/", "중요한, 상당한", "adjective", "This is a significant change.", "이것은 중요한 변화입니다.", "GENERAL", "HIGH_SCHOOL", 3, "important, major", "insignificant, minor", None),
        ("source", "/sɔːrs/", "출처, 원천", "noun", "What is the source of this information?", "이 정보의 출처가 무엇인가요?", "GENERAL", "MIDDLE_SCHOOL", 2, "origin, reference", None, None),
        ("specific", "/spɪˈsɪfɪk/", "구체적인, 특정한", "adjective", "Be specific about your needs.", "필요한 것을 구체적으로 말씀해 주세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "particular, precise", "vague, general", None),
        ("structure", "/ˈstrʌktʃər/", "구조, 건축물", "noun", "The structure of the essay is clear.", "에세이의 구조가 명확합니다.", "GENERAL", "HIGH_SCHOOL", 3, "framework, organization", None, None),
        ("theory", "/ˈθɪəri/", "이론", "noun", "Darwin's theory of evolution.", "다윈의 진화론.", "SCIENCE", "HIGH_SCHOOL", 3, "hypothesis, concept", None, None),
        ("vary", "/ˈvɛri/", "다양하다, 변하다", "verb", "Prices vary by location.", "가격은 위치에 따라 다릅니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "differ, change", "stay the same", None),
        ("constitute", "/ˈkɑːnstɪtuːt/", "구성하다, ~에 해당하다", "verb", "This constitutes a breach of contract.", "이것은 계약 위반에 해당합니다.", "LAW", "COLLEGE", 4, "make up, form", None, None),
        ("debate", "/dɪˈbeɪt/", "토론, 논쟁", "noun", "There is much debate on this topic.", "이 주제에 대해 많은 토론이 있습니다.", "GENERAL", "HIGH_SCHOOL", 3, "argument, discussion", None, None),
        ("consequence", "/ˈkɑːnsɪkwəns/", "결과, 결론", "noun", "Think about the consequences.", "결과를 생각해 보세요.", "GENERAL", "HIGH_SCHOOL", 3, "outcome, result", "cause", None),
        ("enforce", "/ɛnˈfɔːrs/", "강요하다, 집행하다", "verb", "Enforce the rules strictly.", "규칙을 엄격히 집행하세요.", "LAW", "HIGH_SCHOOL", 3, "impose, implement", "ignore, waive", None),
        ("export", "/ˈɛkspɔːrt/", "수출하다, 수출", "verb", "Korea exports many products.", "한국은 많은 제품을 수출합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "ship, send", "import", None),
        ("factor", "/ˈfæktər/", "요인, 요소", "noun", "Consider all factors.", "모든 요인을 고려하세요.", "GENERAL", "HIGH_SCHOOL", 3, "element, aspect", None, None),
        ("feature", "/ˈfiːtʃər/", "특징, 특성", "noun", "This phone has many features.", "이 폰은 많은 특징이 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "characteristic, attribute", None, None),
        ("foundation", "/faʊnˈdeɪʃən/", "기초, 재단", "noun", "Build a strong foundation.", "튼튼한 기초를 쌓으세요.", "GENERAL", "HIGH_SCHOOL", 3, "base, basis", None, None),
        ("image", "/ˈɪmɪdʒ/", "이미지, 인상", "noun", "The company's image is important.", "회사의 이미지가 중요합니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "impression, picture", None, None),
        ("individual", "/ˌɪndɪˈvɪdʒuəl/", "개인", "noun", "Each individual is unique.", "각 개인은 고유합니다.", "GENERAL", "HIGH_SCHOOL", 3, "person, single", "group", None),
        ("instance", "/ˈɪnstəns/", "예, 경우", "noun", "For instance, take this case.", "예를 들어, 이 경우를 보세요.", "GENERAL", "HIGH_SCHOOL", 3, "example, case", None, None),
        ("interact", "/ˌɪntərˈækt/", "상호작용하다", "verb", "Interact with your classmates.", "반 친구들과 상호작용하세요.", "GENERAL", "HIGH_SCHOOL", 3, "communicate, engage", None, None),
        ("legal", "/ˈliːɡəl/", "법적인, 합법적인", "adjective", "Is this legal?", "이것이 합법적인가요?", "LAW", "HIGH_SCHOOL", 3, "lawful, legitimate", "illegal, unlawful", None),
        ("link", "/lɪŋk/", "연결, 링크", "noun", "There is a link between diet and health.", "식단과 건강 사이에 연관성이 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "connection, bond", None, None),
        ("network", "/ˈnɛtwɜːrk/", "네트워크, 인맥", "noun", "Build your professional network.", "전문 인맥을 쌓으세요.", "BUSINESS", "HIGH_SCHOOL", 3, "connection, system", None, None),
        ("output", "/ˈaʊtpʊt/", "출력, 생산량", "noun", "Increase output.", "생산량을 늘리세요.", "BUSINESS", "HIGH_SCHOOL", 3, "production, result", "input", None),
        ("participate", "/pɑːrˈtɪsɪpeɪt/", "참여하다", "verb", "Participate in the discussion.", "토론에 참여하세요.", "GENERAL", "HIGH_SCHOOL", 3, "join, take part", "withdraw", None),
        ("percent", "/pərˈsɛnt/", "퍼센트", "noun", "50 percent of students passed.", "학생의 50%가 통과했습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "percentage, ratio", None, None),
        ("period", "/ˈpɪriəd/", "기간, 시대", "noun", "The trial period is 30 days.", "시험 기간은 30일입니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "time, era", None, None),
        ("phase", "/feɪz/", "단계, 국면", "noun", "We are in the final phase.", "우리는 마지막 단계에 있습니다.", "GENERAL", "HIGH_SCHOOL", 3, "stage, step", None, None),
        ("potential", "/pəˈtɛnʃəl/", "잠재력, 잠재적인", "adjective", "She has great potential.", "그녀는 큰 잠재력이 있습니다.", "GENERAL", "HIGH_SCHOOL", 3, "possible, promising", "actual", None),
        ("preliminary", "/prɪˈlɪmɪnɛri/", "예비적인, 초보적인", "adjective", "Preliminary results look good.", "예비 결과가 좋아 보입니다.", "GENERAL", "COLLEGE", 4, "initial, preparatory", "final", None),
        ("primary", "/ˈpraɪmɛri/", "주요한, 기본적인", "adjective", "What is the primary goal?", "주요 목표가 무엇인가요?", "GENERAL", "HIGH_SCHOOL", 3, "main, chief", "secondary", None),
        ("professional", "/prəˈfɛʃənəl/", "전문적인, 전문가", "adjective", "She is very professional.", "그녀는 매우 전문적입니다.", "BUSINESS", "HIGH_SCHOOL", 3, "skilled, expert", "amateur", None),
        ("publish", "/ˈpʌblɪʃ/", "출판하다, 게시하다", "verb", "Publish your research.", "연구를 출판하세요.", "EDUCATION", "HIGH_SCHOOL", 3, "release, issue", None, None),
        ("range", "/reɪndʒ/", "범위, 다양하다", "noun", "We offer a wide range of products.", "다양한 제품을 제공합니다.", "GENERAL", "HIGH_SCHOOL", 3, "span, variety", None, None),
        ("region", "/ˈriːdʒən/", "지역, 지방", "noun", "This region has a warm climate.", "이 지역은 따뜻한 기후입니다.", "GENERAL", "HIGH_SCHOOL", 3, "area, zone", None, None),
        ("regulate", "/ˈrɛɡjuleɪt/", "규제하다", "verb", "The government regulates industries.", "정부가 산업을 규제합니다.", "LAW", "HIGH_SCHOOL", 3, "control, manage", "deregulate", None),
        ("rely", "/rɪˈlaɪ/", "의존하다, 믿다", "verb", "Rely on your own judgment.", "자신의 판단을 믿으세요.", "GENERAL", "HIGH_SCHOOL", 3, "depend on, trust", None, None),
        ("retain", "/rɪˈteɪn/", "보유하다, 유지하다", "verb", "Retain your receipts.", "영수증을 보관하세요.", "GENERAL", "HIGH_SCHOOL", 3, "keep, hold", "release, lose", None),
        ("sector", "/ˈsɛktər/", "부문, 영역", "noun", "The public sector needs reform.", "공공 부문의 개혁이 필요합니다.", "BUSINESS", "COLLEGE", 4, "area, field", None, None),
        ("similar", "/ˈsɪmɪlər/", "비슷한", "adjective", "These two are very similar.", "이 둘은 매우 비슷합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "alike, comparable", "different, unlike", None),
        ("strategy", "/ˈstrætɪdʒi/", "전략", "noun", "We need a clear strategy.", "명확한 전략이 필요합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "plan, approach", None, None),
        ("survey", "/ˈsɜːrveɪ/", "조사, 설문", "noun", "Conduct a survey.", "설문 조사를 실시하세요.", "GENERAL", "HIGH_SCHOOL", 3, "poll, study", None, None),
        ("target", "/ˈtɑːrɡɪt/", "목표, 대상", "noun", "Set a realistic target.", "현실적인 목표를 설정하세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "goal, aim", None, None),
        ("topic", "/ˈtɑːpɪk/", "주제, 화제", "noun", "Choose an interesting topic.", "흥미로운 주제를 선택하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "subject, theme", None, None),
        ("transfer", "/ˈtrænsfɜːr/", "이동하다, 전송하다", "verb", "Transfer the files to USB.", "파일을 USB로 전송하세요.", "GENERAL", "HIGH_SCHOOL", 3, "move, send", None, None),
        ("trend", "/trɛnd/", "경향, 추세", "noun", "What is the current trend?", "현재 추세가 무엇인가요?", "GENERAL", "HIGH_SCHOOL", 3, "tendency, direction", None, None),
        ("unique", "/juːˈniːk/", "독특한", "adjective", "Everyone is unique.", "모든 사람은 독특합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "special, one-of-a-kind", "common, ordinary", None),
        ("valid", "/ˈvælɪd/", "유효한, 타당한", "adjective", "This ticket is valid for 3 days.", "이 티켓은 3일 동안 유효합니다.", "GENERAL", "HIGH_SCHOOL", 3, "legitimate, sound", "invalid, expired", None),
        ("visible", "/ˈvɪzɪbəl/", "보이는, 눈에 띄는", "adjective", "The logo should be visible.", "로고가 잘 보여야 합니다.", "GENERAL", "HIGH_SCHOOL", 3, "clear, apparent", "invisible, hidden", None),
        ("volume", "/ˈvɑːljuːm/", "볼륨, 양, 권", "noun", "Turn down the volume.", "볼륨을 낮추세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "amount, quantity", None, None),
        ("welfare", "/ˈwɛlfɛr/", "복지", "noun", "Child welfare is important.", "아동 복지가 중요합니다.", "LAW", "HIGH_SCHOOL", 3, "well-being, prosperity", None, None),

        # ===== 중학교 수준 추가 어휘 =====
        ("accident", "/ˈæksɪdənt/", "사고", "noun", "A car accident happened.", "자동차 사고가 났습니다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "crash, mishap", None, None),
        ("adventure", "/ədˈvɛntʃər/", "모험", "noun", "Life is an adventure.", "인생은 모험입니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "journey, expedition", None, None),
        ("agree", "/əˈɡriː/", "동의하다", "verb", "I agree with you.", "당신에게 동의합니다.", "GENERAL", "ELEMENTARY", 1, "consent, approve", "disagree, oppose", None),
        ("alarm", "/əˈlɑːrm/", "알람, 경보", "noun", "Set an alarm for 7 AM.", "오전 7시 알람을 설정하세요.", "DAILY_LIFE", "ELEMENTARY", 1, "alert, warning", None, None),
        ("ancient", "/ˈeɪnʃənt/", "고대의", "adjective", "Ancient Egypt was fascinating.", "고대 이집트는 매혹적이었습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "old, historical", "modern, contemporary", None),
        ("announce", "/əˈnaʊns/", "발표하다, 알리다", "verb", "Announce the results.", "결과를 발표하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "declare, proclaim", None, None),
        ("apologize", "/əˈpɑːlədʒaɪz/", "사과하다", "verb", "I apologize for the mistake.", "실수에 대해 사과합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "say sorry", None, None),
        ("appointment", "/əˈpɔɪntmənt/", "약속, 예약", "noun", "I have a doctor's appointment.", "병원 예약이 있습니다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "meeting, booking", None, None),
        ("appropriate", "/əˈproʊpriɪt/", "적절한", "adjective", "Is this appropriate?", "이것이 적절한가요?", "GENERAL", "HIGH_SCHOOL", 3, "suitable, proper", "inappropriate, unsuitable", None),
        ("attitude", "/ˈætɪtuːd/", "태도", "noun", "Have a positive attitude.", "긍정적인 태도를 가지세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "outlook, perspective", None, None),
        ("behavior", "/bɪˈheɪvjər/", "행동, 행위", "noun", "Good behavior is rewarded.", "좋은 행동은 보상받습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "conduct, manner", None, None),
        ("boring", "/ˈbɔːrɪŋ/", "지루한", "adjective", "The lecture was boring.", "강의가 지루했습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "dull, tedious", "interesting, exciting", None),
        ("calm", "/kɑːm/", "차분한, 침착한", "adjective", "Stay calm in a crisis.", "위기 상황에서 차분하게 있으세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "peaceful, relaxed", "nervous, anxious", None),
        ("cartoon", "/kɑːrˈtuːn/", "만화", "noun", "He enjoys watching cartoons.", "그는 만화 보기를 즐깁니다.", "ARTS", "ELEMENTARY", 1, "animation, comic", None, None),
        ("ceiling", "/ˈsiːlɪŋ/", "천장", "noun", "The ceiling is too high.", "천장이 너무 높습니다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "roof", "floor", None),
        ("celebrate", "/ˈsɛlɪbreɪt/", "축하하다", "verb", "Let's celebrate your birthday.", "생일을 축하합시다.", "GENERAL", "ELEMENTARY", 1, "commemorate, honor", None, None),
        ("challenge", "/ˈtʃælɪndʒ/", "도전, 어려움", "noun", "Face the challenge.", "도전에 맞서세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "difficulty, obstacle", None, None),
        ("charge", "/tʃɑːrdʒ/", "요금, 충전하다", "noun", "Is there a charge for parking?", "주차 요금이 있나요?", "BUSINESS", "MIDDLE_SCHOOL", 2, "fee, cost", None, None),
        ("chemical", "/ˈkɛmɪkəl/", "화학의, 화학물질", "adjective", "Avoid chemical exposure.", "화학물질 노출을 피하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "synthetic", "natural", None),
        ("citizen", "/ˈsɪtɪzən/", "시민", "noun", "Every citizen has rights.", "모든 시민에게는 권리가 있습니다.", "LAW", "MIDDLE_SCHOOL", 2, "resident, national", None, None),
        ("claim", "/kleɪm/", "주장, 청구", "noun", "File an insurance claim.", "보험 청구를 하세요.", "LAW", "HIGH_SCHOOL", 3, "assertion, demand", None, None),
        ("climate", "/ˈklaɪmɪt/", "기후, 분위기", "noun", "Climate change is serious.", "기후 변화가 심각합니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "weather, atmosphere", None, None),
        ("collection", "/kəˈlɛkʃən/", "수집, 컬렉션", "noun", "She has a stamp collection.", "그녀는 우표 수집을 합니다.", "GENERAL", "ELEMENTARY", 1, "set, assortment", None, None),
        ("competition", "/ˌkɑːmpɪˈtɪʃən/", "경쟁, 대회", "noun", "Enter the cooking competition.", "요리 대회에 참가하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "contest, rivalry", "cooperation", None),
        ("complaint", "/kəmˈpleɪnt/", "불평, 민원", "noun", "Submit a complaint.", "민원을 제출하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "grievance, objection", None, None),
        ("concentrate", "/ˈkɑːnsɛntreɪt/", "집중하다", "verb", "Concentrate on your studies.", "공부에 집중하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "focus, pay attention", "distract, scatter", None),
        ("confident", "/ˈkɑːnfɪdənt/", "자신감 있는", "adjective", "Be confident in yourself.", "자신을 믿고 자신감을 가지세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "assured, self-assured", "insecure, timid", None),
        ("connection", "/kəˈnɛkʃən/", "연결, 관계", "noun", "What is the connection?", "연결고리가 무엇인가요?", "GENERAL", "MIDDLE_SCHOOL", 2, "link, relationship", "disconnection", None),
        ("convenient", "/kənˈviːniənt/", "편리한", "adjective", "Is this convenient for you?", "이것이 당신에게 편리한가요?", "GENERAL", "MIDDLE_SCHOOL", 2, "handy, accessible", "inconvenient", None),
        ("conversation", "/ˌkɑːnvərˈseɪʃən/", "대화", "noun", "Have a conversation.", "대화를 나누세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "dialogue, discussion", None, None),
        ("correct", "/kəˈrɛkt/", "올바른, 맞는", "adjective", "That's the correct answer.", "그것이 정답입니다.", "GENERAL", "ELEMENTARY", 1, "right, accurate", "wrong, incorrect", None),
        ("creative", "/kriˈeɪtɪv/", "창의적인", "adjective", "She is very creative.", "그녀는 매우 창의적입니다.", "ARTS", "MIDDLE_SCHOOL", 2, "imaginative, innovative", None, None),
        ("curious", "/ˈkjʊriəs/", "호기심 많은", "adjective", "I'm curious about science.", "과학에 호기심이 있습니다.", "GENERAL", "ELEMENTARY", 1, "inquisitive", "indifferent", None),
        ("damage", "/ˈdæmɪdʒ/", "손상, 피해", "noun", "The storm caused damage.", "폭풍이 피해를 일으켰습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "harm, destruction", "repair", None),
        ("dangerous", "/ˈdeɪndʒərəs/", "위험한", "adjective", "This road is dangerous.", "이 길은 위험합니다.", "GENERAL", "ELEMENTARY", 1, "hazardous, risky", "safe", None),
        ("date", "/deɪt/", "날짜, 데이트", "noun", "What is today's date?", "오늘 날짜가 어떻게 되나요?", "GENERAL", "ELEMENTARY", 1, "appointment, day", None, None),
        ("delay", "/dɪˈleɪ/", "지연, 미루다", "noun", "There was a delay.", "지연이 있었습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "postpone, hold up", "speed up", None),
        ("deny", "/dɪˈnaɪ/", "부정하다, 거절하다", "verb", "She denied the accusation.", "그녀는 혐의를 부인했습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "refuse, reject", "admit, accept", None),
        ("detail", "/ˈdiːteɪl/", "세부 사항", "noun", "Give me the details.", "세부 사항을 알려주세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "particular, specifics", None, None),
        ("direction", "/dɪˈrɛkʃən/", "방향, 지시", "noun", "Which direction is north?", "어느 방향이 북쪽인가요?", "GENERAL", "ELEMENTARY", 1, "way, course", None, None),
        ("disappear", "/ˌdɪsəˈpɪr/", "사라지다", "verb", "The pain disappeared.", "통증이 사라졌습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "vanish, fade", "appear, emerge", None),
        ("discipline", "/ˈdɪsɪplɪn/", "규율, 훈련", "noun", "Self-discipline is important.", "자기 규율이 중요합니다.", "GENERAL", "HIGH_SCHOOL", 3, "control, order", None, None),
        ("discount", "/ˈdɪskaʊnt/", "할인", "noun", "Get a 20% discount.", "20% 할인을 받으세요.", "BUSINESS", "ELEMENTARY", 1, "reduction, deal", "surcharge", None),
        ("disease", "/dɪˈziːz/", "질병", "noun", "Prevent disease through exercise.", "운동을 통해 질병을 예방하세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "illness, sickness", "health", None),
        ("distance", "/ˈdɪstəns/", "거리", "noun", "The distance is 5 km.", "거리는 5킬로미터입니다.", "GENERAL", "ELEMENTARY", 1, "space, length", None, None),
        ("earn", "/ɜːrn/", "벌다, 얻다", "verb", "She earns a good salary.", "그녀는 좋은 급여를 받습니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "make, gain", "spend, lose", None),
        ("education", "/ˌɛdʒuˈkeɪʃən/", "교육", "noun", "Education is the key to success.", "교육이 성공의 열쇠입니다.", "EDUCATION", "MIDDLE_SCHOOL", 2, "learning, schooling", None, None),
        ("embarrassed", "/ɪmˈbærəst/", "당황한, 창피한", "adjective", "She felt embarrassed.", "그녀는 당황했습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "ashamed, awkward", None, None),
        ("emotion", "/ɪˈmoʊʃən/", "감정", "noun", "Express your emotions.", "감정을 표현하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "feeling, sentiment", None, None),
        ("employee", "/ɛmˈplɔɪiː/", "직원", "noun", "The company has 100 employees.", "회사에 직원이 100명 있습니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "worker, staff", "employer, boss", None),
        ("energy", "/ˈɛnərdʒi/", "에너지", "noun", "Solar energy is renewable.", "태양 에너지는 재생 가능합니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "power, force", None, None),
        ("environment", "/ɪnˈvaɪrənmənt/", "환경", "noun", "Protect the environment.", "환경을 보호하세요.", "SCIENCE", "MIDDLE_SCHOOL", 2, "surroundings, nature", None, None),
        ("equal", "/ˈiːkwəl/", "동등한, 평등한", "adjective", "Everyone should be equal.", "모든 사람은 평등해야 합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "same, equivalent", "unequal, different", None),
        ("examine", "/ɪɡˈzæmɪn/", "검사하다, 살펴보다", "verb", "Examine the patient.", "환자를 검사하세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "inspect, check", None, None),
        ("excellent", "/ˈɛksələnt/", "훌륭한, 우수한", "adjective", "Your work is excellent.", "당신의 작업이 훌륭합니다.", "GENERAL", "ELEMENTARY", 1, "outstanding, superb", "poor, terrible", None),
        ("explore", "/ɪkˈsplɔːr/", "탐험하다, 탐구하다", "verb", "Explore new places.", "새로운 장소를 탐험하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "investigate, venture", None, None),
        ("express", "/ɪkˈsprɛs/", "표현하다", "verb", "Express yourself clearly.", "자신을 명확히 표현하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "communicate, convey", "suppress", None),
        ("failure", "/ˈfeɪljər/", "실패", "noun", "Failure is a part of learning.", "실패는 배움의 일부입니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "defeat, loss", "success", None),
        ("familiar", "/fəˈmɪliər/", "익숙한, 친근한", "adjective", "This place looks familiar.", "이 장소가 익숙해 보입니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "known, acquainted", "unfamiliar, strange", None),
        ("fascinating", "/ˈfæsɪneɪtɪŋ/", "매혹적인", "adjective", "The documentary was fascinating.", "다큐멘터리가 매혹적이었습니다.", "GENERAL", "HIGH_SCHOOL", 3, "captivating, interesting", "boring, dull", None),
        ("flavor", "/ˈfleɪvər/", "맛, 향", "noun", "This has a unique flavor.", "이것은 독특한 맛이 있습니다.", "FOOD", "ELEMENTARY", 1, "taste, aroma", None, None),
        ("fluent", "/ˈfluːənt/", "유창한", "adjective", "She is fluent in three languages.", "그녀는 세 가지 언어를 유창하게 합니다.", "EDUCATION", "HIGH_SCHOOL", 3, "skilled, proficient", None, None),
        ("focus", "/ˈfoʊkəs/", "초점, 집중", "noun", "The focus is on quality.", "초점은 품질에 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "concentration, emphasis", None, None),
        ("freeze", "/friːz/", "얼다, 냉동하다", "verb", "Freeze the leftovers.", "남은 음식을 냉동하세요.", "GENERAL", "ELEMENTARY", 1, "ice, solidify", "melt, thaw", None),
        ("friendly", "/ˈfrɛndli/", "친근한, 다정한", "adjective", "He is very friendly.", "그는 매우 친근합니다.", "GENERAL", "ELEMENTARY", 1, "warm, sociable", "unfriendly, hostile", None),
        ("frustrating", "/ˈfrʌstreɪtɪŋ/", "좌절스러운", "adjective", "It was frustrating.", "좌절스러웠습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "annoying, exasperating", "satisfying", None),
        ("function", "/ˈfʌŋkʃən/", "기능하다", "verb", "The machine functions well.", "기계가 잘 작동합니다.", "GENERAL", "HIGH_SCHOOL", 3, "work, operate", "break down", None),
        ("fundamental", "/ˌfʌndəˈmɛntəl/", "기본적인, 근본적인", "adjective", "This is fundamental.", "이것은 근본적입니다.", "GENERAL", "HIGH_SCHOOL", 3, "basic, essential", "advanced, secondary", None),
        ("future", "/ˈfjuːtʃər/", "미래", "noun", "Plan for the future.", "미래를 계획하세요.", "GENERAL", "ELEMENTARY", 1, "prospect, tomorrow", "past, history", None),
        ("generous", "/ˈdʒɛnərəs/", "관대한, 너그러운", "adjective", "She is very generous.", "그녀는 매우 관대합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "kind, giving", "stingy, selfish", None),
        ("genuine", "/ˈdʒɛnjuɪn/", "진짜의, 진심의", "adjective", "Is this genuine leather?", "이것이 진짜 가죽인가요?", "GENERAL", "HIGH_SCHOOL", 3, "authentic, real", "fake, artificial", None),
        ("global", "/ˈɡloʊbəl/", "세계적인, 전반적인", "adjective", "Climate change is a global problem.", "기후 변화는 세계적인 문제입니다.", "GENERAL", "HIGH_SCHOOL", 3, "worldwide, international", "local, regional", None),
        ("graduate", "/ˈɡrædʒueɪt/", "졸업하다, 졸업생", "verb", "She graduated from university.", "그녀는 대학교를 졸업했습니다.", "EDUCATION", "MIDDLE_SCHOOL", 2, "complete, finish", None, None),
        ("grammar", "/ˈɡræmər/", "문법", "noun", "English grammar is complex.", "영어 문법은 복잡합니다.", "EDUCATION", "MIDDLE_SCHOOL", 2, "syntax, rules", None, None),
        ("handle", "/ˈhændəl/", "처리하다, 다루다", "verb", "Handle with care.", "주의해서 다루세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "manage, deal with", None, None),
        ("hometown", "/ˈhoʊmtaʊn/", "고향", "noun", "My hometown is Seoul.", "내 고향은 서울입니다.", "DAILY_LIFE", "ELEMENTARY", 1, "birthplace, home", None, None),
        ("honest", "/ˈɑːnɪst/", "솔직한, 정직한", "adjective", "Always be honest.", "항상 정직하세요.", "GENERAL", "ELEMENTARY", 1, "truthful, sincere", "dishonest, lying", None),
        ("host", "/hoʊst/", "주최하다, 진행자", "verb", "She hosted the event.", "그녀가 행사를 주최했습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "organize, manage", "attend", None),
        ("human", "/ˈhjuːmən/", "인간의", "adjective", "Kindness is a human quality.", "친절은 인간적인 자질입니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "person, mankind", None, None),
        ("humor", "/ˈhjuːmər/", "유머", "noun", "She has a great sense of humor.", "그녀는 유머 감각이 뛰어납니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "comedy, wit", None, None),
        ("ideal", "/aɪˈdiːəl/", "이상적인", "adjective", "This is an ideal opportunity.", "이것은 이상적인 기회입니다.", "GENERAL", "HIGH_SCHOOL", 3, "perfect, optimal", "imperfect, flawed", None),
        ("identify", "/aɪˈdɛntɪfaɪ/", "확인하다", "verb", "Identify your strengths.", "장점을 파악하세요.", "GENERAL", "HIGH_SCHOOL", 3, "recognize, spot", None, None),
        ("impressive", "/ɪmˈprɛsɪv/", "인상적인", "adjective", "The performance was impressive.", "공연이 인상적이었습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "remarkable, outstanding", "unimpressive", None),
        ("income", "/ˈɪnkʌm/", "수입, 소득", "noun", "My income increased.", "소득이 늘었습니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "earnings, salary", "expense, expenditure", None),
        ("independence", "/ˌɪndɪˈpɛndəns/", "독립", "noun", "Korea gained independence in 1945.", "한국은 1945년 독립을 얻었습니다.", "GENERAL", "HIGH_SCHOOL", 3, "freedom, autonomy", "dependence, reliance", None),
        ("influence", "/ˈɪnfluəns/", "영향, 영향력", "noun", "She has great influence.", "그녀는 큰 영향력이 있습니다.", "GENERAL", "HIGH_SCHOOL", 3, "impact, effect", None, None),
        ("ingredient", "/ɪnˈɡriːdiənt/", "재료, 성분", "noun", "What are the ingredients?", "재료가 무엇인가요?", "FOOD", "MIDDLE_SCHOOL", 2, "component, element", None, None),
        ("injury", "/ˈɪndʒəri/", "부상", "noun", "He suffered a knee injury.", "그는 무릎 부상을 당했습니다.", "SPORTS", "MIDDLE_SCHOOL", 2, "wound, harm", "recovery", None),
        ("innocent", "/ˈɪnəsənt/", "무죄의, 순수한", "adjective", "He was found innocent.", "그는 무죄 판결을 받았습니다.", "LAW", "MIDDLE_SCHOOL", 2, "not guilty, pure", "guilty, corrupt", None),
        ("inspire", "/ɪnˈspaɪər/", "영감을 주다", "verb", "Her story inspires many people.", "그녀의 이야기가 많은 사람에게 영감을 줍니다.", "GENERAL", "HIGH_SCHOOL", 3, "motivate, encourage", "discourage", None),
        ("instead", "/ɪnˈstɛd/", "대신에", "adverb", "Use water instead of soda.", "탄산음료 대신 물을 드세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "rather than, alternatively", None, None),
        ("instruction", "/ɪnˈstrʌkʃən/", "지시, 설명서", "noun", "Read the instructions carefully.", "설명서를 주의 깊게 읽으세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "direction, guide", None, None),
        ("intelligent", "/ɪnˈtɛlɪdʒənt/", "지능적인, 총명한", "adjective", "She is very intelligent.", "그녀는 매우 총명합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "smart, clever", "stupid, dull", None),
        ("interview", "/ˈɪntərvjuː/", "인터뷰, 면접", "noun", "I have a job interview tomorrow.", "내일 취업 면접이 있습니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "meeting, discussion", None, None),
        ("jealous", "/ˈdʒɛləs/", "질투하는", "adjective", "Don't be jealous.", "질투하지 마세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "envious", None, None),
        ("journey", "/ˈdʒɜːrni/", "여행, 여정", "noun", "Life is a journey.", "인생은 여정입니다.", "TRAVEL", "MIDDLE_SCHOOL", 2, "trip, voyage", None, None),
        ("kindness", "/ˈkaɪndnəs/", "친절", "noun", "Kindness is a virtue.", "친절은 덕목입니다.", "GENERAL", "ELEMENTARY", 1, "generosity, compassion", "cruelty, meanness", None),
        ("knowledge", "/ˈnɑːlɪdʒ/", "지식", "noun", "Share your knowledge.", "지식을 나누세요.", "EDUCATION", "MIDDLE_SCHOOL", 2, "understanding, information", "ignorance", None),
        ("lazy", "/ˈleɪzi/", "게으른", "adjective", "Don't be lazy.", "게으르지 마세요.", "GENERAL", "ELEMENTARY", 1, "idle, sluggish", "hardworking, diligent", None),
        ("leadership", "/ˈliːdərʃɪp/", "리더십, 지도력", "noun", "She shows great leadership.", "그녀는 훌륭한 리더십을 보여줍니다.", "BUSINESS", "HIGH_SCHOOL", 3, "guidance, management", None, None),
        ("local", "/ˈloʊkəl/", "지역의, 현지의", "adjective", "Try local food.", "현지 음식을 먹어보세요.", "GENERAL", "ELEMENTARY", 1, "nearby, regional", "foreign, distant", None),
        ("lonely", "/ˈloʊnli/", "외로운", "adjective", "She feels lonely.", "그녀는 외로움을 느낍니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "isolated, alone", "surrounded", None),
        ("luck", "/lʌk/", "운, 행운", "noun", "Good luck to you!", "당신에게 행운이 있기를!", "GENERAL", "ELEMENTARY", 1, "fortune, chance", "misfortune", None),
        ("memory", "/ˈmɛməri/", "기억, 기억력", "noun", "I have a good memory.", "기억력이 좋습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "recollection, remembrance", "forgetfulness", None),
        ("mention", "/ˈmɛnʃən/", "언급하다", "verb", "She mentioned your name.", "그녀가 당신 이름을 언급했습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "refer to, note", None, None),
        ("mistake", "/mɪˈsteɪk/", "실수", "noun", "Everyone makes mistakes.", "모든 사람은 실수를 합니다.", "GENERAL", "ELEMENTARY", 1, "error, fault", None, None),
        ("necessary", "/ˈnɛsəˌsɛri/", "필요한, 필수적인", "adjective", "Is this necessary?", "이것이 필요한가요?", "GENERAL", "MIDDLE_SCHOOL", 2, "essential, required", "unnecessary, optional", None),
        ("negative", "/ˈnɛɡətɪv/", "부정적인", "adjective", "Avoid negative thinking.", "부정적인 생각을 피하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "pessimistic, unfavorable", "positive", None),
        ("noise", "/nɔɪz/", "소음, 잡음", "noun", "The noise is too loud.", "소음이 너무 큽니다.", "DAILY_LIFE", "ELEMENTARY", 1, "sound, racket", "silence, quiet", None),
        ("normal", "/ˈnɔːrməl/", "정상적인, 보통의", "adjective", "Is this normal?", "이것이 정상인가요?", "GENERAL", "ELEMENTARY", 1, "regular, typical", "abnormal, unusual", None),
        ("notice", "/ˈnoʊtɪs/", "알아채다, 공지", "verb", "Did you notice anything?", "무언가 알아챘나요?", "GENERAL", "MIDDLE_SCHOOL", 2, "observe, see", "ignore", None),
        ("offer", "/ˈɔːfər/", "제안, 제공", "noun", "I accepted the job offer.", "취업 제안을 받아들였습니다.", "BUSINESS", "MIDDLE_SCHOOL", 2, "proposal, bid", "rejection", None),
        ("opinion", "/əˈpɪnjən/", "의견", "noun", "What is your opinion?", "의견이 어떻습니까?", "GENERAL", "MIDDLE_SCHOOL", 2, "view, thought", None, None),
        ("opportunity", "/ˌɑːpərˈtuːnɪti/", "기회", "noun", "Take this opportunity.", "이 기회를 잡으세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "chance, occasion", None, None),
        ("organize", "/ˈɔːrɡənaɪz/", "조직하다, 정리하다", "verb", "Organize your workspace.", "작업 공간을 정리하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "arrange, plan", "disorganize, mess up", None),
        ("overcome", "/ˌoʊvərˈkʌm/", "극복하다", "verb", "Overcome your fears.", "두려움을 극복하세요.", "GENERAL", "HIGH_SCHOOL", 3, "conquer, surmount", "give in, surrender", None),
        ("patient", "/ˈpeɪʃənt/", "인내심 있는, 환자", "adjective", "Be patient.", "인내심을 가지세요.", "GENERAL", "ELEMENTARY", 1, "tolerant, calm", "impatient", None),
        ("permanent", "/ˈpɜːrmənənt/", "영구적인", "adjective", "Is this a permanent job?", "이것이 정규직인가요?", "GENERAL", "HIGH_SCHOOL", 3, "lasting, enduring", "temporary, temporary", None),
        ("polite", "/pəˈlaɪt/", "예의 바른", "adjective", "Always be polite.", "항상 예의 바르게 행동하세요.", "GENERAL", "ELEMENTARY", 1, "courteous, well-mannered", "rude, impolite", None),
        ("positive", "/ˈpɑːzɪtɪv/", "긍정적인", "adjective", "Stay positive!", "긍정적으로 지내세요!", "GENERAL", "MIDDLE_SCHOOL", 2, "optimistic, favorable", "negative, pessimistic", None),
        ("prefer", "/prɪˈfɜːr/", "선호하다", "verb", "I prefer coffee.", "커피를 선호합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "favor, like better", "dislike", None),
        ("present", "/ˈprɛzənt/", "현재의, 선물", "adjective", "Be present in the moment.", "현재 순간에 집중하세요.", "GENERAL", "ELEMENTARY", 1, "current, gift", "absent, past", None),
        ("pride", "/praɪd/", "자존심, 자부심", "noun", "Take pride in your work.", "자신의 일에 자부심을 가지세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "honor, dignity", "shame, humility", None),
        ("priority", "/praɪˈɔːrəti/", "우선순위", "noun", "What is your priority?", "우선순위가 무엇인가요?", "GENERAL", "HIGH_SCHOOL", 3, "main concern, importance", None, None),
        ("progress", "/ˈproʊɡrɛs/", "진전, 발전", "noun", "We are making progress.", "진전이 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "advancement, development", "regression", None),
        ("promise", "/ˈprɑːmɪs/", "약속하다", "verb", "Promise me you'll be careful.", "조심하겠다고 약속해 주세요.", "GENERAL", "ELEMENTARY", 1, "pledge, vow", "break a promise", None),
        ("proper", "/ˈprɑːpər/", "적절한, 올바른", "adjective", "Use the proper tool.", "적절한 도구를 사용하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "appropriate, correct", "improper, wrong", None),
        ("punish", "/ˈpʌnɪʃ/", "처벌하다", "verb", "Students should not be punished.", "학생들을 처벌해서는 안 됩니다.", "EDUCATION", "MIDDLE_SCHOOL", 2, "penalize, discipline", "reward, praise", None),
        ("quality", "/ˈkwɑːlɪti/", "품질, 질", "noun", "Quality over quantity.", "양보다 질.", "GENERAL", "MIDDLE_SCHOOL", 2, "standard, excellence", "poor quality", None),
        ("realize", "/ˈriːəlaɪz/", "깨닫다", "verb", "I finally realized the truth.", "마침내 진실을 깨달았습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "understand, recognize", None, None),
        ("recommend", "/ˌrɛkəˈmɛnd/", "추천하다", "verb", "Can you recommend a restaurant?", "식당을 추천해 주시겠어요?", "GENERAL", "MIDDLE_SCHOOL", 2, "suggest, advise", None, None),
        ("refresh", "/rɪˈfrɛʃ/", "새롭게 하다, 상쾌하게 하다", "verb", "Refresh the page.", "페이지를 새로고침하세요.", "TECHNOLOGY", "MIDDLE_SCHOOL", 2, "update, renew", None, None),
        ("regret", "/rɪˈɡrɛt/", "후회하다", "verb", "Don't regret your decision.", "결정을 후회하지 마세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "be sorry, feel bad", None, None),
        ("relationship", "/rɪˈleɪʃənʃɪp/", "관계", "noun", "Build strong relationships.", "강한 관계를 구축하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "bond, connection", None, None),
        ("relax", "/rɪˈlæks/", "긴장을 풀다, 쉬다", "verb", "Relax and take a break.", "긴장을 풀고 휴식을 취하세요.", "GENERAL", "ELEMENTARY", 1, "rest, unwind", "tense up, stress", None),
        ("reliable", "/rɪˈlaɪəbəl/", "신뢰할 수 있는", "adjective", "She is a reliable worker.", "그녀는 신뢰할 수 있는 직원입니다.", "GENERAL", "HIGH_SCHOOL", 3, "dependable, trustworthy", "unreliable", None),
        ("remember", "/rɪˈmɛmbər/", "기억하다", "verb", "Remember to call me.", "나에게 전화하는 것을 기억하세요.", "GENERAL", "ELEMENTARY", 1, "recall, recollect", "forget", None),
        ("responsible", "/rɪˈspɑːnsɪbəl/", "책임있는", "adjective", "Be responsible for your actions.", "자신의 행동에 책임을 지세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "accountable, dependable", "irresponsible", None),
        ("reward", "/rɪˈwɔːrd/", "보상하다, 보상", "verb", "Hard work is rewarded.", "노력은 보상을 받습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "compensate, honor", "punish", None),
        ("satisfied", "/ˈsætɪsfaɪd/", "만족한", "adjective", "Are you satisfied?", "만족하십니까?", "GENERAL", "MIDDLE_SCHOOL", 2, "pleased, content", "dissatisfied, unhappy", None),
        ("schedule", "/ˈskɛdʒuːl/", "일정, 계획표", "noun", "Check your schedule.", "일정을 확인하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "timetable, plan", None, None),
        ("secret", "/ˈsiːkrɪt/", "비밀", "noun", "Keep this a secret.", "이것을 비밀로 해주세요.", "GENERAL", "ELEMENTARY", 1, "mystery, hidden", None, None),
        ("sensitive", "/ˈsɛnsɪtɪv/", "민감한", "adjective", "She is very sensitive.", "그녀는 매우 민감합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "delicate, emotional", "insensitive", None),
        ("separate", "/ˈsɛpəreɪt/", "분리하다, 분리된", "verb", "Separate the recycling.", "재활용품을 분리하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "divide, split", "combine, join", None),
        ("solution", "/səˈluːʃən/", "해결책", "noun", "Find a solution.", "해결책을 찾으세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "answer, remedy", "problem", None),
        ("soul", "/soʊl/", "영혼", "noun", "Music feeds the soul.", "음악은 영혼을 채웁니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "spirit, essence", None, None),
        ("spend", "/spɛnd/", "쓰다, 보내다", "verb", "Spend time with family.", "가족과 시간을 보내세요.", "GENERAL", "ELEMENTARY", 1, "use, invest", "save, earn", None),
        ("stress", "/strɛs/", "스트레스, 강조", "noun", "Manage your stress.", "스트레스를 관리하세요.", "MEDICINE", "MIDDLE_SCHOOL", 2, "pressure, tension", "relaxation", None),
        ("struggle", "/ˈstrʌɡəl/", "분투하다, 어려움", "verb", "Struggle is part of life.", "분투는 삶의 일부입니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "fight, strive", "succeed easily", None),
        ("success", "/səkˈsɛs/", "성공", "noun", "Success requires hard work.", "성공은 노력이 필요합니다.", "GENERAL", "ELEMENTARY", 1, "achievement, triumph", "failure", None),
        ("suitable", "/ˈsuːtəbəl/", "적합한", "adjective", "Is this suitable?", "이것이 적합한가요?", "GENERAL", "HIGH_SCHOOL", 3, "appropriate, fitting", "unsuitable, wrong", None),
        ("tradition", "/trəˈdɪʃən/", "전통", "noun", "Korean traditions are rich.", "한국의 전통은 풍부합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "custom, heritage", None, None),
        ("trust", "/trʌst/", "믿다, 신뢰", "verb", "Trust yourself.", "자신을 믿으세요.", "GENERAL", "ELEMENTARY", 1, "believe, rely on", "distrust, doubt", None),
        ("understand", "/ˌʌndərˈstænd/", "이해하다", "verb", "Do you understand?", "이해하십니까?", "GENERAL", "ELEMENTARY", 1, "comprehend, grasp", "misunderstand", None),
        ("useful", "/ˈjuːsfəl/", "유용한", "adjective", "This is very useful.", "이것은 매우 유용합니다.", "GENERAL", "ELEMENTARY", 1, "helpful, practical", "useless", None),
        ("various", "/ˈvɛriəs/", "다양한", "adjective", "There are various options.", "다양한 선택지가 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "different, diverse", "uniform, same", None),
        ("waste", "/weɪst/", "낭비하다", "verb", "Don't waste time.", "시간을 낭비하지 마세요.", "GENERAL", "ELEMENTARY", 1, "squander, misuse", "save, conserve", None),
        ("wealth", "/wɛlθ/", "부, 재산", "noun", "Health is more important than wealth.", "건강이 부보다 중요합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "riches, fortune", "poverty", None),
        ("wonder", "/ˈwʌndər/", "궁금해하다, 놀라움", "verb", "I wonder what happened.", "무슨 일이 있었는지 궁금합니다.", "GENERAL", "ELEMENTARY", 1, "question, marvel", None, None),
        ("worry", "/ˈwɜːri/", "걱정하다", "verb", "Don't worry about it.", "그것에 대해 걱정하지 마세요.", "GENERAL", "ELEMENTARY", 1, "be concerned, fret", "relax", None),
    ]


if __name__ == "__main__":
    conn = get_connection()
    existing = get_existing_words(conn)
    words = get_words()
    added = add_words(conn, words, existing)
    print(f"배치 2: {added}개 단어 추가")
    print_stats(conn, "배치 2: 중고등 학술 어휘")
    conn.close()
