#!/usr/bin/env python3
"""배치 5: OPIc 레벨별 어휘 (IL~AL 회화 단어)."""
from batch_utils import get_connection, get_existing_words, add_words, print_stats

def get_words():
    return [
        # ===== OPIc IL (Intermediate Low) - 기초 일상 대화 =====
        ("alarm clock", "/əˈlɑːrm klɑːk/", "자명종, 알람 시계", "noun", "Set your alarm clock.", "알람 시계를 맞추세요.", "DAILY_LIFE", "ELEMENTARY", 1, None, None, "OPIc IL"),
        ("apartment", "/əˈpɑːrtmənt/", "아파트", "noun", "I live in an apartment.", "저는 아파트에 살고 있습니다.", "DAILY_LIFE", "ELEMENTARY", 1, "flat, unit", "house", "OPIc IL"),
        ("backyard", "/ˈbækjɑːrd/", "뒤뜰", "noun", "We have a backyard garden.", "뒤뜰에 정원이 있습니다.", "DAILY_LIFE", "ELEMENTARY", 1, "garden, yard", None, "OPIc IL"),
        ("beach", "/biːtʃ/", "해변", "noun", "I go to the beach in summer.", "여름에 해변에 갑니다.", "TRAVEL", "ELEMENTARY", 1, "shore, coast", None, "OPIc IL"),
        ("chore", "/tʃɔːr/", "집안일", "noun", "I do household chores.", "집안일을 합니다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "housework, task", None, "OPIc IL"),
        ("commute", "/kəˈmjuːt/", "통근하다", "verb", "I commute by subway.", "지하철로 통근합니다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "travel, go to work", None, "OPIc IL"),
        ("cook", "/kʊk/", "요리하다", "verb", "I love to cook.", "요리하기를 좋아합니다.", "FOOD", "ELEMENTARY", 1, "prepare food, make meals", "order out", "OPIc IL"),
        ("downtown", "/ˌdaʊnˈtaʊn/", "시내", "noun", "Let's meet downtown.", "시내에서 만납시다.", "DAILY_LIFE", "ELEMENTARY", 1, "city center", "suburbs", "OPIc IL"),
        ("enjoy", "/ɪnˈdʒɔɪ/", "즐기다", "verb", "I enjoy hiking.", "하이킹을 즐깁니다.", "GENERAL", "ELEMENTARY", 1, "like, love", "dislike, hate", "OPIc IL"),
        ("exercise", "/ˈɛksərsaɪz/", "운동하다", "verb", "Exercise every morning.", "매일 아침 운동하세요.", "SPORTS", "ELEMENTARY", 1, "work out, train", "rest", "OPIc IL"),
        ("favorite", "/ˈfeɪvərɪt/", "가장 좋아하는", "adjective", "What's your favorite food?", "좋아하는 음식이 뭐예요?", "GENERAL", "ELEMENTARY", 1, "preferred, beloved", None, "OPIc IL"),
        ("groceries", "/ˈɡroʊsəriz/", "식료품", "noun", "Buy groceries at the store.", "가게에서 식료품을 사세요.", "FOOD", "ELEMENTARY", 1, "food, supplies", None, "OPIc IL"),
        ("hang out", "/hæŋ aʊt/", "놀다, 어울리다", "phrasal verb", "I hang out with friends.", "친구들과 어울립니다.", "DAILY_LIFE", "ELEMENTARY", 1, "spend time, socialize", None, "OPIc IL"),
        ("hobby", "/ˈhɑːbi/", "취미", "noun", "My hobby is reading.", "제 취미는 독서입니다.", "GENERAL", "ELEMENTARY", 1, "interest, pastime", None, "OPIc IL"),
        ("mall", "/mɔːl/", "쇼핑몰", "noun", "Let's go to the mall.", "쇼핑몰에 갑시다.", "DAILY_LIFE", "ELEMENTARY", 1, "shopping center", None, "OPIc IL"),
        ("movie", "/ˈmuːvi/", "영화", "noun", "I love watching movies.", "영화 보는 것을 좋아합니다.", "ARTS", "ELEMENTARY", 1, "film, picture", None, "OPIc IL"),
        ("neighborhood", "/ˈneɪbərˌhʊd/", "이웃, 근처", "noun", "My neighborhood is quiet.", "제 동네는 조용합니다.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "area, district", None, "OPIc IL"),
        ("outdoor", "/ˈaʊtdɔːr/", "야외의", "adjective", "I enjoy outdoor activities.", "야외 활동을 즐깁니다.", "SPORTS", "ELEMENTARY", 1, "outside, open-air", "indoor, inside", "OPIc IL"),
        ("park", "/pɑːrk/", "공원", "noun", "Walk in the park.", "공원에서 산책하세요.", "DAILY_LIFE", "ELEMENTARY", 1, "garden, recreation area", None, "OPIc IL"),
        ("pet", "/pɛt/", "반려동물", "noun", "Do you have a pet?", "반려동물이 있나요?", "DAILY_LIFE", "ELEMENTARY", 1, "animal companion", None, "OPIc IL"),
        ("recipe", "/ˈrɛsɪpi/", "요리법", "noun", "Share your recipe.", "요리법을 공유해 주세요.", "FOOD", "MIDDLE_SCHOOL", 2, "instructions, method", None, "OPIc IL"),
        ("restaurant", "/ˈrɛstərɑːnt/", "음식점, 식당", "noun", "Let's eat at a restaurant.", "식당에서 먹읍시다.", "FOOD", "ELEMENTARY", 1, "eatery, diner", None, "OPIc IL"),
        ("routine", "/ruːˈtiːn/", "일과, 루틴", "noun", "What is your morning routine?", "아침 일과가 어떻게 되나요?", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "habit, schedule", None, "OPIc IL"),
        ("shopping", "/ˈʃɑːpɪŋ/", "쇼핑", "noun", "I go shopping on weekends.", "주말에 쇼핑을 갑니다.", "DAILY_LIFE", "ELEMENTARY", 1, "buying, purchasing", None, "OPIc IL"),
        ("spare time", "/spɛr taɪm/", "여가 시간", "noun", "I read in my spare time.", "여가 시간에 독서를 합니다.", "GENERAL", "ELEMENTARY", 1, "free time, leisure", None, "OPIc IL"),
        ("subway", "/ˈsʌbweɪ/", "지하철", "noun", "Take the subway.", "지하철을 타세요.", "TRAVEL", "ELEMENTARY", 1, "metro, underground", "bus, taxi", "OPIc IL"),
        ("typical", "/ˈtɪpɪkəl/", "전형적인, 보통의", "adjective", "It's a typical workday.", "전형적인 근무일입니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "usual, regular", "unusual, atypical", "OPIc IL"),
        ("vacation", "/veɪˈkeɪʃən/", "방학, 휴가", "noun", "I'm going on vacation.", "휴가를 떠납니다.", "TRAVEL", "ELEMENTARY", 1, "holiday, break", "work", "OPIc IL"),
        ("weekend", "/ˈwiːkɛnd/", "주말", "noun", "What do you do on weekends?", "주말에 무엇을 하나요?", "DAILY_LIFE", "ELEMENTARY", 1, "Saturday and Sunday", "weekday", "OPIc IL"),

        # ===== OPIc IM (Intermediate Mid) - 중간 일상/취미/여행 =====
        ("atmosphere", "/ˈætməsfɪr/", "분위기, 대기", "noun", "The restaurant has a great atmosphere.", "식당 분위기가 좋습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "ambiance, mood", None, "OPIc IM"),
        ("attraction", "/əˈtrækʃən/", "명소, 매력", "noun", "What are the tourist attractions?", "관광 명소가 어디인가요?", "TRAVEL", "MIDDLE_SCHOOL", 2, "sight, landmark", None, "OPIc IM"),
        ("budget", "/ˈbʌdʒɪt/", "예산, 저렴한", "adjective", "I travel on a budget.", "저예산으로 여행합니다.", "TRAVEL", "MIDDLE_SCHOOL", 2, "affordable, economical", "expensive, luxurious", "OPIc IM"),
        ("childhood", "/ˈtʃaɪldhʊd/", "어린 시절", "noun", "Tell me about your childhood.", "어린 시절에 대해 말해주세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "youth, early years", "adulthood", "OPIc IM"),
        ("cuisine", "/kwɪˈziːn/", "요리, 음식 문화", "noun", "I love Korean cuisine.", "한국 요리를 좋아합니다.", "FOOD", "HIGH_SCHOOL", 3, "food, cooking style", None, "OPIc IM"),
        ("destination", "/ˌdɛstɪˈneɪʃən/", "목적지", "noun", "Choose a travel destination.", "여행 목적지를 선택하세요.", "TRAVEL", "MIDDLE_SCHOOL", 2, "goal, endpoint", None, "OPIc IM"),
        ("diary", "/ˈdaɪəri/", "일기", "noun", "I keep a daily diary.", "매일 일기를 씁니다.", "GENERAL", "ELEMENTARY", 1, "journal, log", None, "OPIc IM"),
        ("environment", "/ɪnˈvaɪrənmənt/", "환경, 주변", "noun", "I grew up in a rural environment.", "시골 환경에서 자랐습니다.", "SCIENCE", "MIDDLE_SCHOOL", 2, "surroundings, setting", None, "OPIc IM"),
        ("familiar", "/fəˈmɪliər/", "친숙한, 익숙한", "adjective", "I'm familiar with this place.", "이 장소가 익숙합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "known, acquainted", "unfamiliar", "OPIc IM"),
        ("festival", "/ˈfɛstɪvəl/", "축제", "noun", "Attend the cultural festival.", "문화 축제에 참석하세요.", "ARTS", "ELEMENTARY", 1, "celebration, event", None, "OPIc IM"),
        ("gossip", "/ˈɡɑːsɪp/", "험담, 잡담", "noun", "Don't gossip about others.", "다른 사람에 대한 험담을 하지 마세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "rumor, chat", None, "OPIc IM"),
        ("hang out", "/hæŋ aʊt/", "시간을 보내다", "verb", "We hang out at cafes.", "카페에서 시간을 보냅니다.", "DAILY_LIFE", "ELEMENTARY", 1, "spend time, chill", None, "OPIc IM"),
        ("hiking", "/ˈhaɪkɪŋ/", "하이킹", "noun", "Go hiking on weekends.", "주말에 하이킹하러 가세요.", "SPORTS", "ELEMENTARY", 1, "trekking, walking", None, "OPIc IM"),
        ("impression", "/ɪmˈprɛʃən/", "인상", "noun", "What was your first impression?", "첫인상이 어땠나요?", "GENERAL", "MIDDLE_SCHOOL", 2, "perception, feeling", None, "OPIc IM"),
        ("landscape", "/ˈlændskeɪp/", "풍경, 경치", "noun", "The landscape is beautiful.", "풍경이 아름답습니다.", "TRAVEL", "MIDDLE_SCHOOL", 2, "scenery, view", None, "OPIc IM"),
        ("leisure", "/ˈliːʒər/", "여가", "noun", "I enjoy leisure activities.", "여가 활동을 즐깁니다.", "GENERAL", "HIGH_SCHOOL", 3, "free time, recreation", "work, labor", "OPIc IM"),
        ("lifestyle", "/ˈlaɪfstaɪl/", "생활 방식", "noun", "Adopt a healthy lifestyle.", "건강한 생활 방식을 채택하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "way of life, habits", None, "OPIc IM"),
        ("memory", "/ˈmɛməri/", "추억", "noun", "I have great memories.", "좋은 추억이 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "recollection, souvenir", None, "OPIc IM"),
        ("nostalgia", "/nɑːˈstælɪə/", "향수", "noun", "I feel nostalgia for my hometown.", "고향에 대한 향수를 느낍니다.", "GENERAL", "COLLEGE", 4, "longing, sentimentality", None, "OPIc IM"),
        ("passion", "/ˈpæʃən/", "열정", "noun", "Follow your passion.", "열정을 따르세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "enthusiasm, love", "indifference", "OPIc IM"),
        ("personality", "/ˌpɜːrsəˈnælɪti/", "성격", "noun", "She has a great personality.", "그녀는 성격이 좋습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "character, traits", None, "OPIc IM"),
        ("preference", "/ˈprɛfərəns/", "선호도", "noun", "What are your food preferences?", "음식 선호도가 어떻게 되나요?", "GENERAL", "MIDDLE_SCHOOL", 2, "choice, liking", None, "OPIc IM"),
        ("recommend", "/ˌrɛkəˈmɛnd/", "추천하다", "verb", "I recommend this book.", "이 책을 추천합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "suggest, advise", "warn against", "OPIc IM"),
        ("sightseeing", "/ˈsaɪtsiːɪŋ/", "관광", "noun", "Go sightseeing in the city.", "도시 관광을 하세요.", "TRAVEL", "ELEMENTARY", 1, "tourism, visiting", None, "OPIc IM"),
        ("socialize", "/ˈsoʊʃəlaɪz/", "사교하다", "verb", "I like to socialize.", "사교를 좋아합니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "interact, mingle", "isolate", "OPIc IM"),
        ("souvenir", "/ˌsuːvəˈnɪr/", "기념품", "noun", "Buy a souvenir.", "기념품을 사세요.", "TRAVEL", "MIDDLE_SCHOOL", 2, "memento, keepsake", None, "OPIc IM"),
        ("stressful", "/ˈstrɛsfəl/", "스트레스가 많은", "adjective", "My job is stressful.", "직업이 스트레스가 많습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "demanding, overwhelming", "relaxing", "OPIc IM"),
        ("tradition", "/trəˈdɪʃən/", "전통", "noun", "Respect local traditions.", "지역 전통을 존중하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "custom, heritage", "modern practice", "OPIc IM"),

        # ===== OPIc IH (Intermediate High) - 직장/사회 주제 =====
        ("acknowledge", "/ækˈnɑːlɪdʒ/", "인정하다", "verb", "Acknowledge your weaknesses.", "약점을 인정하세요.", "GENERAL", "HIGH_SCHOOL", 3, "admit, recognize", "deny", "OPIc IH"),
        ("ambitious", "/æmˈbɪʃəs/", "야심 있는", "adjective", "She is very ambitious.", "그녀는 매우 야심 있습니다.", "GENERAL", "HIGH_SCHOOL", 3, "driven, motivated", "unambitious, lazy", "OPIc IH"),
        ("broadminded", "/ˈbrɔːdˈmaɪndɪd/", "열린 마음의", "adjective", "Be broadminded.", "열린 마음을 가지세요.", "GENERAL", "HIGH_SCHOOL", 3, "open-minded, tolerant", "narrow-minded", "OPIc IH"),
        ("characteristic", "/ˌkærəktəˈrɪstɪk/", "특성, 특징", "noun", "Describe your characteristics.", "특성을 묘사해 보세요.", "GENERAL", "HIGH_SCHOOL", 3, "feature, trait", None, "OPIc IH"),
        ("cope with", "/koʊp wɪð/", "대처하다", "phrasal verb", "How do you cope with stress?", "스트레스에 어떻게 대처하나요?", "GENERAL", "HIGH_SCHOOL", 3, "deal with, handle", None, "OPIc IH"),
        ("deadline", "/ˈdɛdlaɪn/", "마감 기한", "noun", "Meet the deadline.", "마감 기한을 맞추세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "due date, cutoff", None, "OPIc IH"),
        ("dedicate", "/ˈdɛdɪkeɪt/", "헌신하다", "verb", "Dedicate yourself to work.", "일에 헌신하세요.", "GENERAL", "HIGH_SCHOOL", 3, "commit, devote", None, "OPIc IH"),
        ("diverse", "/daɪˈvɜːrs/", "다양한", "adjective", "We have a diverse team.", "다양한 팀이 있습니다.", "GENERAL", "HIGH_SCHOOL", 3, "varied, different", "uniform, homogeneous", "OPIc IH"),
        ("efficient", "/ɪˈfɪʃənt/", "효율적인", "adjective", "Work in an efficient manner.", "효율적인 방식으로 일하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "productive, effective", "inefficient", "OPIc IH"),
        ("engagement", "/ɪnˈɡeɪdʒmənt/", "참여, 약혼", "noun", "Increase employee engagement.", "직원 참여도를 높이세요.", "BUSINESS", "HIGH_SCHOOL", 3, "involvement, participation", "disengagement", "OPIc IH"),
        ("ethical", "/ˈɛθɪkəl/", "윤리적인", "adjective", "Act in an ethical manner.", "윤리적으로 행동하세요.", "GENERAL", "HIGH_SCHOOL", 3, "moral, principled", "unethical", "OPIc IH"),
        ("evaluate", "/ɪˈvæljueɪt/", "평가하다", "verb", "Evaluate your performance.", "성과를 평가하세요.", "GENERAL", "HIGH_SCHOOL", 3, "assess, judge", None, "OPIc IH"),
        ("exhausted", "/ɪɡˈzɔːstɪd/", "기진맥진한", "adjective", "I'm completely exhausted.", "완전히 지쳤습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "tired, worn out", "energized, refreshed", "OPIc IH"),
        ("flexible", "/ˈflɛksɪbəl/", "유연한", "adjective", "Stay flexible.", "유연하게 대처하세요.", "GENERAL", "HIGH_SCHOOL", 3, "adaptable", "rigid", "OPIc IH"),
        ("fulfill", "/fʊlˈfɪl/", "이루다", "verb", "Fulfill your dreams.", "꿈을 이루세요.", "GENERAL", "HIGH_SCHOOL", 3, "achieve, realize", "fail", "OPIc IH"),
        ("generation", "/ˌdʒɛnəˈreɪʃən/", "세대", "noun", "Each generation is different.", "각 세대는 다릅니다.", "GENERAL", "HIGH_SCHOOL", 3, "era, age group", None, "OPIc IH"),
        ("habit", "/ˈhæbɪt/", "습관", "noun", "Break bad habits.", "나쁜 습관을 버리세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "custom, routine", None, "OPIc IH"),
        ("impact", "/ˈɪmpækt/", "영향을 미치다", "verb", "It impacts everyone.", "모두에게 영향을 미칩니다.", "GENERAL", "HIGH_SCHOOL", 3, "affect, influence", None, "OPIc IH"),
        ("independent", "/ˌɪndɪˈpɛndənt/", "독립적인", "adjective", "Be financially independent.", "재정적으로 독립하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "self-reliant, autonomous", "dependent, reliant", "OPIc IH"),
        ("initiate", "/ɪˈnɪʃieɪt/", "시작하다, 착수하다", "verb", "Initiate the project.", "프로젝트를 시작하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "start, begin", "end, finish", "OPIc IH"),

        # ===== OPIc AL (Advanced Low) - 고급 회화 =====
        ("absorb", "/əbˈzɔːrb/", "흡수하다, 배우다", "verb", "She absorbs knowledge quickly.", "그녀는 지식을 빠르게 흡수합니다.", "EDUCATION", "HIGH_SCHOOL", 3, "take in, learn", None, "OPIc AL"),
        ("accustomed", "/əˈkʌstəmd/", "익숙한", "adjective", "Get accustomed to changes.", "변화에 익숙해지세요.", "GENERAL", "HIGH_SCHOOL", 3, "used to, familiar", "unaccustomed", "OPIc AL"),
        ("address", "/əˈdrɛs/", "다루다, 언급하다", "verb", "Address the main issues.", "주요 문제를 다루세요.", "GENERAL", "HIGH_SCHOOL", 3, "deal with, tackle", "ignore, avoid", "OPIc AL"),
        ("advocate", "/ˈædvəkɪt/", "지지하다, 옹호자", "verb", "Advocate for equal rights.", "평등권을 지지하세요.", "LAW", "COLLEGE", 4, "support, promote", "oppose", "OPIc AL"),
        ("allocate", "/ˈæləkeɪt/", "할당하다", "verb", "Allocate resources wisely.", "자원을 현명하게 할당하세요.", "BUSINESS", "COLLEGE", 4, "assign, distribute", "withhold", "OPIc AL"),
        ("anticipate", "/ænˈtɪsɪpeɪt/", "예상하다, 기대하다", "verb", "Anticipate problems.", "문제를 예상하세요.", "GENERAL", "HIGH_SCHOOL", 3, "expect, foresee", "be surprised by", "OPIc AL"),
        ("aspire", "/əˈspaɪər/", "열망하다", "verb", "Aspire to be the best.", "최고가 되기를 열망하세요.", "GENERAL", "HIGH_SCHOOL", 3, "aim, strive", None, "OPIc AL"),
        ("articulate", "/ɑːrˈtɪkjuleɪt/", "말로 표현하다, 명확한", "verb", "Articulate your thoughts.", "생각을 말로 표현하세요.", "GENERAL", "COLLEGE", 4, "express, communicate", None, "OPIc AL"),
        ("breakthrough", "/ˈbreɪkθruː/", "획기적 발전", "noun", "A scientific breakthrough.", "과학적 획기적 발전.", "SCIENCE", "COLLEGE", 4, "discovery, advance", "setback", "OPIc AL"),
        ("collaborate", "/kəˈlæbəreɪt/", "협력하다", "verb", "Collaborate to solve problems.", "협력하여 문제를 해결하세요.", "GENERAL", "HIGH_SCHOOL", 3, "cooperate, work together", None, "OPIc AL"),
        ("compelling", "/kəmˈpɛlɪŋ/", "설득력 있는, 매력적인", "adjective", "A compelling argument.", "설득력 있는 주장.", "GENERAL", "COLLEGE", 4, "convincing, attractive", "weak, unconvincing", "OPIc AL"),
        ("compromise", "/ˈkɑːmprəmaɪz/", "타협하다", "verb", "Compromise when necessary.", "필요할 때 타협하세요.", "GENERAL", "HIGH_SCHOOL", 3, "meet halfway, settle", "refuse, stand firm", "OPIc AL"),
        ("conscious", "/ˈkɑːnʃəs/", "의식하는", "adjective", "Be conscious of your impact.", "자신의 영향을 의식하세요.", "GENERAL", "HIGH_SCHOOL", 3, "aware, mindful", "unconscious, unaware", "OPIc AL"),
        ("conviction", "/kənˈvɪkʃən/", "신념, 유죄 판결", "noun", "Speak with conviction.", "확신을 가지고 말하세요.", "GENERAL", "COLLEGE", 4, "belief, certainty", "doubt, uncertainty", "OPIc AL"),
        ("critical", "/ˈkrɪtɪkəl/", "비판적인, 중요한", "adjective", "Critical thinking is important.", "비판적 사고가 중요합니다.", "EDUCATION", "HIGH_SCHOOL", 3, "analytical, vital", "uncritical, trivial", "OPIc AL"),
        ("eloquent", "/ˈɛləkwənt/", "말 잘하는", "adjective", "She is eloquent.", "그녀는 말을 잘합니다.", "GENERAL", "COLLEGE", 4, "well-spoken, articulate", "inarticulate", "OPIc AL"),
        ("empower", "/ɪmˈpaʊər/", "권한을 주다, 능력을 강화하다", "verb", "Empower your team.", "팀에 권한을 주세요.", "GENERAL", "COLLEGE", 4, "enable, strengthen", "disempower", "OPIc AL"),
        ("enlighten", "/ɪnˈlaɪtən/", "계몽하다, 가르치다", "verb", "The lecture enlightened us.", "강의가 우리를 계몽했습니다.", "EDUCATION", "COLLEGE", 4, "educate, inform", "confuse", "OPIc AL"),
        ("evolve", "/ɪˈvɑːlv/", "발전하다, 진화하다", "verb", "Society continues to evolve.", "사회는 계속 발전합니다.", "SCIENCE", "HIGH_SCHOOL", 3, "develop, change", "stagnate, stay the same", "OPIc AL"),
        ("expertise", "/ˌɛkspɜːrˈtiːz/", "전문 지식", "noun", "Develop your expertise.", "전문 지식을 개발하세요.", "GENERAL", "COLLEGE", 4, "skill, proficiency", None, "OPIc AL"),
        ("facilitates", "/fəˈsɪlɪteɪts/", "촉진하다", "verb", "Technology facilitates learning.", "기술이 학습을 촉진합니다.", "GENERAL", "COLLEGE", 4, "enable, assist", "hinder, obstruct", "OPIc AL"),
        ("flexible thinking", "/ˈflɛksɪbəl ˈθɪŋkɪŋ/", "유연한 사고", "noun", "Practice flexible thinking.", "유연한 사고를 연습하세요.", "GENERAL", "COLLEGE", 4, "adaptability, open-mindedness", None, "OPIc AL"),
        ("global perspective", "/ˈɡloʊbəl pərˈspɛktɪv/", "세계적인 관점", "noun", "Adopt a global perspective.", "세계적 관점을 채택하세요.", "GENERAL", "COLLEGE", 4, "international view", "local view", "OPIc AL"),
        ("insight", "/ˈɪnsaɪt/", "통찰력", "noun", "Share your insights.", "통찰을 공유하세요.", "GENERAL", "HIGH_SCHOOL", 3, "understanding, wisdom", None, "OPIc AL"),
        ("integrate", "/ˈɪntɪɡreɪt/", "통합하다", "verb", "Integrate new technologies.", "새 기술을 통합하세요.", "GENERAL", "COLLEGE", 4, "combine, merge", "separate, segregate", "OPIc AL"),
        ("nuanced", "/ˈnjuːɑːnst/", "미묘한", "adjective", "Give a nuanced answer.", "미묘한 답변을 주세요.", "GENERAL", "PROFESSIONAL", 5, "subtle, refined", "simplistic", "OPIc AL"),
        ("navigate", "/ˈnævɪɡeɪt/", "항해하다, 탐색하다", "verb", "Navigate the challenges.", "도전 과제를 헤쳐나가세요.", "GENERAL", "HIGH_SCHOOL", 3, "guide, find way", None, "OPIc AL"),
        ("objective", "/əbˈdʒɛktɪv/", "객관적인", "adjective", "Stay objective.", "객관적으로 유지하세요.", "GENERAL", "HIGH_SCHOOL", 3, "unbiased, impartial", "subjective, biased", "OPIc AL"),
        ("perception", "/pərˈsɛpʃən/", "인식, 지각", "noun", "Change the perception.", "인식을 바꾸세요.", "GENERAL", "COLLEGE", 4, "awareness, understanding", None, "OPIc AL"),
        ("persevere", "/ˌpɜːrsɪˈvɪr/", "끈질기게 계속하다", "verb", "Persevere through hardships.", "어려움을 극복하고 계속하세요.", "GENERAL", "HIGH_SCHOOL", 3, "persist, continue", "give up, quit", "OPIc AL"),
        ("phenomenon", "/fɪˈnɑːmɪnɑːn/", "현상", "noun", "A remarkable phenomenon.", "놀라운 현상.", "SCIENCE", "COLLEGE", 4, "event, occurrence", None, "OPIc AL"),
        ("prioritize", "/praɪˈɔːrɪtaɪz/", "우선순위를 정하다", "verb", "Prioritize tasks.", "업무 우선순위를 정하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "rank, order", None, "OPIc AL"),
        ("sustainable", "/səˈsteɪnəbəl/", "지속 가능한", "adjective", "Choose sustainable options.", "지속 가능한 선택을 하세요.", "SCIENCE", "HIGH_SCHOOL", 3, "lasting, green", "unsustainable", "OPIc AL"),
        ("tackle", "/ˈtækəl/", "대처하다, 맞서다", "verb", "Tackle problems head-on.", "문제에 정면으로 맞서세요.", "GENERAL", "HIGH_SCHOOL", 3, "address, handle", "avoid, ignore", "OPIc AL"),
        ("transformative", "/trænsˈfɔːrmətɪv/", "변혁적인", "adjective", "A transformative experience.", "변혁적인 경험.", "GENERAL", "COLLEGE", 4, "life-changing, revolutionary", "ordinary", "OPIc AL"),
        ("venture", "/ˈvɛntʃər/", "모험하다, 사업", "verb", "Venture into new territory.", "새로운 영역에 도전하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "explore, risk", "stay safe", "OPIc AL"),

        # ===== OPIc 주제별 특화 어휘 =====
        # 집/거주
        ("furnished", "/ˈfɜːrnɪʃt/", "가구가 딸린", "adjective", "Is the apartment furnished?", "아파트에 가구가 있나요?", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "equipped", "unfurnished", "OPIc IM"),
        ("landlord", "/ˈlændlɔːrd/", "집주인", "noun", "Call the landlord.", "집주인에게 전화하세요.", "DAILY_LIFE", "MIDDLE_SCHOOL", 2, "property owner", "tenant", "OPIc IM"),
        ("renovate", "/ˈrɛnəveɪt/", "리모델링하다", "verb", "We renovated the kitchen.", "주방을 리모델링했습니다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, "remodel, restore", None, "OPIc IM"),
        ("tenant", "/ˈtɛnənt/", "세입자", "noun", "The tenant paid rent.", "세입자가 월세를 냈습니다.", "DAILY_LIFE", "HIGH_SCHOOL", 3, "renter, occupant", "landlord", "OPIc IM"),
        # 음식
        ("bland", "/blænd/", "맛이 없는, 싱거운", "adjective", "The soup is bland.", "국이 싱겁습니다.", "FOOD", "MIDDLE_SCHOOL", 2, "tasteless, mild", "spicy, flavorful", "OPIc IL"),
        ("crave", "/kreɪv/", "간절히 원하다, 갈망하다", "verb", "I crave spicy food.", "매운 음식이 먹고 싶습니다.", "FOOD", "MIDDLE_SCHOOL", 2, "desire, long for", None, "OPIc IM"),
        ("portion", "/ˈpɔːrʃən/", "1인분, 몫", "noun", "The portion is large.", "양이 많습니다.", "FOOD", "MIDDLE_SCHOOL", 2, "serving, amount", None, "OPIc IM"),
        ("savory", "/ˈseɪvəri/", "짭짤한, 맛있는", "adjective", "Korean food is savory.", "한국 음식은 짭짤합니다.", "FOOD", "HIGH_SCHOOL", 3, "tasty, flavorful", "bland, sweet", "OPIc IM"),
        ("cuisine", "/kwɪˈziːn/", "요리, 음식", "noun", "I love Korean cuisine.", "한국 요리를 좋아합니다.", "FOOD", "HIGH_SCHOOL", 3, "food, cooking", None, "OPIc IM"),
        # 취미
        ("craft", "/kræft/", "공예, 기술", "noun", "She enjoys handicrafts.", "그녀는 수공예를 즐깁니다.", "ARTS", "MIDDLE_SCHOOL", 2, "art, skill", None, "OPIc IL"),
        ("instrument", "/ˈɪnstrəmənt/", "악기", "noun", "Play an instrument.", "악기를 연주하세요.", "ARTS", "ELEMENTARY", 1, "musical instrument, tool", None, "OPIc IL"),
        ("sketch", "/skɛtʃ/", "스케치하다", "verb", "She loves to sketch.", "그녀는 스케치를 좋아합니다.", "ARTS", "ELEMENTARY", 1, "draw, draft", None, "OPIc IL"),
        ("photography", "/fəˈtɑːɡrəfi/", "사진 촬영", "noun", "Photography is my hobby.", "사진 촬영이 취미입니다.", "ARTS", "MIDDLE_SCHOOL", 2, "taking pictures", None, "OPIc IL"),
        # 학교/교육
        ("curriculum", "/kəˈrɪkjuːləm/", "교육과정", "noun", "The curriculum includes sports.", "교육과정에 스포츠가 포함됩니다.", "EDUCATION", "HIGH_SCHOOL", 3, "program, syllabus", None, "OPIc IH"),
        ("scholarship", "/ˈskɑːlərʃɪp/", "장학금", "noun", "She received a scholarship.", "그녀는 장학금을 받았습니다.", "EDUCATION", "MIDDLE_SCHOOL", 2, "grant, award", None, "OPIc IM"),
        ("semester", "/sɪˈmɛstər/", "학기", "noun", "Final exams are next semester.", "기말고사는 다음 학기입니다.", "EDUCATION", "MIDDLE_SCHOOL", 2, "term, quarter", None, "OPIc IL"),
        ("tuition", "/tjuːˈɪʃən/", "수업료", "noun", "Tuition is expensive.", "수업료가 비쌉니다.", "EDUCATION", "HIGH_SCHOOL", 3, "fees, school fee", None, "OPIc IH"),
    ]


if __name__ == "__main__":
    conn = get_connection()
    existing = get_existing_words(conn)
    words = get_words()
    added = add_words(conn, words, existing)
    print(f"배치 5: {added}개 단어 추가")
    print_stats(conn, "배치 5: OPIc 어휘")
    conn.close()
