#!/usr/bin/env python3
"""배치 4: TOEIC Speaking 레벨별 어휘 (Level 4-8 직장/일상 커뮤니케이션)."""
from batch_utils import get_connection, get_existing_words, add_words, print_stats

def get_words():
    return [
        # ===== TOEIC Speaking Level 4-5 기본 직장 어휘 =====
        # 직장 일상 (회의, 이메일, 업무 요청)
        ("aboard", "/əˈbɔːrd/", "탑승하여, 합류하여", "adverb", "Welcome aboard the team.", "팀에 오신 것을 환영합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "on board", None, "TOEIC Speaking L4"),
        ("absence", "/ˈæbsəns/", "부재, 결석", "noun", "Explain your absence.", "결석 이유를 설명하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "nonattendance, lack", "presence", "TOEIC Speaking L4"),
        ("accomplish", "/əˈkɑːmplɪʃ/", "달성하다, 완수하다", "verb", "We accomplished the goal.", "우리는 목표를 달성했습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "achieve, complete", "fail, abandon", "TOEIC Speaking L4"),
        ("accurate", "/ˈækjərɪt/", "정확한", "adjective", "Please be accurate.", "정확하게 해주세요.", "GENERAL", "HIGH_SCHOOL", 3, "precise, correct", "inaccurate, wrong", "TOEIC Speaking L4"),
        ("acknowledge", "/ækˈnɑːlɪdʒ/", "인정하다, 알림 받다", "verb", "Acknowledge receipt of the email.", "이메일 수신을 확인해 주세요.", "BUSINESS", "HIGH_SCHOOL", 3, "confirm, recognize", "deny, ignore", "TOEIC Speaking L4"),
        ("adapt", "/əˈdæpt/", "적응하다, 조정하다", "verb", "Adapt to changes quickly.", "변화에 빨리 적응하세요.", "GENERAL", "HIGH_SCHOOL", 3, "adjust, modify", "resist", "TOEIC Speaking L4"),
        ("adequate", "/ˈædɪkwɪt/", "충분한, 적절한", "adjective", "Is the budget adequate?", "예산이 충분한가요?", "BUSINESS", "HIGH_SCHOOL", 3, "sufficient, enough", "inadequate, insufficient", "TOEIC Speaking L4"),
        ("administration", "/ədˌmɪnɪˈstreɪʃən/", "행정, 경영", "noun", "Handle the administration.", "행정을 처리하세요.", "BUSINESS", "COLLEGE", 4, "management, governance", None, "TOEIC Speaking L4"),
        ("advantage", "/ədˈvæntɪdʒ/", "이점, 유리함", "noun", "What are the advantages?", "이점이 무엇인가요?", "GENERAL", "MIDDLE_SCHOOL", 2, "benefit, merit", "disadvantage", "TOEIC Speaking L4"),
        ("advisor", "/ədˈvaɪzər/", "조언자, 고문", "noun", "Consult your financial advisor.", "재정 고문과 상담하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "consultant, counselor", None, "TOEIC Speaking L4"),
        ("affordable", "/əˈfɔːrdəbəl/", "저렴한, 알맞은 가격의", "adjective", "Find an affordable option.", "저렴한 옵션을 찾으세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "cheap, reasonable", "expensive, costly", "TOEIC Speaking L4"),
        ("alternative", "/ɔːlˈtɜːrnətɪv/", "대안, 대체", "noun", "Find an alternative solution.", "대안을 찾으세요.", "GENERAL", "HIGH_SCHOOL", 3, "option, choice", None, "TOEIC Speaking L4"),
        ("analyst", "/ˈænəlɪst/", "분석가", "noun", "She works as a business analyst.", "그녀는 비즈니스 분석가입니다.", "BUSINESS", "COLLEGE", 4, "researcher, expert", None, "TOEIC Speaking L4"),
        ("applicant", "/ˈæplɪkənt/", "지원자", "noun", "Fifty applicants applied.", "지원자 50명이 지원했습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "candidate, job seeker", None, "TOEIC Speaking L4"),
        ("appreciate", "/əˈpriːʃieɪt/", "감사하다, 인정하다", "verb", "I appreciate your help.", "도움에 감사드립니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "be grateful, value", "disregard", "TOEIC Speaking L4"),
        ("approval", "/əˈpruːvəl/", "승인", "noun", "Get management approval.", "경영진의 승인을 받으세요.", "BUSINESS", "HIGH_SCHOOL", 3, "consent, authorization", "rejection, denial", "TOEIC Speaking L4"),
        ("arrangement", "/əˈreɪndʒmənt/", "준비, 배열", "noun", "Make arrangements for the meeting.", "회의 준비를 하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "preparation, plan", None, "TOEIC Speaking L4"),
        ("assessment", "/əˈsɛsmənt/", "평가", "noun", "Complete the skills assessment.", "기술 평가를 완료하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "evaluation, appraisal", None, "TOEIC Speaking L4"),
        ("assign", "/əˈsaɪn/", "할당하다, 배정하다", "verb", "Assign tasks to each person.", "각자에게 업무를 할당하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "allocate, delegate", None, "TOEIC Speaking L4"),
        ("association", "/əˌsoʊsiˈeɪʃən/", "협회, 연합", "noun", "She joined the professional association.", "그녀가 전문 협회에 가입했습니다.", "BUSINESS", "COLLEGE", 4, "organization, group", None, "TOEIC Speaking L4"),
        ("attendance", "/əˈtɛndəns/", "출석, 참석", "noun", "Attendance is mandatory.", "출석은 필수입니다.", "EDUCATION", "HIGH_SCHOOL", 3, "presence, participation", "absence", "TOEIC Speaking L4"),
        ("attentive", "/əˈtɛntɪv/", "주의 깊은", "adjective", "Be attentive in meetings.", "회의에서 주의를 기울이세요.", "BUSINESS", "HIGH_SCHOOL", 3, "focused, observant", "inattentive", "TOEIC Speaking L4"),
        ("attract", "/əˈtrækt/", "끌어들이다, 유치하다", "verb", "Attract new customers.", "새 고객을 유치하세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "draw in, appeal to", "repel, drive away", "TOEIC Speaking L4"),
        ("benefit", "/ˈbɛnɪfɪt/", "이익을 얻다, 혜택", "verb", "Both sides benefit.", "양측 모두 이익을 얻습니다.", "BUSINESS", "HIGH_SCHOOL", 3, "gain, profit", "lose", "TOEIC Speaking L4"),
        ("brief", "/briːf/", "간단한, 보고서", "adjective", "Keep it brief.", "간단하게 해주세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "short, concise", "long, detailed", "TOEIC Speaking L4"),
        ("capacity", "/kəˈpæsɪti/", "수용 능력, 용량", "noun", "The hall has a capacity of 500.", "홀은 500명을 수용합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "volume, ability", None, "TOEIC Speaking L4"),
        ("clarity", "/ˈklærɪti/", "명확함", "noun", "Speak with clarity.", "명확하게 말하세요.", "GENERAL", "HIGH_SCHOOL", 3, "clearness, precision", "vagueness, confusion", "TOEIC Speaking L4"),
        ("colleague", "/ˈkɑːliːɡ/", "동료", "noun", "She is my colleague.", "그녀는 제 동료입니다.", "BUSINESS", "HIGH_SCHOOL", 3, "coworker, associate", None, "TOEIC Speaking L4"),
        ("compensate", "/ˈkɑːmpənseɪt/", "보상하다", "verb", "We will compensate you.", "보상해 드리겠습니다.", "BUSINESS", "COLLEGE", 4, "reimburse, pay", None, "TOEIC Speaking L4"),
        ("comprehensive", "/ˌkɑːmprɪˈhɛnsɪv/", "포괄적인", "adjective", "Give a comprehensive report.", "포괄적인 보고서를 제출하세요.", "GENERAL", "HIGH_SCHOOL", 3, "thorough, complete", "partial, limited", "TOEIC Speaking L5"),

        # ===== TOEIC Speaking Level 5-6 =====
        ("concise", "/kənˈsaɪs/", "간결한", "adjective", "Be concise in your email.", "이메일에서 간결하게 쓰세요.", "BUSINESS", "HIGH_SCHOOL", 3, "brief, to the point", "verbose, wordy", "TOEIC Speaking L5"),
        ("conduct", "/kənˈdʌkt/", "실시하다, 행동", "verb", "Conduct the survey.", "설문조사를 실시하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "carry out, perform", None, "TOEIC Speaking L5"),
        ("confidential", "/ˌkɑːnfɪˈdɛnʃəl/", "기밀의, 비밀의", "adjective", "This is confidential.", "이것은 기밀입니다.", "BUSINESS", "HIGH_SCHOOL", 3, "secret, private", "public, open", "TOEIC Speaking L5"),
        ("consecutive", "/kənˈsɛkjutɪv/", "연속적인", "adjective", "Consecutive meetings are tiring.", "연속 회의는 피곤합니다.", "BUSINESS", "COLLEGE", 4, "successive, sequential", "nonconsecutive", "TOEIC Speaking L5"),
        ("constructive", "/kənˈstrʌktɪv/", "건설적인", "adjective", "Give constructive feedback.", "건설적인 피드백을 주세요.", "BUSINESS", "HIGH_SCHOOL", 3, "positive, helpful", "destructive, negative", "TOEIC Speaking L5"),
        ("coordination", "/koʊˌɔːrdɪˈneɪʃən/", "조율, 협력", "noun", "Good coordination is needed.", "좋은 조율이 필요합니다.", "BUSINESS", "COLLEGE", 4, "collaboration, teamwork", None, "TOEIC Speaking L5"),
        ("correspondence", "/ˌkɔːrɪˈspɑːndəns/", "서신, 통신", "noun", "Maintain professional correspondence.", "전문적인 서신을 유지하세요.", "BUSINESS", "COLLEGE", 4, "communication, letters", None, "TOEIC Speaking L5"),
        ("courteous", "/ˈkɜːrtiəs/", "공손한, 예의 바른", "adjective", "Be courteous to customers.", "고객에게 공손하게 대하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "polite, respectful", "rude, impolite", "TOEIC Speaking L5"),
        ("coverage", "/ˈkʌvərɪdʒ/", "보도, 보장 범위", "noun", "Check your insurance coverage.", "보험 보장 범위를 확인하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "scope, extent", None, "TOEIC Speaking L5"),
        ("delay", "/dɪˈleɪ/", "지연시키다", "verb", "Don't delay the decision.", "결정을 미루지 마세요.", "BUSINESS", "MIDDLE_SCHOOL", 2, "postpone, put off", "speed up, rush", "TOEIC Speaking L5"),
        ("delivery", "/dɪˈlɪvəri/", "배달, 전달", "noun", "When is the delivery?", "배달이 언제인가요?", "BUSINESS", "MIDDLE_SCHOOL", 2, "shipment, dispatch", None, "TOEIC Speaking L5"),
        ("demonstrate", "/ˈdɛmənstreɪt/", "시연하다, 증명하다", "verb", "Demonstrate the product.", "제품을 시연하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "show, present", None, "TOEIC Speaking L5"),
        ("department", "/dɪˈpɑːrtmənt/", "부서, 학과", "noun", "Which department are you in?", "어느 부서에 계신가요?", "BUSINESS", "MIDDLE_SCHOOL", 2, "division, section", None, "TOEIC Speaking L5"),
        ("depend", "/dɪˈpɛnd/", "의존하다, 달려 있다", "verb", "It depends on the budget.", "예산에 달려 있습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "rely, hinge on", None, "TOEIC Speaking L5"),
        ("destination", "/ˌdɛstɪˈneɪʃən/", "목적지", "noun", "What is your final destination?", "최종 목적지가 어디인가요?", "TRAVEL", "MIDDLE_SCHOOL", 2, "endpoint, goal", "origin, departure", "TOEIC Speaking L5"),
        ("effective", "/ɪˈfɛktɪv/", "효과적인", "adjective", "This is an effective method.", "효과적인 방법입니다.", "GENERAL", "HIGH_SCHOOL", 3, "successful, productive", "ineffective, useless", "TOEIC Speaking L5"),
        ("eligible", "/ˈɛlɪdʒɪbəl/", "자격이 있는", "adjective", "Are you eligible to apply?", "지원 자격이 있나요?", "BUSINESS", "COLLEGE", 4, "qualified, entitled", "ineligible", "TOEIC Speaking L5"),
        ("emphasis", "/ˈɛmfəsɪs/", "강조", "noun", "Put emphasis on safety.", "안전에 중점을 두세요.", "GENERAL", "HIGH_SCHOOL", 3, "stress, focus", "de-emphasis", "TOEIC Speaking L5"),
        ("ensure", "/ɪnˈʃʊr/", "보장하다, 확실히 하다", "verb", "Ensure quality control.", "품질 관리를 확실히 하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "guarantee, secure", None, "TOEIC Speaking L5"),
        ("enthusiastic", "/ɪnˌθuːziˈæstɪk/", "열정적인", "adjective", "Be enthusiastic about your work.", "업무에 열정적이세요.", "GENERAL", "HIGH_SCHOOL", 3, "passionate, eager", "indifferent, apathetic", "TOEIC Speaking L5"),
        ("equipment", "/ɪˈkwɪpmənt/", "장비, 기기", "noun", "Use proper equipment.", "적절한 장비를 사용하세요.", "GENERAL", "MIDDLE_SCHOOL", 2, "tools, gear", None, "TOEIC Speaking L5"),
        ("expand", "/ɪkˈspænd/", "확장하다, 넓히다", "verb", "Expand your business.", "사업을 확장하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "grow, extend", "shrink, contract", "TOEIC Speaking L5"),
        ("expertise", "/ˌɛkspɜːrˈtiːz/", "전문성", "noun", "Share your expertise.", "전문성을 공유하세요.", "BUSINESS", "COLLEGE", 4, "knowledge, skill", "inexperience", "TOEIC Speaking L5"),
        ("facility", "/fəˈsɪlɪti/", "시설", "noun", "Use the training facilities.", "교육 시설을 이용하세요.", "GENERAL", "HIGH_SCHOOL", 3, "building, center", None, "TOEIC Speaking L5"),
        ("feedback", "/ˈfiːdbæk/", "피드백", "noun", "Give me your feedback.", "피드백을 주세요.", "BUSINESS", "HIGH_SCHOOL", 3, "response, comment", None, "TOEIC Speaking L5"),
        ("flexible", "/ˈflɛksɪbəl/", "유연한", "adjective", "We offer flexible hours.", "유연한 근무 시간을 제공합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "adaptable, adjustable", "rigid, inflexible", "TOEIC Speaking L5"),
        ("follow-up", "/ˈfoʊloʊ ʌp/", "후속 조치", "noun", "Schedule a follow-up meeting.", "후속 회의를 예약하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "continuation, next step", None, "TOEIC Speaking L5"),
        ("former", "/ˈfɔːrmər/", "이전의, 전직", "adjective", "A former employee called.", "전직 직원이 전화했습니다.", "GENERAL", "MIDDLE_SCHOOL", 2, "previous, prior", "current, latter", "TOEIC Speaking L5"),
        ("fulfill", "/fʊlˈfɪl/", "이행하다, 충족하다", "verb", "Fulfill your obligations.", "의무를 이행하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "complete, satisfy", "fail, neglect", "TOEIC Speaking L5"),
        ("fundamental", "/ˌfʌndəˈmɛntəl/", "기본적인, 필수적인", "adjective", "These are fundamental skills.", "이것들은 기본적인 기술입니다.", "GENERAL", "HIGH_SCHOOL", 3, "basic, essential", "trivial, secondary", "TOEIC Speaking L5"),

        # ===== TOEIC Speaking Level 6-7 =====
        ("guarantee", "/ˌɡærənˈtiː/", "보장하다, 보증", "verb", "Guarantee customer satisfaction.", "고객 만족을 보장하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "promise, ensure", "fail to deliver", "TOEIC Speaking L6"),
        ("guideline", "/ˈɡaɪdlaɪn/", "지침", "noun", "Follow the guidelines.", "지침을 따르세요.", "BUSINESS", "HIGH_SCHOOL", 3, "rule, policy", None, "TOEIC Speaking L6"),
        ("hesitate", "/ˈhɛzɪteɪt/", "망설이다", "verb", "Don't hesitate to ask.", "망설이지 말고 물어보세요.", "GENERAL", "HIGH_SCHOOL", 3, "pause, waver", "act, proceed", "TOEIC Speaking L6"),
        ("highlight", "/ˈhaɪlaɪt/", "강조하다, 돋보이게 하다", "verb", "Highlight key points.", "핵심 사항을 강조하세요.", "GENERAL", "HIGH_SCHOOL", 3, "emphasize, feature", "downplay", "TOEIC Speaking L6"),
        ("implication", "/ˌɪmplɪˈkeɪʃən/", "함의, 결과", "noun", "Consider the implications.", "함의를 고려하세요.", "GENERAL", "COLLEGE", 4, "consequence, meaning", None, "TOEIC Speaking L6"),
        ("initiative", "/ɪˈnɪʃɪətɪv/", "주도권, 계획", "noun", "Take the initiative.", "주도권을 잡으세요.", "BUSINESS", "COLLEGE", 4, "lead, action", None, "TOEIC Speaking L6"),
        ("integral", "/ˈɪntɪɡrəl/", "필수적인, 완전한", "adjective", "She is an integral member.", "그녀는 필수적인 구성원입니다.", "GENERAL", "COLLEGE", 4, "essential, crucial", "marginal", "TOEIC Speaking L6"),
        ("integrity", "/ɪnˈtɛɡrɪti/", "성실성, 청렴", "noun", "Act with integrity.", "성실하게 행동하세요.", "BUSINESS", "COLLEGE", 4, "honesty, morality", "dishonesty", "TOEIC Speaking L6"),
        ("intermediate", "/ˌɪntərˈmiːdiɪt/", "중간의", "adjective", "Intermediate-level skills needed.", "중급 수준의 기술이 필요합니다.", "EDUCATION", "HIGH_SCHOOL", 3, "mid-level, moderate", "beginner, advanced", "TOEIC Speaking L6"),
        ("lucrative", "/ˈluːkrətɪv/", "수익성 있는", "adjective", "A lucrative business opportunity.", "수익성 있는 사업 기회.", "BUSINESS", "COLLEGE", 4, "profitable, rewarding", "unprofitable", "TOEIC Speaking L6"),
        ("mandatory", "/ˈmændətɔːri/", "의무적인", "adjective", "Attendance is mandatory.", "출석은 의무적입니다.", "BUSINESS", "HIGH_SCHOOL", 3, "required, compulsory", "optional, voluntary", "TOEIC Speaking L6"),
        ("metrics", "/ˈmɛtrɪks/", "측정 기준", "noun", "Track the key metrics.", "핵심 측정 기준을 추적하세요.", "BUSINESS", "COLLEGE", 4, "measures, data points", None, "TOEIC Speaking L6"),
        ("milestone", "/ˈmaɪlstoʊn/", "이정표, 중요한 단계", "noun", "Reach the project milestone.", "프로젝트 이정표를 달성하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "achievement, benchmark", None, "TOEIC Speaking L6"),
        ("minimize", "/ˈmɪnɪmaɪz/", "최소화하다", "verb", "Minimize waste.", "낭비를 최소화하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "reduce, decrease", "maximize, increase", "TOEIC Speaking L6"),
        ("misconception", "/ˌmɪskənˈsɛpʃən/", "오해", "noun", "Address misconceptions.", "오해를 해소하세요.", "GENERAL", "COLLEGE", 4, "misunderstanding, error", "understanding", "TOEIC Speaking L6"),
        ("momentum", "/moʊˈmɛntəm/", "추진력, 탄력", "noun", "Maintain the momentum.", "추진력을 유지하세요.", "BUSINESS", "COLLEGE", 4, "force, drive", "stagnation", "TOEIC Speaking L6"),
        ("monitor", "/ˈmɑːnɪtər/", "모니터링하다, 감시하다", "verb", "Monitor progress regularly.", "진행 상황을 정기적으로 모니터링하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "track, observe", None, "TOEIC Speaking L6"),
        ("motivation", "/ˌmoʊtɪˈveɪʃən/", "동기, 동기부여", "noun", "What is your motivation?", "동기가 무엇인가요?", "GENERAL", "HIGH_SCHOOL", 3, "drive, incentive", "discouragement", "TOEIC Speaking L6"),
        ("mutual", "/ˈmjuːtʃuəl/", "상호적인, 공동의", "adjective", "Mutual respect is key.", "상호 존중이 핵심입니다.", "GENERAL", "HIGH_SCHOOL", 3, "shared, reciprocal", "one-sided", "TOEIC Speaking L6"),
        ("notification", "/ˌnoʊtɪfɪˈkeɪʃən/", "알림, 통보", "noun", "Send a notification.", "알림을 보내세요.", "GENERAL", "HIGH_SCHOOL", 3, "alert, notice", None, "TOEIC Speaking L6"),
        ("outstanding", "/ˌaʊtˈstændɪŋ/", "뛰어난, 미지불된", "adjective", "Outstanding performance!", "뛰어난 성과입니다!", "GENERAL", "HIGH_SCHOOL", 3, "excellent, unpaid", "poor, settled", "TOEIC Speaking L6"),
        ("oversight", "/ˈoʊvərsaɪt/", "감독, 실수", "noun", "Under management oversight.", "경영진 감독 하에.", "BUSINESS", "COLLEGE", 4, "supervision, error", None, "TOEIC Speaking L6"),
        ("persistent", "/pərˈsɪstənt/", "지속적인, 끈질긴", "adjective", "Be persistent in your efforts.", "노력에 끈기를 가지세요.", "GENERAL", "HIGH_SCHOOL", 3, "determined, tenacious", "giving up, temporary", "TOEIC Speaking L6"),
        ("perspective", "/pərˈspɛktɪv/", "관점", "noun", "Share your perspective.", "관점을 공유하세요.", "GENERAL", "HIGH_SCHOOL", 3, "viewpoint, standpoint", None, "TOEIC Speaking L6"),
        ("preliminary", "/prɪˈlɪmɪnɛri/", "예비의, 예선", "adjective", "Run a preliminary check.", "예비 점검을 하세요.", "GENERAL", "COLLEGE", 4, "initial, preparatory", "final", "TOEIC Speaking L6"),
        ("proactive", "/proʊˈæktɪv/", "적극적인, 주도적인", "adjective", "Take a proactive approach.", "주도적인 접근법을 취하세요.", "BUSINESS", "COLLEGE", 4, "initiative, forward-thinking", "reactive, passive", "TOEIC Speaking L6"),
        ("productivity", "/ˌproʊdʌkˈtɪvɪti/", "생산성", "noun", "Improve productivity.", "생산성을 향상시키세요.", "BUSINESS", "HIGH_SCHOOL", 3, "efficiency, output", "inefficiency", "TOEIC Speaking L6"),
        ("proficiency", "/prəˈfɪʃənsi/", "능숙함", "noun", "Achieve language proficiency.", "언어 능숙도를 달성하세요.", "EDUCATION", "COLLEGE", 4, "skill, expertise", "incompetence", "TOEIC Speaking L6"),
        ("quarterly", "/ˈkwɔːrtərli/", "분기마다", "adverb", "Review results quarterly.", "분기마다 결과를 검토하세요.", "BUSINESS", "COLLEGE", 4, "every three months", None, "TOEIC Speaking L6"),
        ("reconciliation", "/ˌrɛkənsɪliˈeɪʃən/", "화해, 조정", "noun", "Reach a reconciliation.", "화해에 도달하세요.", "BUSINESS", "COLLEGE", 4, "resolution, settlement", "conflict", "TOEIC Speaking L6"),

        # ===== TOEIC Speaking Level 7-8 (고급) =====
        ("restructure", "/riːˈstrʌktʃər/", "구조 조정하다", "verb", "Restructure the department.", "부서를 구조조정하세요.", "BUSINESS", "PROFESSIONAL", 5, "reorganize, reshape", None, "TOEIC Speaking L7"),
        ("revenue stream", "/ˈrɛvɪnjuː striːm/", "수익원", "noun", "Diversify revenue streams.", "수익원을 다각화하세요.", "BUSINESS", "PROFESSIONAL", 5, "income source", None, "TOEIC Speaking L7"),
        ("scalable", "/ˈskeɪləbəl/", "확장 가능한", "adjective", "Build a scalable solution.", "확장 가능한 솔루션을 구축하세요.", "TECHNOLOGY", "PROFESSIONAL", 5, "expandable, flexible", "rigid", "TOEIC Speaking L7"),
        ("stipulate", "/ˈstɪpjuleɪt/", "규정하다, 명시하다", "verb", "The contract stipulates terms.", "계약이 조건을 명시합니다.", "LAW", "PROFESSIONAL", 5, "specify, state", None, "TOEIC Speaking L7"),
        ("streamline", "/ˈstriːmlaɪn/", "간소화하다", "verb", "Streamline the process.", "과정을 간소화하세요.", "BUSINESS", "PROFESSIONAL", 5, "simplify, optimize", "complicate", "TOEIC Speaking L7"),
        ("subcontract", "/ˈsʌbkɑːntrækt/", "하청하다", "verb", "Subcontract the IT work.", "IT 작업을 하청하세요.", "BUSINESS", "PROFESSIONAL", 5, "outsource, delegate", None, "TOEIC Speaking L7"),
        ("synergy", "/ˈsɪnərdʒi/", "시너지", "noun", "Create synergy between teams.", "팀 간에 시너지를 만드세요.", "BUSINESS", "PROFESSIONAL", 5, "cooperation, combined effect", None, "TOEIC Speaking L7"),
        ("transparent", "/trænsˈpærənt/", "투명한", "adjective", "Be transparent with clients.", "고객에게 투명하게 대하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "clear, open", "secretive, opaque", "TOEIC Speaking L7"),
        ("underperform", "/ˌʌndərpərˈfɔːrm/", "기대 이하의 성과를 내다", "verb", "The team underperformed.", "팀이 기대 이하의 성과를 냈습니다.", "BUSINESS", "PROFESSIONAL", 5, "fail, fall short", "excel, outperform", "TOEIC Speaking L7"),
        ("utilize", "/ˈjuːtɪlaɪz/", "활용하다", "verb", "Utilize available resources.", "가용 자원을 활용하세요.", "GENERAL", "COLLEGE", 4, "use, employ", "waste, ignore", "TOEIC Speaking L7"),
        ("validate", "/ˈvælɪdeɪt/", "검증하다", "verb", "Validate the data.", "데이터를 검증하세요.", "GENERAL", "COLLEGE", 4, "confirm, verify", "invalidate, reject", "TOEIC Speaking L7"),
        ("viable", "/ˈvaɪəbəl/", "실행 가능한", "adjective", "Is this a viable option?", "이것이 실행 가능한 옵션인가요?", "BUSINESS", "COLLEGE", 4, "feasible, workable", "unworkable, impractical", "TOEIC Speaking L7"),
        ("yield", "/jiːld/", "산출하다, 양보하다", "verb", "The investment yielded profits.", "투자가 이익을 산출했습니다.", "BUSINESS", "COLLEGE", 4, "produce, generate", "consume", "TOEIC Speaking L8"),
        ("workforce development", "/ˈwɜːrkfɔːrs dɪˈvɛləpmənt/", "인력 개발", "noun", "Invest in workforce development.", "인력 개발에 투자하세요.", "BUSINESS", "PROFESSIONAL", 5, "staff training, HR", None, "TOEIC Speaking L8"),
        ("benchmark", "/ˈbɛntʃmɑːrk/", "기준점으로 삼다", "verb", "Benchmark against competitors.", "경쟁사 대비 기준을 설정하세요.", "BUSINESS", "COLLEGE", 4, "compare, measure", None, "TOEIC Speaking L8"),
        ("contingency", "/kənˈtɪndʒənsi/", "비상 계획", "noun", "Have a contingency plan.", "비상 계획을 준비하세요.", "BUSINESS", "PROFESSIONAL", 5, "backup plan, emergency plan", None, "TOEIC Speaking L8"),
        ("leverage", "/ˈlɛvərɪdʒ/", "활용하다, 지렛대", "verb", "Leverage your network.", "인맥을 활용하세요.", "BUSINESS", "PROFESSIONAL", 5, "use, exploit", None, "TOEIC Speaking L8"),
        ("paradigm", "/ˈpærədaɪm/", "패러다임, 틀", "noun", "A paradigm shift has occurred.", "패러다임 전환이 일어났습니다.", "GENERAL", "PROFESSIONAL", 5, "model, framework", None, "TOEIC Speaking L8"),
        ("stakeholder", "/ˈsteɪkhoʊldər/", "이해관계자", "noun", "Engage all stakeholders.", "모든 이해관계자를 참여시키세요.", "BUSINESS", "PROFESSIONAL", 5, "investor, participant", None, "TOEIC Speaking L8"),
        ("turnover", "/ˈtɜːrnoʊvər/", "이직률, 매출액", "noun", "Reduce employee turnover.", "직원 이직률을 낮추세요.", "BUSINESS", "COLLEGE", 4, "attrition, revenue", None, "TOEIC Speaking L8"),
        ("vague", "/veɪɡ/", "모호한", "adjective", "Your answer was vague.", "답변이 모호했습니다.", "GENERAL", "HIGH_SCHOOL", 3, "unclear, ambiguous", "clear, specific", "TOEIC Speaking L6"),
        ("vendor", "/ˈvɛndər/", "공급업체", "noun", "Select the right vendor.", "올바른 공급업체를 선택하세요.", "BUSINESS", "COLLEGE", 4, "supplier, seller", "buyer", "TOEIC Speaking L5"),

        # ===== 직장/이직 관련 실용 어휘 =====
        ("cover letter", "/ˈkʌvər ˈlɛtər/", "자기소개서 커버레터", "noun", "Write a strong cover letter.", "강력한 커버레터를 작성하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "letter of application", None, "TOEIC Speaking L5"),
        ("internship", "/ˈɪntɜːrnʃɪp/", "인턴십", "noun", "Do an internship.", "인턴십을 하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "apprenticeship, training", None, "TOEIC Speaking L4"),
        ("resignation", "/ˌrɛzɪɡˈneɪʃən/", "사직, 사퇴", "noun", "Submit your resignation.", "사직서를 제출하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "quitting, leaving", None, "TOEIC Speaking L5"),
        ("probation", "/proʊˈbeɪʃən/", "수습 기간", "noun", "Three-month probation period.", "3개월 수습 기간.", "BUSINESS", "COLLEGE", 4, "trial period", None, "TOEIC Speaking L5"),
        ("overtime", "/ˈoʊvərtaɪm/", "초과 근무", "noun", "Work overtime when needed.", "필요할 때 초과 근무하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "extra hours", None, "TOEIC Speaking L4"),
        ("telecommute", "/ˈtɛlɪkəmjuːt/", "재택근무하다", "verb", "She telecommutes three days.", "그녀는 3일 재택근무합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "work from home, remote work", None, "TOEIC Speaking L5"),
        ("benchmark", "/ˈbɛntʃmɑːrk/", "비교 기준", "noun", "Use industry benchmarks.", "업계 기준을 사용하세요.", "BUSINESS", "COLLEGE", 4, "standard, reference", None, "TOEIC Speaking L6"),
        ("revenue", "/ˈrɛvɪnjuː/", "수익", "noun", "Grow annual revenue.", "연간 수익을 성장시키세요.", "BUSINESS", "COLLEGE", 4, "income, earnings", "expenses", "TOEIC Speaking L5"),
        ("client", "/ˈklaɪənt/", "고객, 의뢰인", "noun", "The client is satisfied.", "고객이 만족합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "customer, patron", None, "TOEIC Speaking L4"),
        ("corporate", "/ˈkɔːrpərɪt/", "기업의", "adjective", "Corporate culture matters.", "기업 문화가 중요합니다.", "BUSINESS", "HIGH_SCHOOL", 3, "business, company", None, "TOEIC Speaking L5"),
        ("benchmark", "/ˈbɛntʃmɑːrk/", "기준을 정하다", "noun", "Set performance benchmarks.", "성과 기준을 정하세요.", "BUSINESS", "COLLEGE", 4, "criterion, standard", None, "TOEIC Speaking L6"),
        ("onboarding", "/ˈɑːnbɔːrdɪŋ/", "신입 교육", "noun", "Complete the onboarding process.", "신입 교육 과정을 완료하세요.", "BUSINESS", "COLLEGE", 4, "orientation, training", None, "TOEIC Speaking L5"),
        ("performance review", "/pərˈfɔːrməns rɪˈvjuː/", "성과 평가", "noun", "Prepare for the performance review.", "성과 평가를 준비하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "appraisal, evaluation", None, "TOEIC Speaking L5"),
        ("quarterly report", "/ˈkwɔːrtərli rɪˈpɔːrt/", "분기 보고서", "noun", "Submit the quarterly report.", "분기 보고서를 제출하세요.", "BUSINESS", "COLLEGE", 4, None, None, "TOEIC Speaking L6"),
        ("teleconference", "/ˈtɛlɪkɑːnfərəns/", "전화 회의", "noun", "Join the teleconference.", "전화 회의에 참여하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "conference call, video call", None, "TOEIC Speaking L5"),
        ("workload", "/ˈwɜːrkloʊd/", "업무량", "noun", "Manage your workload.", "업무량을 관리하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "tasks, assignments", None, "TOEIC Speaking L4"),
        ("annual leave", "/ˈænjuəl liːv/", "연차 휴가", "noun", "Take your annual leave.", "연차 휴가를 사용하세요.", "BUSINESS", "HIGH_SCHOOL", 3, "vacation, holiday", None, "TOEIC Speaking L4"),
        ("reimbursement", "/ˌriɪmˈbɜːrsmənt/", "환급, 상환", "noun", "Claim your reimbursement.", "환급을 청구하세요.", "BUSINESS", "COLLEGE", 4, "refund, repayment", None, "TOEIC Speaking L5"),
        ("quarterly earnings", "/ˈkwɔːrtərli ˈɜːrnɪŋz/", "분기 수익", "noun", "Report quarterly earnings.", "분기 수익을 보고하세요.", "BUSINESS", "COLLEGE", 4, None, None, "TOEIC Speaking L6"),
        ("profit margin", "/ˈprɑːfɪt ˈmɑːrdʒɪn/", "이익률", "noun", "Increase the profit margin.", "이익률을 높이세요.", "BUSINESS", "PROFESSIONAL", 5, "margin, return", None, "TOEIC Speaking L7"),
    ]


if __name__ == "__main__":
    conn = get_connection()
    existing = get_existing_words(conn)
    words = get_words()
    added = add_words(conn, words, existing)
    print(f"배치 4: {added}개 단어 추가")
    print_stats(conn, "배치 4: TOEIC Speaking 어휘")
    conn.close()
